### ISSUE TITLE
Extend Swagger 2.0 with additional properties.

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#1]
Initial list is:
- [x] service name `x-serviceName`
- [x] Link to page where you can read how to receive API key, 'x-getApiKey'
- [x] URL on logo, `x-logo`
- [x] Categories tags
- [x] Link to original spec, `x-origin`(Format, FormatVersion, URL)
- [x] Provider name `x-providerName`, suggested by @bobby-brennan

**Comment by bobby-brennan** [comment]
Two more that I was thinking of:
score/popularity (probably shouldn't be part of core Swagger, but will be a useful extension for anyone creating a gallery)
parameter priority - currently parameters are an object, so they have no ordering, even though some parameters are more important than others. This would be helpful for deciding the order of the parameters in a console

**Comment by BSalita** [comment]
I'd like every API provider to provide these URLs. As a developer, I don't like wasting my time hunting down this information.
  
"developerWebsite" // Landing page for developers
"developerApiDocs" // Documentation about APIs
"developerAppConsole" // For creating and maintaining API apps, obtaining OAuth credentials.
"developerOAuthDocs" // Documentation about how to authenticate (usually OAuth).
"developerRegistration" // Where to obtain a developer login and get started consuming APIs.

**Comment by IvanGoncharov** [comment]
@BSalita thank you for input.
Right now I'm fully focused on expanding API collection beyond Google APIs.
My next goal will be to improve quality and usefulness of collection.
That's why user feedback is really important for me.
I send you gitter invitation and I like to chat with you about future of this project.

**Comment by bobby-brennan** [comment]
More requests:
* **parameterOrder**, like in Google API discover format. This helps push important parameters to the top in API consoles and documentation
* **consoleDefault** or **sampleValue** or **example** - to be used to pre-fill the console with sample values, so the user doesn't have to guess what he can type.

**Comment by MikeRalphson** [comment]
@bobby-brennan shared parameters are defined as an object (without explicit ordering), but parameters **where used** are defined in an array, thus ordered. Or are we talking about converting from/to another format?

I'd like to be able to document the existing vendor extensions, and include a note in the FAQ about the upcoming Schema.org Web API discovery format. Then close this issue.

For examples etc, I'd probably suggest once OpenAPI 3 is ratified, we recommend back-porting things like `requestBody.content.examples` to OpenAPI 2 using the same structure and an `x-` prefix if people have a pressing need until OpenAPI 3 becomes dominant. That will make the transition as smooth as possible.

**Comment by bobby-brennan** [comment]
You can forget parameterOrder, you're right that it's already covered.

Backporting examples from OAI3 makes sense to me. I haven't dug too far into the new spec, but as long as there's a field for specifying e.g. an example value for query parameters, that covers my use case.

I've also been using parameter['x-consoleDefault'] to allow API providers to specify what the default value should be in an API console, but I don't think that's critical.

**Comment by MikeRalphson** [comment]
Wiki / FAQ updated. Closing this issue as above.
