### ISSUE TITLE
Add "Ecota.co" API

### ISSUE THREAD

**Issue by maxime-lenne** [APIs-guru/openapi-directory#101]
**Format**: API Blueprint
**Official**: YES
**Url**: http://docs.ecotaco.apiary.io/api-description-document
**Name**: Ecota.co
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/674904964125368320/5Z7DncLT_400x400.png
**Category**: location

**Comment by IvanGoncharov** [comment]
@maxime-lenne Thank you for submission.
I have some problem with converting your API into Swagger format.
But I will try to solve them in the next couple of days.

**Comment by MikeRalphson** [comment]
Same issue as #234 - hardcoded query parameters in URLs?

**Comment by MikeRalphson** [comment]
Not a perfect conversion, but at least we have the API in the collection now. Many thanks for the submission!
