### ISSUE TITLE
Add "Octy AI Retention Toolchain" API

### ISSUE THREAD

**Issue by benpayflic** [APIs-guru/openapi-directory#1014]
**Format**: Postman Collection
**Official**: YES
**Url**: https://www.getpostman.com/collections/f7d9065e5b49314d5a55
**Name**: Octy AI Retention Toolchain
**Category**: machine_learning
**Logo**: https://octy.ai/images/logo/no_text_trans@2x.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
