### ISSUE TITLE
Add "AresPass" API

### ISSUE THREAD

**Issue by aquariuswolf940** [APIs-guru/openapi-directory#1017]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://arespass.net/assets/arespassv1.0-openapi.yaml
**Name**: AresPass
**Category**: security
**Logo**: https://arespass.net/assets/arespass-logo-390x500.png

The AresPass API does a complete analysis of a password. It calculates its entropy and looks for words in several languages, keyboard sequences - QWERTY and Dvorak keyboards - or irregular entropy distribution, to mention some of the analysis carried out.

A detailed report informs about the outcome of all the analysis that were done, including the boundaries of password fragments were randomness is low.

Word search uses out propietary technology that enables multi-language support, full automation - no hints about the language are needed - and leet substitutions. Currently, word search is available for these languages: English, French, German, Italian, Portuguese, Russian and Spanish.

Below is shown an example of a password analysis made by the AresPass API.

![ec-000-2375x3355](https://user-images.githubusercontent.com/107808780/174493136-ed3feb56-e33f-4b66-9426-3b11f2edd5f5.png)

The AresPass API can be found at RapidAPI.com HUB:

https://rapidapi.com/aquariuswolf940/api/arespass

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
