### ISSUE TITLE
Add "Text Generator" API

### ISSUE THREAD

**Issue by lee101** [APIs-guru/openapi-directory#1021]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://textgenerator.app.nz/openapi.json
**Name**: Text Generator
**Category**: machine_learning
**Logo**: https://textgenerator.app.nz/static/img/brain-generated256.png

base url is https://textgenerator.app.nz/

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
