### ISSUE TITLE
Add "Firebase Cloud Messaging API" API

### ISSUE THREAD

**Issue by apgiorgi** [APIs-guru/openapi-directory#1024]
**Format**: Google API Discovery
**Official**: YES
**Url**: https://fcm.googleapis.com/$discovery/rest?version=v1
**Name**: Firebase Cloud Messaging API
**Category**: messaging
**Logo**: https://static.javatpoint.com/tutorial/firebase/images/firebase-cloud-messaging.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
