### ISSUE TITLE
Add "Nautobot REST API" API

### ISSUE THREAD

**Issue by bryanculver** [APIs-guru/openapi-directory#1026]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://main.demo.nautobot.com/api/swagger/
**Name**: Nautobot REST API
**Category**: developer_tools
**Logo**: https://github.com/nautobot/.github/blob/main/profile/nautobot_logo.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
