### ISSUE TITLE
Add "travel" API

### ISSUE THREAD

**Issue by mehdiwihp** [APIs-guru/openapi-directory#1036]
**Format**: Google API Discovery
**Official**: YES
**Url**: https://travelpartner.googleapis.com/$discovery/rest?version=v3
**Name**: TravelPartner
**Category**: marketing
**Logo**: http://www.google.com/images/icons/product/search-32.gif

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
