### ISSUE TITLE
Add "String All In One" API

### ISSUE THREAD

**Issue by alaabenalidev** [APIs-guru/openapi-directory#1037]
**Format**: OpenAPI 3.0
**Official**: NO
**Url**: https://stringallinone.herokuapp.com/
**Name**: String All In One
**Category**: text
**Logo**:

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.

As the URL given errors, I'm closing this, but can reopen if necessary.
