### ISSUE TITLE
Add "https://api.whatsapp.com/send?phone=+989128917805" API

### ISSUE THREAD

**Issue by farnoshteymori** [APIs-guru/openapi-directory#1039]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.whatsapp.com/send?phone=+989128917805
**Name**: https://api.whatsapp.com/send?phone=+989128917805
**Category**: messaging
**Logo**: https://api.whatsapp.com/send?phone=+989128917805

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Rather than an API endpoint, we require a link to an actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.
