### ISSUE TITLE
Generate Swagger file for AWS APIs

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#104]
AWS team describe their API in some homegrown format:
https://github.com/aws/aws-sdk-js/tree/master/apis
So we need to write some converter for it.

**Comment by MikeRalphson** [comment]
@IvanGoncharov I've started some work on this issue.

[Smallest test-case](https://mermade.github.io/swagger/index.html?url=https://raw.githubusercontent.com/Mermade/openC4/master/c4Api/swagger.json#!/default/PutEvents)

**Comment by MikeRalphson** [comment]
@IvanGoncharov and a *slightly* more complex one:

[Amazon S3](https://mermade.github.io/swagger/index.html?url=https://raw.githubusercontent.com/Mermade/openapi_specifications/master/aws/s3.json)

**Comment by IvanGoncharov** [comment]
@MikeRalphson Excellent. I'm taking part in RestFest hackathon so I will check your code in a few days.

**Comment by MikeRalphson** [comment]
@IvanGoncharov @RomanGotsiy Hope you're having a great time. Consider me there in spirit.
