### ISSUE TITLE
Add "SolarEnergyPrediction" API

### ISSUE THREAD

**Issue by zoernert** [APIs-guru/openapi-directory#1044]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://corrently.io/attachments/4
**Name**: SolarEnergyPrediction
**Category**: iot
**Logo**: https://rapidapi.com/cdn/images?url=https://rapidapi-prod-apis.s3.amazonaws.com/4c2152da-94f2-43b5-9eca-ac9665f08d7e.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
