### ISSUE TITLE
Add "Sahha Mental Health API" API

### ISSUE THREAD

**Issue by leotheloser** [APIs-guru/openapi-directory#1045]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://api.sahha.ai/swagger/v1/swagger.json
**Name**: Sahha Mental Health API
**Category**: machine_learning
**Logo**:

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
