### ISSUE TITLE
Add "KumpeApps" API

### ISSUE THREAD

**Issue by justinkumpe** [APIs-guru/openapi-directory#1050]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.kumpeapps.com/python/swagger/swagger.yaml
**Name**: KumpeApps
**Category**: developer_tools
**Logo**: https://api.kumpeapps.com/images/kumpeapps/base_logo_white_background.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
