### ISSUE TITLE
Microsoft Graph v1 description is out of date

### ISSUE THREAD

**Issue by baywet** [APIs-guru/openapi-directory#1054]
Hi Team,
Thanks for the awesome work here!

FYI Microsoft Graph v1.0 description has been out of date for the past 17 months. (microsoft.com:graph) https://github.com/APIs-guru/openapi-directory/tree/main/APIs/microsoft.com/graph. We update it weekly (usually on tuesdays).

Also, could we change the title to "Microsoft Graph v1.0"?

Please let us know if we can help in the process.
Thanks a lot!

**Comment by MikeRalphson** [comment]
Thanks for raising this. I'm just getting back to this project and will be automating as much of the old manual weekly process as possible.

**Comment by baywet** [comment]
no worries, Thanks for keeping this on!
Our descriptions live here https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml
And here https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/beta/openapi.yaml
