### ISSUE TITLE
Add "GererMesAffaires API" API

### ISSUE THREAD

**Issue by fvaletas** [APIs-guru/openapi-directory#1055]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.gerermesaffaires.com/wp-content/uploads/2022/09/GmaAPI-GererMesAffairesAPI-1.0.6-swagger.json
**Name**: GererMesAffaires API
**Category**: storage
**Logo**: https://api.gerermesaffaires.com/wp-content/uploads/2019/10/logo-2019-1.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
