### ISSUE TITLE
Add "IP Address Reputation API" API

### ISSUE THREAD

**Issue by IPQualityScore** [APIs-guru/openapi-directory#1056]
**Format**: Postman Collection
**Official**: YES
**Url**: https://raw.githubusercontent.com/IPQualityScore/IP_Quality_Score_API_Spec/Review1/postman/collections/IP%20API%20Spec%20Review%201.json
**Host**: https://www.ipqualityscore.com
**Name**: IP Reputation API
**Category**: security
**Logo**: https://www.ipqualityscore.com/templates/img/logo.png

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.

**Comment by IPQualityScore** [comment]
Sure, please use the Postman template here: https://github.com/IPQualityScore/IP_Quality_Score_API_Spec

**Comment by MikeRalphson** [comment]
@IPQualityScore - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://raw.githubusercontent.com/IPQualityScore/IP_Quality_Score_API_Spec/Review1/postman/collections/IP%20API%20Spec%20Review%201.json

https://raw.githubusercontent.com/IPQualityScore/IP_Quality_Score_API_Spec/Review1/postman/collections/IP%20API%20Spec%20Review%201.json FC
undefined
 ✗ 
Must have determined servers by now
Saving metadata...
Exiting with 1

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
