### ISSUE TITLE
Add "Groundhog Day API" API

### ISSUE THREAD

**Issue by pcraig3** [APIs-guru/openapi-directory#1057]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.swaggerhub.com/apis/pcraig3/groundhog-day-api/1.2.1
**Host**: https://groundhog-day.com/api/v1
**Name**: Groundhog Day API
**Category**: open_data
**Logo**: https://groundhog-day.com/apple-touch-icon.png

There is also a page here that gives a good overview: https://groundhog-day.com/api

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
