### ISSUE TITLE
Add "trakt" API

### ISSUE THREAD

**Issue by tmcappsph** [APIs-guru/openapi-directory#1062]
**Format**: API Blueprint
**Official**: YES
**Url**: https://trakt.docs.apiary.io/api-description-document
**Name**: trakt
**Category**: entertainment
**Logo**:

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
