### ISSUE TITLE
Add "ZAMG Data Hub" API

### ISSUE THREAD

**Issue by simon04** [APIs-guru/openapi-directory#1065]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://dataset.api.hub.zamg.ac.at/v1/openapi.json
**Name**: ZAMG Data Hub
**Category**: open_data (meteorological data)
**Logo**:  https://data.hub.zamg.ac.at/images/logo.png

Website: https://data.hub.zamg.ac.at/

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
