### ISSUE TITLE
Add "FaceCheck - Search Internet by Face" API

### ISSUE THREAD

**Issue by BumbleBeeeeeeeeeee** [APIs-guru/openapi-directory#1066]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://facecheck.id/Swagger/v1/swagger.json
**Host**: https://facecheck.id/
**Name**: FaceCheck - Search Internet by Face
**Category**: search
**Logo**: https://facecheck.id/img/FaceCheck_logo.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
