### ISSUE TITLE
Easier non-API access

### ISSUE THREAD

**Issue by erunion** [APIs-guru/openapi-directory#1067]
Hey @MikeRalphson! I am integrating this datset into a smoketest suite for an [SDK codegen application](https://github.com/readmeio/api) I'm building at [ReadMe](https://readme.com) and I'd love to eschew retrieving specs over the wire for the test suite and access them locally through something like a git submodule.

What I'm wondering is if you'd be able to compile the JSON that's output to https://api.apis.guru/v2/list.json somewhere into the repo, with pointers for the URLs to the relative filesystem. Would not only make my test suite faster by not having to pull down specs over the wire, but also not blow up your CDN costs from CI jobs.

**Comment by MikeRalphson** [comment]
Hope you found a solution? For future reference the API `list.json` is available in this repo in the `gh-pages` branch. https://raw.githubusercontent.com/APIs-guru/openapi-directory/gh-pages/v2/list.json
