### ISSUE TITLE
github api description (api.github.com) is out of date

### ISSUE THREAD

**Issue by baywet** [APIs-guru/openapi-directory#1069]
Hi there 👋
Just letting you know that the github API description is seriously out of date at this point and needs to be refreshed.
Let me know if you need some help in the process.

**Comment by MikeRalphson** [comment]
github.com APIs updated. Thanks for pointing this out. I'm hopefully getting back to automating more of the API update process.

**Comment by baywet** [comment]
thanks for fixing it! It'd be nice if you could open up a discussion on how people can help with the automations? (instead of saying "I was API X in the index" they could say "here is an automation to keep API X up to date")

**Comment by MikeRalphson** [comment]
Feel free to start a Github discussion on this topic and to expand on your last point.

**Comment by baywet** [comment]
#1109
