### ISSUE TITLE
Add "ContentGroove" API

### ISSUE THREAD

**Issue by chriscgroove** [APIs-guru/openapi-directory#1072]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.contentgroove.com/api-docs/v1/openapi.json
**Name**: ContentGroove
**Category**: media
**Logo**: https://developers.contentgroove.com/static/media/thumbsUp.f7afd0e551ff6e2ff8ede64777ff4e49.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
