### ISSUE TITLE
Add "Stellastra" API

### ISSUE THREAD

**Issue by stellastrareviews** [APIs-guru/openapi-directory#1073]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://stellastra.com/stellastra.json
**Name**: Stellastra
**Category**: security
**Logo**: https://stellastra.com/images/stellastra.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
