### ISSUE TITLE
Add "Vercel" API

### ISSUE THREAD

**Issue by juancampa** [APIs-guru/openapi-directory#1075]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://openapi.vercel.sh
**Name**: Vercel
**Category**: hosting
**Logo**: https://pbs.twimg.com/profile_images/1252531684353998848/6R0-p1Vf_400x400.jpg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
