### ISSUE TITLE
Is the /list.json API still available?

### ISSUE THREAD

**Issue by bali182** [APIs-guru/openapi-directory#1078]
Looking at https://apis.guru/api-doc it looks like there was an endpoint, that allows querying the available APIs.  I noticed it points to a different URL: https://api.apis.guru/list.json, so I tried a few alternatives:

- https://api.apis.guru/list.json
- https://apis.guru/list.json
- https://apis.guru/api/list.json

But all of them come back with a 404. Is the API still available somewhere?

**By the way, big thanks for compiling all these OpenAPI documents, it is an invaluable help when working on OpenAPI tooling!**

**Comment by MikeRalphson** [comment]
Hi, it should be available at https://api.apis.guru/v2/list.json
