### ISSUE TITLE
Add "GSMTasks" API

### ISSUE THREAD

**Issue by rafalkrupinski** [APIs-guru/openapi-directory#1080]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/oeklo/gsmtasks-schema/v2.4.13/GSMTasks.yaml
**Host**: https://api.gsmtasks.com/
**Name**: GSMTasks
**Category**: transport
**Logo**: https://gsmtasks.com/wp-content/uploads/2021/05/cropped-favicon-1-270x270.png

**Comment by MikeRalphson** [comment]
It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://api.gsmtasks.com/docs/schema/

https://api.gsmtasks.com/docs/schema/ Fnetwork timeout at: https://api.gsmtasks.com/docs/schema/
Saving metadata...
Exiting with 1

**Comment by MikeRalphson** [comment]
It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://api.gsmtasks.com/docs/schema/

https://api.gsmtasks.com/docs/schema/ Fnetwork timeout at: https://api.gsmtasks.com/docs/schema/
Saving metadata...
Exiting with 1

**Comment by rafalkrupinski** [comment]
That's right, the last two or three versions are invalid. I've already reported it to the vendor.
I've stashed the latest working version here
https://github.com/oeklo/gsmtasks-schema/blob/v2.4.13/GSMTasks.yaml
it's still supported

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.

**Comment by rafalkrupinski** [comment]
@tonisvain
