### ISSUE TITLE
Add "MineSkin" API

### ISSUE THREAD

**Issue by InventivetalentDev** [APIs-guru/openapi-directory#1083]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.mineskin.org/openapi.yml
**Name**: MineSkin 
**Category**: developer_tools
**Logo**: https://mineskin.org/img/mineskin-x256.png
**Website**: https://mineskin.org/

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
