### ISSUE TITLE
Add "Stream Chat API" API

### ISSUE THREAD

**Issue by jeroenleenarts** [APIs-guru/openapi-directory#1086]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://stream-openapi.s3.us-east-1.amazonaws.com/chat/openapi-latest.yaml
**Name**: Stream Chat API
**Category**: messaging
**Logo**:

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
