### ISSUE TITLE
Add "TeamCity" API

### ISSUE THREAD

**Issue by CodeIdeal** [APIs-guru/openapi-directory#1087]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://www.jetbrains.com/help/teamcity/rest/teamcity-rest-api-documentation.html
**Name**: TeamCity
**Category**: backend
**Logo**: https://upload.wikimedia.org/wikipedia/commons/8/8e/TeamCity_Icon.png

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.
