### ISSUE TITLE
Add "DFlight API" API

### ISSUE THREAD

**Issue by LJKerr** [APIs-guru/openapi-directory#1089]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://dflight-api.ljaero.com/openapi.json
**Name**: DFlight API
**Category**: transport
**Logo**: https://i0.wp.com/ljaero.com/wp-content/uploads/2022/11/dflight-logo.png

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.

**Comment by MikeRalphson** [comment]
It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://dflight-api.ljaero.com/openapi.json

https://dflight-api.ljaero.com/openapi.json FRV ✔ 
Must have determined servers by now
Saving metadata...
Exiting with 1

**Comment by LJKerr** [comment]
Hi @MikeRalphson,
I thought that openapi.json _was_ machine readable. I looked through it to see if there were any obvious errors, the only thing I could think of to change was to add the "servers" entry (have done that now). Is openapi v 3.0.2 not good for you? I could use a different version. Also, I converted the .json to a .yaml file in case that works better. I've attached it here... if it's good, then do you need us to publish it in addition to the .json version of same?
Thanks!
Lisa
[openapi.yaml.txt](https://github.com/APIs-guru/openapi-directory/files/10889817/openapi.yaml.txt)

**Comment by MikeRalphson** [comment]
Hi @LJKerr - I was adding some automation to the API review process and I need to improve the response when `servers` cannot be found. Your definition looks great, I'll add it now. Thanks again.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
