### ISSUE TITLE
Add "ZenoMedia" API

### ISSUE THREAD

**Issue by ZenoAPI** [APIs-guru/openapi-directory#1093]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.zeno.fm/v3/api-docs
**Name**: ZenoMedia
**Category**: media
**Logo**: https://i.postimg.cc/m2vR2wwB/ZenoAPI.png

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.

**Comment by ZenoAPI** [comment]
Hello @MikeRalphson Is this the link you need? https://api.zeno.fm/v3/api-docs we are hoping to be part of the directory.

**Comment by MikeRalphson** [comment]
@ZenoAPI yes, that's the one!

There is one small issue in your definition, the `securityScheme` name `API Key` can't contain a space. If you update this (in two places) to `APIKey` or `API_Key` your definition will validate OK.

**Comment by ZenoAPI** [comment]
I will ask our Devs to update the definition. I will post again once done. Thanks @MikeRalphson for looking into this.

**Comment by ZenoAPI** [comment]
@MikeRalphson kindly check again. our Developer had updated the service.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
