### ISSUE TITLE
Add "SpellCheckPro" API

### ISSUE THREAD

**Issue by VipulBachani** [APIs-guru/openapi-directory#1094]
**Format**: Postman
**Official**: YES
**Url**: https://raw.githubusercontent.com/VipulBachani/SpellCheckerPro/44da96c5bfa723362f5a3d3d6af441a4e818b93a/SpellCheckPro.postman_collection.json
**Name**: SpellCheckPro
**Service**: spellcheckpro
**Category**: text
**Logo**: https://user-images.githubusercontent.com/20950491/213159600-1a685dfa-50b2-4132-a095-8e01dc58ab9d.png

Sample Request:
<img width="644" alt="image" src="https://user-images.githubusercontent.com/20950491/213159313-231b8349-2253-4875-bd36-294cc080586c.png">

**Comment by VipulBachani** [comment]
Sample Request (Postman Collection):
[SpellCheckPro.postman_collection.zip](https://github.com/APIs-guru/openapi-directory/files/10445466/SpellCheckPro.postman_collection.zip)

**Comment by MikeRalphson** [comment]
Hi, do you have a hosted link for the Postman collection (or an OpenAPI definition), that way we can keep your API up to date. Thanks.

**Comment by VipulBachani** [comment]
Hi Mike, Please find below a hosted link for the Postman collection:
https://github.com/VipulBachani/SpellCheckerPro/blob/44da96c5bfa723362f5a3d3d6af441a4e818b93a/SpellCheckPro.postman_collection.json

Regards,
Vipul.

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
