### ISSUE TITLE
Add "OpenAI" API

### ISSUE THREAD

**Issue by darrelmiller** [APIs-guru/openapi-directory#1096]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml
**Name**: OpenAI
**Category**: machine_learning
**Logo**: https://learnodo-newtonic.com/wp-content/uploads/2020/04/Logo-of-OpenAI-768x161.jpg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.

**Comment by JustinGrote** [comment]
@darrelmiller related, I don't think this matches your published anymore, for the reasons mentioned about property references.
