### ISSUE TITLE
Add "Company Logo From Domain" API

### ISSUE THREAD

**Issue by OsakaSaul** [APIs-guru/openapi-directory#1098]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://ritekit.com/api-demo/company-logo
**Name**: Company Logo From Domain
**Service**: company-logo
**Category**: customer_relation
**Logo**: https://cdn.ritekit.com/assets/img/ritekit/logo.svg

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, **Postman** etc)? Without this unfortunately we cannot add the API to the directory.

**Comment by OsakaSaul** [comment]
Sure:
https://documenter.getpostman.com/view/2010712/SzS7Qku5?version=latest#88e611af-5973-4fe6-a4fe-37b8ead77347

The documentation for our other 24 APIs is right there as well.

Best,

Saul Fleischman
CEO at RiteKit <https://ritekit.com/>

**Comment by MikeRalphson** [comment]
Hi, it's the actual collection json link we need, not the generated documentation. From the source of that page

> `meta name="collection-isPublicCollection" content="false"><meta name="ownerId" content="2010712"><meta name="publishedId" content="SzS7Qku5"><meta name="collectionId" content="2010712-300aff1a-bda8-4466-80c7-ea9161dd616b">`

I think the fact the collection itself isn't public is preventing us from using a link such as https://www.postman.com/collections/[2010712-]300aff1a-bda8-4466-80c7-ea9161dd616b

I couldn't find a public workspace for RiteKit, only https://www.postman.com/api-evangelist/workspace/rite-kit/overview
