### ISSUE TITLE
Add "Cisco PSIRT openVuln API" API

### ISSUE THREAD

**Issue by santosomar** [APIs-guru/openapi-directory#110]
**Format**: Swagger 1.x
**Official**: YES
**Url**: https://developer.cisco.com/site/PSIRT/
**Name**: Cisco PSIRT openVuln API

**Comment by santosomar** [comment]
Swagger YAML >> https://github.com/CiscoPSIRT/openVulnAPI/tree/master/swagger

**Comment by IvanGoncharov** [comment]
@santosomar Thanks a lot. Will try to add it tomorrow.

**Comment by santosomar** [comment]
Thank you @IvanGoncharov ! Have a nice weekend!

**Comment by IvanGoncharov** [comment]
@santosomar You have excellent spec no errors no warnings 👍

Does your API have a specific logo or you use CISCO logo?
Can you please host logo inside your repo?
