### ISSUE TITLE
Add "API Wealth Reader" API

### ISSUE THREAD

**Issue by dlozanolu** [APIs-guru/openapi-directory#1102]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.swaggerhub.com/apis/Wealth-Reader/api/1.0.0
**Host**: https://api.wealthreader.com/
**Name**: API Wealth Reader
**Category**: financial
**Logo**: https://www.wealthreader.com/i/wealthreader.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
