### ISSUE TITLE
Add "Go-UPC Barcode API" API

### ISSUE THREAD

**Issue by blizzrdof77** [APIs-guru/openapi-directory#1103]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://gist.githubusercontent.com/blizzrdof77/c3aa75284830179b44acc1aebd236e1a/raw/437d7bbb822f069efd700f1081a55f421bb3453d/go-upc-barcode-api-definition.yaml
**Name**: Go-UPC Barcode API
**Category**: developer_tools
**Logo**: https://go-upc.com/img/favicon.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.

**Comment by blizzrdof77** [comment]
Thanks! @JustAHappyKid
