### ISSUE TITLE
Add "SimpliVPN VPN API" API

### ISSUE THREAD

**Issue by Ezchan** [APIs-guru/openapi-directory#1104]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.simplivpn.net/swagger/v1/swagger.json
**Name**: SimpliVPN VPN API
**Category**: security
**Logo**: https://simplivpn.net/wp-content/uploads/2022/12/logos.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
