### ISSUE TITLE
Add "Color Names" API

### ISSUE THREAD

**Issue by meodai** [APIs-guru/openapi-directory#1107]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.color.pizza/v1/
**Name**: Color Names
**Category**: media
**Logo**: https://github.com/meodai/color-name-api/raw/main/logo.png

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.

**Comment by meodai** [comment]
@MikeRalphson thanks for getting back to me. That is the file: https://github.com/meodai/color-name-api/blob/main/color-names-v1-OpenAPI.yml does it need to be served on an endpoint of the API itself? Sorry I'm a total API n00b

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.

**Comment by meodai** [comment]
@MikeRalphson it was harder than it should be. but thank you :D There are great linters out there, but I fail to produce a good looking documentation from it.
