### ISSUE TITLE
Non-string parameter types with minLength/maxLength properties (e.g. clickmeter v2)

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/openapi-directory#111]
As discussed, the clickmeter v2 API contains parameters of type 'integer' which have 'minLength' and 'maxLength' properties, which are only applicable to parameters of type 'string'.

@bigstickcarpet A modified version of the [bigstickcarpet swagger-parser](https://github.com/BigstickCarpet/swagger-parser)  is in progress:

``` json
{
  "name": "SyntaxError",
  "message": "Validation failed. Parameter offset at /paths/account/domainwhitelist/get is not of type string, therefore cannot have a minLength property",
  "stack": "SyntaxError: Validation failed. Parameter offset at /paths/account/domainwhitelist/get is not of type string, therefore cannot have a minLength property"
}
```

I just need to check the other parameter properties **and formats** directly inherited from the JSON schema.

Is https://github.com/APIs-guru/OpenAPI-Lint up-to-date? It doesn't currently have many checkers so there are not many examples of the correct way to add this validation.

**Comment by MikeRalphson** [comment]
Similiar problems affect the daisycon/1.0.0, owler 1.0.0 and hetras-certification/booking/v0 specifications. Do you want these raising as separate issues?

**Comment by IvanGoncharov** [comment]
> Do you want these raising as separate issues?

@MikeRalphson No need, since it should be fixed with the same script.

**Comment by MikeRalphson** [comment]
It's also worth checking the other invalid type/property combinations, e.g.:

````json
API name: hetras Booking API Version 0, Version: v0
{
  "name": "SyntaxError",
  "message": "Validation failed. Parameter adults at /paths/api/booking/v0/addons/get is not a numeric type, therefore cannot have a ``minimum`` property",
  "stack": "SyntaxError: Validation failed. Parameter adults at /paths/api/booking/v0/addons/get is not a numeric type, therefore cannot have a ``minimum`` property"}
````

Which applies to non-integer/number types with `minimum`,`maximum`,`exclusiveMinimum`,`exclusiveMaximum` and `multipleOf` properties.

Because the bigstickcarpet swagger-parser stops at the first error, there may also be 'hidden' errors in type/format combinations.

The 'byte' format here (for the same spec) seems likely to be a bug and would get picked up if the adults parameter was changed to an integer type:

````yaml
        - description: Number of adults per room.
          format: byte
          in: query
          maximum: 255
          minimum: 1
          name: adults
          required: true
          type: string
````

**Comment by IvanGoncharov** [comment]
@MikeRalphson How critical it for your use case?
We plan to release the first version of our validator in a few months, and then update scripts to fix some of the errors automatically.

If it's critical I can think of some hack to handle it this week.

**Comment by MikeRalphson** [comment]
@IvanGoncharov absolutely **not** critical, I am just using the APIs.guru collection as a set of tests for [openapi_optimise](https://github.com/mermade/openapi_optimise), I can easily make the validation optional or blacklist the affected specs.
