### ISSUE TITLE
Preferred version googleapis.com:cloudresourcemanager is not up-to-date on /v2/list.json endpoint

### ISSUE THREAD

**Issue by lomeshpatel** [APIs-guru/openapi-directory#1111]
It appears [/v2/list.json](https://api.apis.guru/v2/list.json) has not been updated with the latest preferred version for `googleapis.com:cloudresourcemanager`.

It currently points to `v2beta1`, but the current preferred version according to [Google API Discovery Service](https://developers.google.com/discovery/v1/reference/apis/list?apix_params=%7B%22name%22%3A%22cloudresourcemanager%22%2C%22preferred%22%3Atrue%7D) is `v3`, which is drastically different and contains important endpoints like `/v3/projects` missing in `v2beta1` version.

I also see that [OpenApi Spec for v3](https://github.com/APIs-guru/openapi-directory/blob/main/APIs/googleapis.com/cloudresourcemanager/v3/openapi.yaml) has already been generated. It would be a great help if [/v2/list.json](https://api.apis.guru/v2/list.json) is updated to return the correct preferred version.

If there's anything I can do to help making this change, please let me know.

**Comment by MikeRalphson** [comment]
Thanks for pointing this out, I have implemented a fix and will check that tonight's run picks up the correct flags.

**Comment by MikeRalphson** [comment]
Had to fix a further bug related to alternate versions being output to `list.json` but the `cloudresourcemanager` API preferred version is now correctly set to `v3`.

Thanks again for raising this issue.
