### ISSUE TITLE
Add "Token Metrics Data API" API

### ISSUE THREAD

**Issue by azeemkafridi** [APIs-guru/openapi-directory#1112]
**Format**: Postman
**Official**: YES
**Url**: https://www.postman.com/collections/25954042-3a7b5f30-f598-4f9e-ba5f-4ebb58a1f18d
**Name**: Token Metrics Data API
**Category**: financial
**Logo**: https://files.readme.io/53cd56d-2d5efc7-logo.svg

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.

**Comment by azeemkafridi** [comment]
Here's a link to Postman: https://www.postman.com/token-metrics/workspace/token-metrics-crypto-data-api/collection/25954042-3a7b5f30-f598-4f9e-ba5f-4ebb58a1f18d?action=share&creator=25954042

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
