### ISSUE TITLE
Add "NBA stats data" API

### ISSUE THREAD

**Issue by dheeraj-turing** [APIs-guru/openapi-directory#1113]
**Format**: Postman
**Official**: NO
**Url**: https://www.postman.com/collections/c51c3810db2ab3ca4ab4
**Name**: NBA stats data
**Category**: open_data
**Logo**: https://app.balldontlie.io/favicon.ico

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
