### ISSUE TITLE
Remove outdated/duplicate Xero.com Swagger spec

### ISSUE THREAD

**Issue by pimterry** [APIs-guru/openapi-directory#1116]
The [Xero.com directory](https://github.com/APIs-guru/openapi-directory/tree/main/APIs/xero.com) contains a set of individual specs for various components of their API, plus a 2.0 folder, which contains an [old Swagger spec](https://github.com/APIs-guru/openapi-directory/blob/main/APIs/xero.com/2.0/swagger.yaml) whose [origin](https://raw.githubusercontent.com/XeroAPI/Xero-OpenAPI/master/spec/accounting2.yaml) returns a 404.

As far as I can tell, this was removed some time ago - the other specs are intended to replace it, and this spec duplicates (conflictingly) many endpoints that are now better defined in their new OpenAPI specs.

I think we can just drop this 2.0 spec entirely.

Might also be worth adding automation one day, to warn about/automatically remove specs which are replaced like this (e.g. which begin 404ing indefinitely).

**Comment by MikeRalphson** [comment]
Thanks for the detailed write-up. Will sort tomorrow. In the meantime, please see https://github.com/APIs-guru/openapi-directory/discussions/1110

**Comment by MikeRalphson** [comment]
![image](https://user-images.githubusercontent.com/21603/223369826-dda8975e-65d5-4124-8719-d5d5fb3334cd.png)
