### ISSUE TITLE
Update "ProxyKingdom" API

### ISSUE THREAD

**Issue by bokklu** [APIs-guru/openapi-directory#1121]
New Details:
(Please note that only the logo changed)

Format: OpenAPI 3.0
Official: YES
Url: https://api.proxykingdom.com/swagger/v1/swagger.json
Name: ProxyKingdom
Category: developer_tools
Logo: https://i.imgur.com/9ojm4rP.jpeg

One more thing which I noticed is that after the last CI build the API was added having an x-origin of imgur.com, but instead should be proxykingdom.com:
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/imgur.com/v1/openapi.yaml

How can we fix this?

Thanks a bunch!

**Comment by MikeRalphson** [comment]
Thanks, I can fix up the origin, there was a short-lived bug related to image urls.

**Comment by MikeRalphson** [comment]
Have re-added the API with the correct origin and the new logo URL. Will be live after tonight's CI run. Thanks again for letting me know.
