### ISSUE TITLE
Add "free stock quote" API

### ISSUE THREAD

**Issue by sharpxiayan** [APIs-guru/openapi-directory#1123]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://quote.tradeswitcher.com/quote-stock-api
**Name**: free stock quote
**Category**: financial
**Logo**: https://github.com/CTradeExchange/free-quote

**Comment by MikeRalphson** [comment]
@sharpxiayan - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://quote.tradeswitcher.com/quote-stock-api

https://quote.tradeswitcher.com/quote-stock-api F 404 
Saving metadata...
Exiting with 1
