### ISSUE TITLE
Add "Chaingateway.io Blockchain API" API

### ISSUE THREAD

**Issue by chaingateway** [APIs-guru/openapi-directory#1127]
**Format**: Postman Collection
**Official**: YES
**Url**: https://raw.githubusercontent.com/chaingateway/api-specification/main/Chaingateway.io.postman_collection.json
**Name**: Chaingateway.io Blockchain API
**Category**: payment
**Logo**: https://v1.chaingateway.io/img/Logo_gradient_1000x1000.png

**Comment by MikeRalphson** [comment]
@chaingateway - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://raw.githubusercontent.com/chaingateway/api-specification/main/Chaingateway.io.postman_collection.json

https://raw.githubusercontent.com/chaingateway/api-specification/main/Chaingateway.io.postman_collection.json FCV
Identical path templates detected
#/paths/~1v2~1ethereum~1webhooks~1notifications~1failed~1{notification_id}
 ✗ 
chaingateway.io
Saving metadata...
Exiting with 1

**Comment by chaingateway** [comment]
Hello. We have updated the linked specification file and hope it is valid now.

**Comment by MikeRalphson** [comment]
Automated checks succeeded.
