### ISSUE TITLE
Proposal: make x-origin into an array of the current structure

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/openapi-directory#113]
This would allow recording of the entire journey of the specification, e.g. in cases where the spec. has been converted from another format first before importing into APIs.guru. Either way from earliest to latest or the reverse would be meaningful. I'm not sure if recording where a spec has been assembled from multiple files is useful or overkill...

It may also be useful when (if?) APIs.guru migrates to OpenApi 3.x in the future.

**Comment by MikeRalphson** [comment]
See similar thoughts here http://apievangelist.com/2017/03/06/thinking-about-openapi-provenance/

**Comment by IvanGoncharov** [comment]
@MikeRalphson I doubt that anybody using `x-origin` for something so it shouldn't be breaking change. But I need to adjust all my scripts and wrote one more script to convert format in all existing `swagger.yaml`.
Will try to find some time in the next few weeks.

**Comment by MikeRalphson** [comment]
@IvanGoncharov excellent - not urgent. So if I add an `x-origin` to one of my specs (say the BBC one), you would merge your `x-origin` entry into the existing array / structure?

cc @kinlane does this obviate the need for `x-provenance` or were you thinking of adding other fields? It would be good to keep the number of vendor extensions as low as possible.

**Comment by IvanGoncharov** [comment]
> So if I add an x-origin to one of my specs (say the BBC one), you would merge your x-origin entry into the existing array / structure?

@MikeRalphson Yes if I detect it present then I will append to it instead of overriding.

**Comment by IvanGoncharov** [comment]
> existing array / structure

@MikeRalphson  According to spec JSON doesn't preserve orders of keys in an object so the only possible option is an array.

**Comment by kinlane** [comment]
Yes, if it becomes an array / struct it would meet my needs. My primary objective is just showing entire history. I'd prefer to work with existing OpenAPI extensions so that maybe they have enough usage to become part of spec eventually.

**Comment by MikeRalphson** [comment]
While w're discussing this, is it ok to 'reserve' the optional property `converter` within the structure as follows?

````json
  "x-origin": [
    {
      "url": "http://petstore.swagger.io/v2/swagger.json",
      "format": "swagger",
      "version": "2.0",
      "converter": {
        "url": "https://github.com/mermade/swagger2openapi",
        "version": "1.1.16"
      }
    }
  ],
````

and have `contentType` as an optional alternative to the `format` property?

**Comment by kinlane** [comment]
Hey @MikeRalphson I like the converter, as I use a variety of converters (custom, API Transformer), but I think I could also make this work for scraping too. I have a custom scraper that I use to take static docs and turn them into OpenAPI, I can reference the URL for this as well.

**Comment by MikeRalphson** [comment]
Definitions and scripts updated.
