### ISSUE TITLE
Add "Accounting API" API

### ISSUE THREAD

**Issue by dcoplowe** [APIs-guru/openapi-directory#1133]
**Format**: OpenAPI 3.1.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/codatio/oas/main/json/Codat-Accounting.json
**Name**: Accounting API
**Category**: financial
**Logo**: https://static.codat.io/public/branding/codat-icon-blue.svg

**Comment by MikeRalphson** [comment]
@dcoplowe - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://raw.githubusercontent.com/codatio/oas/main/json/Codat-Accounting.json

https://raw.githubusercontent.com/codatio/oas/main/json/Codat-Accounting.json FRUV
Must be an OpenAPI 3.0.x document
#/
 ✗ 
Provider: codat.io Fixes: 0
Saving metadata...
Exiting with 1

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
