### ISSUE TITLE
Add "Sync For Commerce" API

### ISSUE THREAD

**Issue by dcoplowe** [APIs-guru/openapi-directory#1138]
**Format**: OpenAPI 3.1.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/codatio/oas/main/json/Codat-Sync-Commerce.json
**Name**: Sync For Commerce API
**Category**: ecommerce
**Logo**: https://static.codat.io/public/branding/codat-icon-blue.svg

**Comment by MikeRalphson** [comment]
@dcoplowe - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
