### ISSUE TITLE
Add "Chain49 Blockchain API" API

### ISSUE THREAD

**Issue by hardest1** [APIs-guru/openapi-directory#1142]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://docs.chain49.com/schema/openapi.yaml
**Name**: Chain49 Blockchain API
**Category**: cloud
**Logo**: https://docs.chain49.com/slate/img/horizontal-colored.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
