### ISSUE TITLE
Add "SafetyLine" API

### ISSUE THREAD

**Issue by g4mb10r** [APIs-guru/openapi-directory#1143]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.slmonitor.com/swagger/v2.1/swagger.json
**Name**: SafetyLine
**Category**: enterprise
**Logo**: https://images.squarespace-cdn.com/content/v1/5da0d7a42ae7d60e27334f91/1599832509107-MH74LTAWZ4N33TPMZP6M/SafetyLine%2BLogo-min.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
