### ISSUE TITLE
Add "SpaceTraders" API

### ISSUE THREAD

**Issue by Quazaka** [APIs-guru/openapi-directory#1145]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/SpaceTradersAPI/api-docs/main/reference/SpaceTraders.json
**Name**: SpaceTraders
**Category**: entertainment
**Logo**: https://spacetraders.io/logo/logo-over-black.svg

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
