### ISSUE TITLE
Source code for the APIs/googleapis.com openAPI definitions

### ISSUE THREAD

**Issue by PriyankaHariharan** [APIs-guru/openapi-directory#1146]
Hi team, I was wondering if you could point me to the source code of the discovery service definitions of the googleapis? I was looking at [this - google-api-dotnet-client/DiscoveryJson ](https://github.com/googleapis/google-api-dotnet-client/tree/main/DiscoveryJson)but there are some differences I'm noticing.

Thank you in advance!

**Comment by MikeRalphson** [comment]
Sure thing. Go to the index page at  https://www.googleapis.com/discovery/v1/apis - then download all the linked discovery documents.

**Comment by MikeRalphson** [comment]
Shout if you need anything else.
