### ISSUE TITLE
Add "Mailchimp" API

### ISSUE THREAD

**Issue by hugoattal** [APIs-guru/openapi-directory#1147]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.mailchimp.com/schema/3.0/Swagger.json?expand
**Name**: Mailchimp
**Category**: messaging
**Logo**: https://eep.io/images/yzco4xsimv0y/10ZRu9hZ1QQ5u1QQMu7qN1/57f679c6e8f6dd60a01d54f870fae6b7/MC_50-50_-_Brand_Assets_03.png?w=980&fm=webp&q=70

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
