### ISSUE TITLE
Add "The Movie DB" API

### ISSUE THREAD

**Issue by calebhearth** [APIs-guru/openapi-directory#1148]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://developer.themoviedb.org/openapi/6453cc549c91cf004cd2a015
**Name**: The Movie DB
**Category**: media
**Logo**: https://www.themoviedb.org/assets/2/v4/logos/v2/blue_square_2-d537fb228cf3ded904ef09b136fe3fec72548ebc1fea3fbbd1ad9e36364db38b.svg

**Comment by MikeRalphson** [comment]
@calebhearth - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://developer.themoviedb.org/openapi/6453cc549c91cf004cd2a015

https://developer.themoviedb.org/openapi/6453cc549c91cf004cd2a015 FRUV
expected '' to start with '/'
#/paths/
 ✗ 
Provider: themoviedb.org Fixes: 0
Saving metadata...
Exiting with 1
