### ISSUE TITLE
Add "Netlify API" API

### ISSUE THREAD

**Issue by vidakovic** [APIs-guru/openapi-directory#115]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/netlify/open-api/master/swagger.yml
**Name**: Netlify API

**Comment by IvanGoncharov** [comment]
@vidakovic Thank you for submission. Added to the collection but need to find URL to official logo.
On their site, they embedded SVG inside CSS so it impossible to reference.
Maybe you know such URL?

**Comment by vidakovic** [comment]
Here is their page for the press:

https://www.netlify.com/press/

... e. g.:

https://d33wubrfki0l68.cloudfront.net/abb01c156da40cd797da7a9114a07d8b39b6e408/56471/img/press/logos/logomark.svg

**Comment by IvanGoncharov** [comment]
@vidakovic Thanks 👍
