### ISSUE TITLE
Add "Adobe PDF Services API" API

### ISSUE THREAD

**Issue by nirmalmerchant** [APIs-guru/openapi-directory#1150]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/shinesolutions/swagger-aem/master/conf/api.yml
**Name**: Adobe PDF Services API
**Category**: developer_tools
**Logo**:

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
