### ISSUE TITLE
Add "Moon API" API

### ISSUE THREAD

**Issue by HairyDuck** [APIs-guru/openapi-directory#1151]
**Format**: Postman Collection
**Official**: YES
**Url**: https://moon-api.com/postman.json
**Name**: Moon API
**Category**: education
**Logo**: https://moon-api.com/assets/img/illustrations/moon%20icon%20vector.svg

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
