### ISSUE TITLE
Add "Wyjyt - Geo Calculate" API

### ISSUE THREAD

**Issue by westonsoftware** [APIs-guru/openapi-directory#1157]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://wyjyt-geo-calculate.azurewebsites.net/api/swagger.json
**Name**: Wyjyt - Geo Calculate
**Category**: location
**Logo**: https://wyjyt.com/wp-content/uploads/2023/05/widget-300x300.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
