### ISSUE TITLE
Add "NSFW Image Detector" API

### ISSUE THREAD

**Issue by privacy-ai** [APIs-guru/openapi-directory#1158]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/privacy-ai/unsafe-or-fake-image-classifier/main/privacy-ai-SkymelNSFWImageClassifier-0.1-resolved.json
**Name**: NSFW Image Detector
**Category**: machine_learning
**Logo**: https://skymel.com/images/skymel.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
