### ISSUE TITLE
Add "Carbone" API

### ISSUE THREAD

**Issue by guillaume-carbone** [APIs-guru/openapi-directory#1159]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://carbone.io/examples/carboneRenderAPI.OpenAPI.yml
**Name**: Carbone
**Category**: developer_tools
**Logo**: https://carbone-resources.s3.eu-west-3.amazonaws.com/20210630+-+logo_V2.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
