### ISSUE TITLE
Add "Mux" API

### ISSUE THREAD

**Issue by burururu** [APIs-guru/openapi-directory#1160]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://docs.mux.com/api-spec.json
**Name**: Mux
**Category**: media
**Logo**: chrome://favicon/https://mux.com

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
