### ISSUE TITLE
Add "Horse Racing Data API" API

### ISSUE THREAD

**Issue by theracingapi** [APIs-guru/openapi-directory#1161]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.theracingapi.com/openapi.json
**Name**: Horse Racing Data API
**Category**: analytics
**Logo**: https://www.theracingapi.com/static/images/logo.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
