### ISSUE TITLE
Add "RentCast - Real Estate and Property Data" API

### ISSUE THREAD

**Issue by AntonAI** [APIs-guru/openapi-directory#1162]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://developers.rentcast.io/openapi/62980a560589b4001356b8a1
**Name**: RentCast - Real Estate and Property Data API
**Category**: financial
**Logo**: https://uploads-ssl.webflow.com/5fcfc6872ea226dee1432ecd/617c460a237cd21ffdb2b9f8_logo-icon.svg

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
