### ISSUE TITLE
Add "BKK Futár" API

### ISSUE THREAD

**Issue by Krisztiaan** [APIs-guru/openapi-directory#1164]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://opendata.bkk.hu/docs/futar-openapi.yaml
**Name**: BKK Futár
**Category**: transport
**Logo**: https://bkk.hu/static/cache/web/bkk/img/logo.svg

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
