### ISSUE TITLE
Add "ExoAPI" API

### ISSUE THREAD

**Issue by flmg** [APIs-guru/openapi-directory#1167]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.exoapi.dev/openapi.json
**Name**: ExoAPI
**Category**: developer_tools
**Logo**: https://exoapi.dev/assets/exoapi-logo-square.svg

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
