### ISSUE TITLE
Add "Zip Code API" API

### ISSUE THREAD

**Issue by ricardo-rangel-velasquez** [APIs-guru/openapi-directory#1168]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/Metadapi/zip-code-api/main/api-specification/Zipcode.json
**Name**: Zip Code API
**Category**: location
**Logo**: https://www.metadapi.com/Portals/0/metadapi_dnn_logo.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
