### ISSUE TITLE
Add "Breadcrumbs One API" API

### ISSUE THREAD

**Issue by kjsninja** [APIs-guru/openapi-directory#1170]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.breadcrumbs.one/swagger/v1/swagger.json
**Name**: Breadcrumbs One API
**Category**: financial
**Logo**: https://twitter.com/AppBreadcrumbs/photo

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
