### ISSUE TITLE
Add "ExhibitDay API" API

### ISSUE THREAD

**Issue by AEDay** [APIs-guru/openapi-directory#1171]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.exhibitday.com/swagger/docs/v1
**Name**: ExhibitDay API
**Category**: project_management
**Logo**: https://api.exhibitday.com/exhibitday-logo-small.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
