### ISSUE TITLE
Add "Maintenanceman.nl asset management API" API

### ISSUE THREAD

**Issue by uncle-b** [APIs-guru/openapi-directory#1173]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://maintenanceman.nl/api/v1/documentation/openapi.yaml
**Name**: Maintenanceman.nl asset management API
**Category**: time_management
**Logo**: https://maintenanceman.nl/site/wp-content/uploads/2023/08/cropped-Maintenanceman-logo.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
