### ISSUE TITLE
Add "Visma.net ERP V3" API

### ISSUE THREAD

**Issue by martinberglund** [APIs-guru/openapi-directory#1175]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://salesorder.visma.net/swagger/v3/swagger.json
**Name**: Visma.net ERP V3
**Category**: enterprise
**Logo**:

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
