### ISSUE TITLE
Add "Visma E-conomic ERP" API

### ISSUE THREAD

**Issue by martinberglund** [APIs-guru/openapi-directory#1176]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://apis.e-conomic.com/openapi/e-conomic.openapi.json
**Name**: Visma E-conomic ERP
**Category**: ecommerce
**Logo**:

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
