### ISSUE TITLE
Add "Visma Severa" API

### ISSUE THREAD

**Issue by martinberglund** [APIs-guru/openapi-directory#1178]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.severa.visma.com/psapublicrest/openapidocs/v1.0/doc.json
**Name**: Visma Severa
**Category**: project_management
**Logo**:

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
