### ISSUE TITLE
Add "Visma.net ERP V1" API

### ISSUE THREAD

**Issue by martinberglund** [APIs-guru/openapi-directory#1179]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://integration.visma.net/API-index/doc/swagger
**Name**: Visma.net ERP V1
**Category**: enterprise
**Logo**:

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
