### ISSUE TITLE
Add "Currencytick" API

### ISSUE THREAD

**Issue by amrsobhy** [APIs-guru/openapi-directory#1183]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://dashboard.currencytick.com/docs/openapi.yaml
**Name**: Currencytick
**Category**: financial
**Logo**: https://dashboard.currencytick.com/svg/logo.svg

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
