### ISSUE TITLE
Add "EAN-Search.org API" API

### ISSUE THREAD

**Issue by eansearch** [APIs-guru/openapi-directory#1184]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://www.ean-search.org/eansearch-swagger2.json
**Name**: EAN-Search.org API
**Category**: ecommerce
**Logo**: https://www.ean-search.org/ean-logo.svg

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
