### ISSUE TITLE
Add "PlaceKit" API

### ISSUE THREAD

**Issue by raphi** [APIs-guru/openapi-directory#1185]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/placekit/api-reference/main/openapi.yml
**Name**: PlaceKit
**Category**: location
**Logo**: https://placekit.io/icon.svg

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
