### ISSUE TITLE
Add "Telstra Messaging API v3" API

### ISSUE THREAD

**Issue by MarioHmura** [APIs-guru/openapi-directory#1186]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://dev.telstra.com/sites/default/files/Messaging-API-Proxy-OAS3.json
**Name**: Telstra Messaging API v3
**Category**: messaging
**Logo**:

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
