### ISSUE TITLE
Add "Midjourney API by useapi.net" API

### ISSUE THREAD

**Issue by useapi** [APIs-guru/openapi-directory#1187]
**Format**: OpenAPI 3.0
**Official**: NO
**Url**: https://useapi.net/docs/api-v1/openapi.yml
**Name**: Midjourney API by useapi.net
**Category**: media
**Logo**: https://useapi.net/assets/images/logo.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
