### ISSUE TITLE
Add "SAPI" API

### ISSUE THREAD

**Issue by AlexBroadbent** [APIs-guru/openapi-directory#1188]
**Format**: OpenAPI 3.1
**Official**: YES
**Url**: https://docs.sapi.com/openapi.json
**Name**: SAPI
**Category**: financial
**Logo**: https://docs.sapi.com/logo.png

**Comment by MikeRalphson** [comment]
@AlexBroadbent - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://docs.sapi.com/openapi.json

https://docs.sapi.com/openapi.json FRUV
expected Object {} to have property 'affordability:create'
#/paths/~1affordability/post/security
 ✗ 
Provider: sapi-sandbox.com Fixes: 1
Saving metadata...
Exiting with 1
