### ISSUE TITLE
Add "Travelpayouts Data API" API

### ISSUE THREAD

**Issue by EngExp** [APIs-guru/openapi-directory#119]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://apimatic.io/apientity/export/YXBpbWF0aWNfNTdlMzdlNDY0MjkyYTcwYzNjZDE1MDVm?format=Swagger20
**Name**: Travelpayouts Data API

**Comment by EngExp** [comment]
Sorry, it's API can edit only owner. My mistake

**Comment by IvanGoncharov** [comment]
@EngExp Thank you for submission.

> Sorry, this API can edit only owner. My mistake

No problem. If you have a copy of this spec somewhere you can reopen this issue.

For example, you can host in GitHub repo, we even develop special tool to help you start:
https://github.com/Rebilly/generator-openapi-repo
