### ISSUE TITLE
Add Quickbook from official postman button 

### ISSUE THREAD

**Issue by sanchojaf** [APIs-guru/openapi-directory#120]
Is not possible add a Postman collection spec in 

https://apis.guru/add-api/

But maybe is a good source in case.

For example I found a Postman Button for Quickbook Online in the official documentation

https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0012_postman?isExpand=false#/1500

here is the postman spec in json generated with the button

https://gist.github.com/sanchojaf/a046e5dbf4a81bc5555e797c483d9667

here are other button listed in the postman website

https://www.getpostman.com/integrations/run-button

**Comment by IvanGoncharov** [comment]
@sanchojaf Postman format missing the description of responses. I don't want to lower quality of specs in this collection beyond a certain limit. We don't have resources to add missing parts in Swagger files so I don't see how we can support Swagger files converted from Postman.
