### ISSUE TITLE
Add "Shipstation" API

### ISSUE THREAD

**Issue by sanchojaf** [APIs-guru/openapi-directory#121]
**Format**: API Blueprint
**Official**: YES
**Url**: http://docs.shipstation.apiary.io/api-description-document
**Name**: Shipstation
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/879470232292663296/Kp70vg1p_400x400.jpg
**Category**: ecommerce

**Comment by MikeRalphson** [comment]
Nearly a year, but we got there in the end! It's not a perfect conversion, but it passes the current validators.
