### ISSUE TITLE
Add "VTex" API

### ISSUE THREAD

**Issue by sanchojaf** [APIs-guru/openapi-directory#122]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://github.com/vtex/openapi-schemas
**Name**: VTex

**Comment by IvanGoncharov** [comment]
@sanchojaf Problem is this API documented in Spanish, am I correct?
Before adding it I need to think of so mechanism to support API documented not in English.
Will think about it this week.

**Comment by sanchojaf** [comment]
Hi @IvanGoncharov is Portuguese

**Comment by MikeRalphson** [comment]
@IvanGoncharov could you give me your thoughts on the issues with non-English-language API definitions? What might need changing/translating?

**Comment by IvanGoncharov** [comment]
>  What might need changing/translating?

@MikeRalphson At the minimum non-English specs should be marked with the language used ( for e.g. x-description-language ), so you would be able to filter spec based on language. You can use 
this spec: https://en.wikipedia.org/wiki/ISO_639-1

**Comment by MikeRalphson** [comment]
@sanchojaf Vtex seem to have moved over to using [Postman collections](https://help.vtex.com/developer-docs/) to document their APIs. Can you confirm?

If so it would be dependent on [this issue](https://github.com/lucybot/api-spec-converter/issues/79)

**Comment by MikeRalphson** [comment]
VTEX seem to have moved (back) to OpenAPI 3.0 - https://github.com/vtex/openapi-schemas

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
