### ISSUE TITLE
Add "CenitIO" API

### ISSUE THREAD

**Issue by maryguirola** [APIs-guru/openapi-directory#125]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://cenit.io/openapi/v1/swagger.yaml
**Name**: Cenit IO

**Comment by sanchojaf** [comment]
Hi @maryguirola 

Thanks for add the API!

The Name should be: Cenit IO

**Comment by maryguirola** [comment]
Thanks @sanchojaf I I corrected it.

**Comment by IvanGoncharov** [comment]
@maryguirola @sanchojaf Thank you for contribution.
Your API is added 🎆
