### ISSUE TITLE
Add "Purchasetesting" API

### ISSUE THREAD

**Issue by Malakatta** [APIs-guru/openapi-directory#126]
**Format**: Swagger 1.x
**Official**: NO
**Url**: https://purchasestesting.talenom.fi/swagger/ui/index
**Name**: Purchasetesting

**Comment by IvanGoncharov** [comment]
@Malakatta Thank you for your submission.
If you have a spec for API that conforms [these criteria](https://github.com/APIs-guru/openapi-directory#api-spec-acceptance-criteria) I will happily add it to the collection.
Can I help you somehow?
