### ISSUE TITLE
Add "Rotten Tomatoes" API

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/openapi-directory#127]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: NO
**Url**: https://raw.githubusercontent.com/Mermade/openapi_specifications/master/mashery/api.rottentomatoes.com/Rotten-Tomatoes/1.0/swagger.json
**Name**: Rotten Tomatoes

**Comment by IvanGoncharov** [comment]
@MikeRalphson Added, sorry for delay
