### ISSUE TITLE
Azure (ARM) DevTest labs Validation issue

### ISSUE THREAD

**Issue by maxmckenzie** [APIs-guru/openapi-directory#130]
Whilst validating the below raw reference for azure devtest labs an error is returned due to the reference containing "circular references"

https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/azure.com/arm-devtestlabs/2016-05-15/swagger.yaml

This API is valid, but it cannot be shown because it contains circular references.

**Comment by maxmckenzie** [comment]
This occurs on this Azure reference as well 

https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/azure.com/arm-dns/2016-04-01/swagger.yaml

**Comment by maxmckenzie** [comment]
This seems to affect quite a few of the Azure API references. I've detailed the ones also effected below.

https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/azure.com/arm-devtestlabs/2016-05-15/swagger.yaml

https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/azure.com/arm-insights/2016-03-01/swagger.yaml

**Comment by IvanGoncharov** [comment]
@maxmckenzie Circular references are valid in JSON Schema and Swagger as well :(
They are not many API that needs them in their OpenAPI specification but they are still valid.
And I can't remove circular reference.
Just as an example why they are needed:
```yaml
definitions:
  Directory:
     properties:
        subdirectories:
            type: object
            additionalProperties:
                $ref: '#/definitions/Directory'
        files:
            type: object
            additionalProperties:
               $ref: '#/definitions/File'
  File:
    properties:
       data:
          type: string
```

In above example `Directory` contain a reference to itself and you can't rewrite this schema differently. 

So "recursive references" are necessary evil which allows us to describe recursive data structures.

**Comment by IvanGoncharov** [comment]
@maxmckenzie Can you please describe what is your use case?
I can try to help you 😄

**Comment by IvanGoncharov** [comment]
@maxmckenzie ping

**Comment by IvanGoncharov** [comment]
@maxmckenzie If you still experience this problem and I can help somehow feel free to reopen this issue.

**Comment by maxmckenzie** [comment]
Sorry man Github gave me exactly 0 notifications about this ticket and the other one i raised. I'm specifically trying to get it to pass http://bigstickcarpet.com/swagger-parser/

before adding it to Hitchhq.com

**Comment by IvanGoncharov** [comment]
@maxmckenzie `swagger-parser` can handle circular references, more details is [here](https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/README.md#circular-refs).

> before adding it to Hitchhq.com

Interesting. Do Hitch plans to integrate with our catalog?
I'm very interested in that, can I help somehow?
