### ISSUE TITLE
Add "Oxford Dictionaries API" API

### ISSUE THREAD

**Issue by vidakovic** [APIs-guru/openapi-directory#131]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developer.oxforddictionaries.com/swagger/spec/public_doc_guest.json
**Name**: Oxford Dictionaries API

**Comment by IvanGoncharov** [comment]
@vidakovic Cool API 👍  Thank you.

**Comment by IvanGoncharov** [comment]
@vidakovic BTW. I added this spec as commit #1001 😄
