### ISSUE TITLE
Add "NY Times Video Transcoding API" API

### ISSUE THREAD

**Issue by vidakovic** [APIs-guru/openapi-directory#133]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/NYTimes/video-transcoding-api/master/swagger.json
**Name**: NY Times Video Transcoding API

**Comment by IvanGoncharov** [comment]
@vidakovic Thanks for PR 👍 
But it's API that you should host yourself. Currently, we only support publicly hosted APIs 😞
