### ISSUE TITLE
Twilio missing formData parameters

### ISSUE THREAD

**Issue by bobby-brennan** [APIs-guru/openapi-directory#136]
E.g. POST /Accounts/{AccountSid}/Messages{mediaTypeExtension}, which sends a new SMS, is missing the to/from/body fields, which are pretty necessary

https://www.twilio.com/docs/api/rest/sending-messages

**Comment by IvanGoncharov** [comment]
@bobby-brennan Twillio spec is now hosted in [separate repo](https://github.com/APIs-guru/unofficial_openapi_specs/blob/master/twilio.com/2010-04-01/swagger.yaml) and you can help a lot by submitting PR.

**Comment by IvanGoncharov** [comment]
Merged in appropriate repo
