### ISSUE TITLE
GitHub API missing page parameter

### ISSUE THREAD

**Issue by bobby-brennan** [APIs-guru/openapi-directory#138]
Every "list" operation should have a page parameter

**Comment by IvanGoncharov** [comment]
@bobby-brennan GitHub API is hosted here:
https://github.com/APIs-guru/unofficial_openapi_specs/tree/master/github.com/v3
You can help by creating PR

**Comment by MikeRalphson** [comment]
Moved to https://github.com/APIs-guru/unofficial_openapi_specs/issues/12
