### ISSUE TITLE
Bad securityDefinitions for Trello

### ISSUE THREAD

**Issue by bobby-brennan** [APIs-guru/openapi-directory#139]
Would suggest moving the Trello spec to unofficial-api-specs as the original doesn't seem to be maintained.  If you do I'll submit a PR there.

* OAuth2 definition should be removed as Trello only supports OAuth1
* api_key name should be `key`
* should also have `api_token` as both `key` and `token` are needed

Correct secDefs:
```json
{
  "securityDefinitions": {
    "api_key": {
      "in": "header",
      "name": "key",
      "type": "apiKey"
    },
    "api_token": {
      "type": "apiKey",
      "in": "query",
      "name": "token"
    }
  }
}
```

**Comment by IvanGoncharov** [comment]
@bobby-brennan Trello here now hosted here:
https://github.com/APIs-guru/unofficial_openapi_specs/blob/master/trello.com/1.0/swagger.yaml
You can help by submitting PR

**Comment by MikeRalphson** [comment]
Moved to https://github.com/APIs-guru/unofficial_openapi_specs/issues/11
