### ISSUE TITLE
Add "Accurate Background Check API" API

### ISSUE THREAD

**Issue by kthartley** [APIs-guru/openapi-directory#143]
**Format**: Swagger 1.x
**Official**: YES
**Url**: https://developer.accuratebackground.com/#/apidoc
**Name**: Accurate Background Check API

**Comment by IvanGoncharov** [comment]
@kthartley Thank you for submission.
But you provide the link to Slate-powered documentation and it missing API specification of any type.
Here is a good article which explains the difference between those two:
http://nordicapis.com/difference-api-documentation-specification-definition/

I can't add API without API specification so I will close this issue.
But feel free to reopen it when you will have link to API specification.
