### ISSUE TITLE
Add "Shop API Showcase" API

### ISSUE THREAD

**Issue by helpermethod** [APIs-guru/openapi-directory#144]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.predic8.de/shop/swagger
**Name**: Shop API Showcase

**Comment by IvanGoncharov** [comment]
@helpermethod Thank you for contribution.
But it's example API and we collect only public APIs of real sites/platforms.

**Comment by helpermethod** [comment]
Ah sorry, somehow skipped that part. Thank you for your time, you're doing a great job!
