### ISSUE TITLE
Add "Traccar" API

### ISSUE THREAD

**Issue by tananaev** [APIs-guru/openapi-directory#145]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/tananaev/traccar/master/swagger.json
**Name**: Traccar

**Comment by IvanGoncharov** [comment]
@tananaev Thank you for submission.
Your API was added long time ago as 80ccb3817d62d31d98b297cf6f6c36f9ad23daf0 but I forget to close issue.
