### ISSUE TITLE
Add "uebermaps" API

### ISSUE THREAD

**Issue by ttoni** [APIs-guru/openapi-directory#147]
**Format**: Swagger 2.0
**Official**: YES
**Url**: https://uebermaps.com/api/v2/apidocs
**Name**: uebermaps

**Comment by IvanGoncharov** [comment]
@ttoni Thank you for submission.
You Swagger file have one problem it incorrectly uses `in` instead of `enum` in mulitple places.
For example:
```json
{
  "definitions": {
    "Map": {
      "properties": {
        "visibility": {
          "type": "string",
          "in": [
             "public",
             "link",
             "private"
          ]
        },
```

**Comment by ttoni** [comment]
@IvanGoncharov thanks for pointing out. Fixed in next API release this week.

**Comment by IvanGoncharov** [comment]
@ttoni Great 👍 
Just ping me when fixed.

**Comment by ttoni** [comment]
@IvanGoncharov Updated the API, please check again.

**Comment by IvanGoncharov** [comment]
@ttoni Thank you.
You fixed the issue I reported previously.
But I see the new one, you stripping leading slash from endpoint paths + you have couple unresolved refs.
You can use this tool to debug issues: http://editor.swagger.io/#/?import=https://uebermaps.com/api/v2/apidocs

**Comment by ttoni** [comment]
Ok it now passes the validation.

**Comment by IvanGoncharov** [comment]
@ttoni Thank you.
Your API added to collection 🎉
