### ISSUE TITLE
Add "IATACodes" API

### ISSUE THREAD

**Issue by iatacodes** [APIs-guru/openapi-directory#148]
**Format**: HTTP API
**Official**: NO
**Url**: http://iatacodes.org/
**Name**: IATACodes

**Comment by IvanGoncharov** [comment]
@iatacodes Thank you for submission.
However, I can't find any machine-readable API spec for your API.
Here is a good article which explains the difference between those two:
http://nordicapis.com/difference-api-documentation-specification-definition/

I can't add API without API specification so I will close this issue.
But feel free to reopen it when you will have a link to API specification.
