### ISSUE TITLE
Add "AppVeyor" API

### ISSUE THREAD

**Issue by kevinoid** [APIs-guru/openapi-directory#149]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: NO
**Url**: https://raw.githubusercontent.com/kevinoid/appveyor-swagger/master/swagger.yaml
**Name**: AppVeyor

This is an OpenAPI/Swagger 2.0 specification for the [AppVeyor REST API](https://www.appveyor.com/docs/api/).  The specification is unofficial.  I am not affiliated with AppVeyor in any way.  However, I did get permission from the AppVeyor team via email to publish the spec.

I hope you find it useful,
Kevin

**Comment by IvanGoncharov** [comment]
@kevinoid Thank you for the contribution I added it to the collection.
You wrote excellent spec it not only passed all validation but specify all possible properties like: `externalDocs`, 'termOfService`, etc. :+1:

P.S. I like how you setup repository to host Swagger spec. 
Maybe you find useful our other project: https://github.com/Rebilly/generator-openapi-repo

**Comment by kevinoid** [comment]
@IvanGoncharov Thanks for reviewing and including it!  It was my first OpenAPI/Swagger spec, so I'm very glad to hear that it passed validation and that I didn't miss anything crucial.

The generator-openapi-repo Yeoman generator looks great!  That will definitely save a lot of time setting up any future specs.  I'll have to see if I can include any of the generated features that I might be missing in this project.  Thanks!
