### ISSUE TITLE
Add "Amadeus Travel Innovation Sandbox" API

### ISSUE THREAD

**Issue by maryguirola** [APIs-guru/openapi-directory#151]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://github.com/amadeus-travel-innovation-sandbox/sandbox-content/blob/master/swagger.yml
**Name**: Amadeus Travel Innovation Sandbox

**Comment by IvanGoncharov** [comment]
@maryguirola Added 👍
