### ISSUE TITLE
Add "Browshot: Take screenshots of any website in real time" API

### ISSUE THREAD

**Issue by juliensobrier** [APIs-guru/openapi-directory#152]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/juliensobrier/browshot-api-spec/master/browshot.yaml
**Name**: Browshot: Take screenshots of any website in real time

**Comment by IvanGoncharov** [comment]
@juliensobrier Thank you for submission 👍 
I added your API to our collection and it appeared to be \#300 in our collection 🎉 

BTW, we have another project: [ReDoc](https://github.com/Rebilly/ReDoc) - Swagger powered documentation engine
Here is how your API looks https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/juliensobrier/browshot-api-spec/master/browshot.yaml

And here is a tool which helps you to host your Swagger spec on GitHub:
https://github.com/Rebilly/generator-openapi-repo
