### ISSUE TITLE
Add "IJENKO IoE² API for end-user applications" API

### ISSUE THREAD

**Issue by dolmen** [APIs-guru/openapi-directory#156]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://developers.ijenko.com/swagger.json
**Name**: IJENKO IoE² API for end-user applications

**Comment by dolmen** [comment]
A rendering of the API using swagger-ui is available here: http://developers.ijenko.com/api-reference/

**Comment by IvanGoncharov** [comment]
@dolmen Thank you for submission and great ideas for ReDoc 👍 
You API was added to the collection.

BTW. If you writing Swagger files by hand you can find this project useful:
https://github.com/Rebilly/generator-openapi-repo

**Comment by dolmen** [comment]
Note that we have 2 APIs: the one submitted is public. We have another one which is private.

Thanks for the link. My needs were far beyond generator-openapi-repo.

I'm writing our API specs by hand in YAML. They share 80% of the routes (the private API is mostly a superset of the public API). I've written my own swagger preprocessor in Perl to allow me to split the source in multiple files and to benefit from much more reusability than the bare Swagger: my processor handles two special keys: `$inline` and `$merge` in addition to `$ref`. This allow me to write the shared bits of both APIs in common files. My original sources are 3537 lines of YAML for the submitted API, while the JSON output after preprocessing is 5162 lines. Global responses and parameters are inlined because I had issues with some tools that did not properly handle them.

**Comment by IvanGoncharov** [comment]
@dolmen You right `generator-openapi-repo` is targeted for APIs which fully developed on GitHub. This is the use case of our customer Rebilly inc. which is the primary user of above tools.
