### ISSUE TITLE
GoDaddy developer APIs

### ISSUE THREAD

**Issue by darklynx** [APIs-guru/openapi-directory#158]
GoDaddy have their dev. APIs documented in Swagger too:

Swagger UI: https://developer.godaddy.com/doc
The list of all APIs: https://developer.godaddy.com/swagger/doc/resources
e.g. Domains API: ~~https://developer.godaddy.com/swagger/doc/resources/v1/domains~~
~~https://developer.godaddy.com/swagger/doc/resources?_=1511251764510~~
E.g.: https://developer.godaddy.com/swagger/swagger_abuse.json

**Comment by MikeRalphson** [comment]
Have created a spec source for GoDaddy APIs but they seem to be failing Swagger 1.2 validation.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
