### ISSUE TITLE
Add "Apacta" API

### ISSUE THREAD

**Issue by Spriz** [APIs-guru/openapi-directory#160]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://apidoc.apacta.com/swagger.yaml
**Name**: Apacta
**Logo**: 
![image](https://cloud.githubusercontent.com/assets/21603/24057934/2a6e03ac-0b41-11e7-80a6-54645751cfe2.png)

**Comment by MikeRalphson** [comment]
Definition is valid as of this date.

**Comment by MikeRalphson** [comment]
API added. Many thanks for the submission.
