### ISSUE TITLE
Add "VisageCloud" Face Recognition API

### ISSUE THREAD

**Issue by bocse** [APIs-guru/openapi-directory#162]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://visagecloud.com/v2/api-docs
**Name**: VisageCloud

**Comment by IvanGoncharov** [comment]
@bocse Added 🎉  Thank you for contribution.

**Comment by bocse** [comment]
Thank you as well.
Our logo is here:
https://visagecloud.com/visage-cloud-logo.png
Or in a larger format, here:
https://scontent-vie1-1.xx.fbcdn.net/v/t1.0-9/16299271_1353472861341063_3434560190164106638_n.png?oh=23666bff898876ebeadaf606dcc540ed&oe=5928E166

**Comment by IvanGoncharov** [comment]
@bocse Added. Thank you for URL 👍 
Will be deployed after CI finishes(~5min).
