### ISSUE TITLE
Add "Kinto" API

### ISSUE THREAD

**Issue by gabisurita** [APIs-guru/openapi-directory#166]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: `https://firefox.settings.services.mozilla.com/v1/__api__`
**Name**: Kinto
**Logo**: 
![image](https://cloud.githubusercontent.com/assets/21603/24036792/23286ed2-0af3-11e7-9353-7a772636dee1.png)

Ref: https://github.com/Kinto/kinto

**Comment by MikeRalphson** [comment]
@gabisurita thanks for your submission.

Is that the correct URL for the OpenAPI definition? For me it returns

```json
{"errno":111,"message":"The resource you are looking for could not be found.","code":404,"error":"Not Found"}
```

**Comment by gabisurita** [comment]
The link is right, but github is not linking the last two underline symbols (`__`). The right link is
`https://firefox.settings.services.mozilla.com/v1/__api__`

**Comment by gabisurita** [comment]
Also, the production version is not valid, but this has been fixed on the staging server. We should have probably included `https://kinto.dev.mozaws.net/v1/__api__` instead of the provided link.

**Comment by MikeRalphson** [comment]
Excellent thank you. Do you have an ETA for when the fixed definition will be deployed to the production server?

**Comment by gabisurita** [comment]
> Do you have an ETA for when the fixed definition will be deployed to the production server?

Not really. It should take some time. Is there a problem in using the staging server instead? It's usually hosts the last released version.

**Comment by MikeRalphson** [comment]
>  Is there a problem in using the staging server instead? It's usually hosts the last released version.

It is a question of whether the two definitions point to the same API endpoint, and whether the copy of the definition on the staging server will always accurately describe that API endpoint.

There is also the question of us remembering to update our source from staging to production when the valid definition gets deployed...

**Comment by MikeRalphson** [comment]
Kinto API added to collection, many thanks again for the submission.
