### ISSUE TITLE
Add "Telegram Bot API" API

### ISSUE THREAD

**Issue by olebedev** [APIs-guru/openapi-directory#167]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: NO
**Url**: https://raw.githubusercontent.com/olebedev/go-tgbot/master/swagger.yaml
**Name**: Telegram Bot API

**Comment by IvanGoncharov** [comment]
@olebedev Thank you submission and for all effort, you put into this spec.
But errors in your spec prevent me from adding it.
You can review errors in http://editor.swagger.io/ tool, just open File -> Import URL and paste URL to your spec.
Please ping me when you fix all of them.

**Comment by MikeRalphson** [comment]
Hasn't been updated in last 3 years and Telegram bot API has moved on. Still no official OpenAPI though.

**Comment by MikeRalphson** [comment]
A telegram bot API definition for v5 of their API has been added.
