### ISSUE TITLE
Add "Authentiq ID" API

### ISSUE THREAD

**Issue by sanchojaf** [APIs-guru/openapi-directory#169]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url Authentiq ID API Provider**: https://github.com/AuthentiqID/authentiq-docs/blob/master/docs/swagger/provider.yaml
**URL Authentiq ID API Issuer**: https://github.com/AuthentiqID/authentiq-docs/blob/master/docs/swagger/issuer.yaml
**Name**: Authentiq ID
**Service home page**: https://www.authentiq.com/
**API doc page**: http://developers.authentiq.io/api-provider/

Notice that are two API's:
- Authentiq ID API Provider
-  Authentiq ID API Issuer

**Comment by IvanGoncharov** [comment]
Added
