### ISSUE TITLE
Undefined behaviour in Rebilly API spec

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/openapi-directory#171]
From testing my v2 to v3 converter, which I want to be lossless, I get

>#/paths/~13dsecure/post/responses/422
Reference object cannot be extended

Where the response is defined as a `$ref` with a `description` property.

Maybe this can be fixed upstream? It's the only example I've found so far in the wild.

**Comment by IvanGoncharov** [comment]
@MikeRalphson Thanks, I will report this to the Rebilly API team.

**Comment by MikeRalphson** [comment]
Sorry @IvanGoncharov when I said it was the only example I meant the Rebilly definition, not that there was only one issue **in** the definition.

Each pair here is a $ref to a location in the definition which has a $ref and a description. The second line is the $ref target.

````
#/paths/~1api-keys~1{id}/delete/responses/409
  #/components/responses/Conflict
#/paths/~1api-keys~1{id}/put/responses/422
  #/components/responses/InvalidDataError
#/paths/~1custom-events~1{id}/delete/responses/409
  #/components/responses/Conflict
#/paths/~1custom-events~1{id}/put/responses/409
  #/components/responses/Conflict
#/paths/~1users~1{id}/delete/responses/409
  #/components/responses/Conflict
#/paths/~1users~1{id}/put/responses/422
  #/components/responses/InvalidDataError
#/paths/~1users~1{id}~1password/post/responses/422
  #/components/responses/InvalidDataError
````

**Comment by MikeRalphson** [comment]
Closing as a very widespread problem and probably won't be fixed until JSON schema supports `$merge` or `$use`.
