### ISSUE TITLE
Add "Ritc" API

### ISSUE THREAD

**Issue by colingoldberg** [APIs-guru/openapi-directory#172]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://www.ritc.io/openapi/ritc.swagger.json
**Name**: Ritc
**Logo**: ![Logo](https://pbs.twimg.com/profile_images/664480221534552064/CwdeYGxs_400x400.jpg)

**Comment by IvanGoncharov** [comment]
@colingoldberg Thank you submission.
But errors in your spec prevent me from adding it.
You can review errors in http://editor.swagger.io/ tool, just open File -> Import URL and paste URL to your spec.
Please ping me when you fix all of them.

**Comment by colingoldberg** [comment]
I have replaced the file with one downloaded from my apimatic account. There are some warnings, but no errors.
http://www.ritc.io/openapi/ritc.swagger.json

**Comment by MikeRalphson** [comment]
Added. Many thanks for your submission.
