### ISSUE TITLE
Add "Amadeus Travel Innovation Sandbox" API

### ISSUE THREAD

**Issue by tadhgpearson** [APIs-guru/openapi-directory#174]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/amadeus-travel-innovation-sandbox/sandbox-content/master/swagger.yml
**Name**: Amadeus Travel Innovation Sandbox

**Comment by IvanGoncharov** [comment]
Thank you for contribution.
However this API already added, see here: https://github.com/APIs-guru/openapi-directory/tree/master/APIs/amadeus.com

**Comment by tadhgpearson** [comment]
It looks like I can just add a description, the image and provider from your patch file to my swagger spec and your site will be updated, correct?

**Comment by IvanGoncharov** [comment]
@tadhgpearson I need to run some scripts on my side, I will do this tomorrow.
I run update script 1-2 times per week and update specs based on the value of `x-origin` field:
https://github.com/APIs-guru/openapi-directory/blob/master/APIs/amadeus.com/1.2/swagger.yaml#L19

**Comment by IvanGoncharov** [comment]
BTW. Your API were submitted here: https://github.com/APIs-guru/openapi-directory/issues/151

**Comment by IvanGoncharov** [comment]
> provider

@tadhgpearson `x-provider` automatically generated based on your domain name and used as ID. Please don't put it in you swagger file. As for other fields, you mentioned it totally safe to add them in your swagger file.
