### ISSUE TITLE
Add "Zappiti Player HTTP Service" API

### ISSUE THREAD

**Issue by Filimindji** [APIs-guru/openapi-directory#179]
**Format**: Swagger 2.0
**Official**: YES
**Url**: http://zappiti.com/api/zappiti-player-4k/swagger/swagger.yaml
**Name**: Zappiti Player HTTP Service
**Categories**: entertainment
**Logo**: 
![image](https://cloud.githubusercontent.com/assets/21603/24292732/7e3a8038-1086-11e7-90c0-434e4dcc3474.png)

**Comment by MikeRalphson** [comment]
API uses a hard-coded 192.168.x.x IP address as the host.

Going forward we want to be able to support APIs with fluid hosts or that (like this one) connect to the internal network (IoT). Just need to spend some time thinking about the best way to achieve it.

Thanks for your submission.

**Comment by Filimindji** [comment]
Yes, that's was issue too with swagger because it is not possible to dynamically specify a custom host so, my users have to edit the yaml first in order to test the queries. Not really convenient.

It's great to know that you are concern about this issue, even if it mean that our API will not be available on your website until an acceptable solution is found.

Keep it up guys !

**Comment by MikeRalphson** [comment]
My current thinking is to back-port the `servers` object from [OpenAPI 3.0.0-RC0](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#server-object) as a Swagger 2.0 vendor extension, so it would look like this;

```yaml
# Zappiti Service API
swagger: '2.0'
info:
  title: Zappiti Player API
  description: Move your app forward with the Zappiti Player API. Use http://your-player-ip:8990/ as base URL for your requests.
  version: "4.14.170"
# the domain of the service
#host: your-player-ip:8990
host: 192.168.1.5:8990
# array of all schemes that your API supports
schemes:
  - http
x-servers:
  - url: http://{ip-address}:{port}/
    variables:
      ip-address:
        default: '192.168.1.5'
     port:
       default: '8990'
```

The only problem is that there will be no tooling support for it (except [Rebilly Redoc](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-servers)) unless we publicise this 'Swagger 2.0++' solution widely. It does also depend on how long it takes OpenAPI 3.0.x to take off.

It does act as a hint that the API supports variable hosts, and of course would be present for any Swagger 2.0 to OpenAPI 3.0.x [converters](https://github.com/mermade/swagger2openapi) to take into account.

We can do it as a patch within this repo if you think it might be confusing to have it in your definition.

cc: @IvanGoncharov, @bobby-brennan and @KinLane for their thoughts.

**Comment by Filimindji** [comment]
OK, I understand, what about this :

https://docs.apimatic.io/advanced/swagger-server-configuration-extensions/

```yaml
swagger: '2.0'
info:
  title: Zappiti Player API
  description: >-
    Move your app forward with the Zappiti Player API. Use
    http://your-player-ip:8990/ as base URL for your requests.
  version: 4.14.170
  x-server-configuration:
    default-environment: player
    default-server: default
    environments:
      - name: player
        servers:
          - name: default
            url: 'http://{host}:8999/'
    parameters:
      - name: host
        description: Your player IP
        type: string
```

**Comment by MikeRalphson** [comment]
@Filimindji Thanks for the link, I hadn't seen the APIMatic extension documentation before.

It looks like another way of specifiying the same information, and though it's not (to my mind) as neat as the OpenAPI 3.x way of doing things, it may have the advantage of real-world tooling existing today. 

If you're thinking of offering an APIMatic-generated SDK for your API, then I think we would be fine with supporting this vendor extension.

Again, thanks for bringing it to my attention, I'm off to add it to the wiki!

**Comment by Filimindji** [comment]
No, I just found APIMatic few hours ago.

So, It's ok for my to use OpenAPI 3.x way it if it's better for you.

And I just updated http://zappiti.com/api/zappiti-player-4k/swagger/swagger.yaml with the **x-servers** tag.

I'm hope it's done right.

**Comment by MikeRalphson** [comment]
@Filimindji yes, it looks right to me and gets merged with the server array using our 2.0 to 3.0.x converter.

There's nothing stopping you adding the APIMatic extension as well if someone needs it.

As your Swagger definition is hosted on your own network, we have a domain to use to identify the API, and to my mind, there is very little difference in an API which has an unresolvable host (if you don't have the necessary device) compared to an API which is unresponsive if you don't have the right authentication.

I'm about to add your API (congratulations on an error and warning-free definition!) but will leave this issue open for a while for comments.

**Comment by MikeRalphson** [comment]
@Filimindji the API definition appears to have been (re)moved, it just redirects to the index page. Is the definition still available at another location?

**Comment by Filimindji** [comment]
Hello MikeRalphson,

I'm sorry for the delay of response. I just noticed it.

I did rename the file with a version number to keep an history (bad idea).

The url http://zappiti.com/api/zappiti-player-4k/swagger/swagger.yaml is fixed now.

Thank you.

**Comment by MikeRalphson** [comment]
API updated, many thanks @Filimindji
