### ISSUE TITLE
Add "LetsValidate" API

### ISSUE THREAD

**Issue by hbakhtiyor** [APIs-guru/openapi-directory#186]
**Format**: MarkDown
**Official**: YES
**Url**: https://github.com/letsvalidate/api
**Name**: LetsValidate

**Comment by MikeRalphson** [comment]
@hbakhtiyor unfortunately we can't add APIs which are documented in free-form markdown, only a defined API description language such as OpenAPI / Swagger, API Blueprint, RAML etc.

It might be easiest to convert your documentation to API Blueprint, as that is just markdown with a set of rules to follow. Alternatively, it wouldn't take long to build an OpenAPI definition as the API is quite simple.

Please let me know if you need any further pointers.
