### ISSUE TITLE
GitHub; Header parameters misusage

### ISSUE THREAD

**Issue by Umkus** [APIs-guru/openapi-directory#187]
At least from what I could see in the GitHub API implemented in Swagger, the request parameter definitions are misused.

For instance consider this [example](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/github.com/v3/swagger.yaml#L80).
You defined `X-RateLimit-Remaining` header as a request (header) parameter. Although it should go into the respected response `headers` object.

**Comment by MikeRalphson** [comment]
Hi @Umkus - for the most part, we are not responsible for the **content** of the API definitions listed here.

95% are official definitions generated by the owners of the APIs, but the GitHub definition falls into the other 5% of unofficial definitions. It comes originally from [here](https://github.com/raml-apis/GitHub).

As you can see from [this issue](https://github.com/APIs-guru/openapi-directory/issues/68) we are looking for a maintainer for this definition.

@bobby-brennan has a more up-to-date GitHub v3 definition [here](https://raw.githubusercontent.com/bobby-brennan/scrape-to-swagger/master/output/github.swagger.json), but it still has [issues](https://github.com/APIs-guru/unofficial_openapi_specs/issues/12) and in fact seems to be missing the `X-RateLimit-Remaining` header completely.

Hopefully this should be a one-off situation, it won't affect **all** of the APIs in the collection.

**Comment by Umkus** [comment]
Thanks for the clarification :-)

**Comment by MikeRalphson** [comment]
Thanks for highlighting the issue.
