### ISSUE TITLE
Add "感情推定（極性判定）" API

### ISSUE THREAD

**Issue by keigohtr** [APIs-guru/openapi-directory#190]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.apitore.com/json/11
**Name**: 感情推定（極性判定）

**Comment by MikeRalphson** [comment]
Hi @keigohtr do you have a list of all your APIs in a machine-readable format, such as [apis.json](http://apisjson.org/), or an API for accessing the other APIs? This would make it simpler for us to add new API's from your store automatically.

What would also help is if the API's had a textual description instead of

````json
"description":"[Endpoint] https://api.apitore.com/api/11"}
````

This can be in any language, but is necessary for our API integrations to show a summary with each API.

I will add comments on each issue regarding the specific APIs.

**Comment by MikeRalphson** [comment]
I've tried validating a couple of your APIs, and I find issues as below:

````json
{
  "details": [
    {
      "code": "PATTERN",
      "params": [
        "^[^{}/ :\\\\]+(?::\\d+)?$",
        "api.apitore.com/api/11"
      ],
      "message": "String does not match pattern ^[^{}/ :\\\\]+(?::\\d+)?$: api.apitore.com/api/11",
      "path": [
        "host"
      ],
      "schemaId": "http://swagger.io/v2/schema.json#",
      "description": "The host (name or ip) of the API. Example: 'swagger.io'"
    },
    {
      "code": "OBJECT_MISSING_REQUIRED_PROPERTY",
      "params": [
        "version"
      ],
      "message": "Missing required property: version",
      "path": [
        "info"
      ],
      "schemaId": "http://swagger.io/v2/schema.json#",
      "description": "General information about the API."
    }
  ],
  "name": "SyntaxError",
  "message": "Swagger schema validation failed.
  String does not match pattern ^[^{}/ :\\\\]+(?::\\d+)?$: api.apitore.com/api/11 at #/host
  Missing required property: version at #/info

JSON_OBJECT_VALIDATION_FAILED"
}
````

So

```json
    "host": "api.apitore.com/api/11",
    "basePath": "/",
````

Should be split into

````json
    "host": "api.apitore.com",
    "basePath": "/api/11",
````

A version for each API should be added under the `info` object, and the `description` property should be a free-text summary of the API as mentioned above.

**Comment by keigohtr** [comment]
@MikeRalphson I see. I will comment here after I correct it. Thank you :)

**Comment by keigohtr** [comment]
@MikeRalphson I fixed it. Please check my APIs again. Thank you :)

**Comment by MikeRalphson** [comment]
Many thanks for the update - see comments on the other issue.

This question is also still outstanding

> do you have a list of all your APIs in a machine-readable format, such as apis.json, or an API for accessing the other APIs? This would make it simpler for us to add new API's from your store automatically.

**Comment by keigohtr** [comment]
@MikeRalphson Oops. I miss it.
I don have a list of all our APIs now. This is because our service is a WebAPI marketplace.  There are many kinds of categories. But I know your points. ...Any good idea?

**Comment by MikeRalphson** [comment]
@keigohtr One option is to generate an [apis.json](http://apisjson.org/) file from whatever database is driving your marketplace - this would only need to be updated when you add or remove an API.

Another option is to have an API which returns data on the other APIs (an API for apitore.com itself), like we do for APIS.guru [here](https://api.apis.guru/v2/list.json).

You could also embed schema.org [WebAPI discovery data](http://pending.schema.org/WebAPI) in your html (we would prefer data on all the APIs to be on one page to save having to navigate pagination links), where the `documentation` property would point to your OpenAPI / Swagger definition in each case.

**Comment by keigohtr** [comment]
@MikeRalphson OK. I will check a construction of our service. I will comment here after modification. :)

**Comment by keigohtr** [comment]
@MikeRalphson How about this style?
https://api.apitore.com/json/0
key is swagger spec, value is simple description.

**Comment by MikeRalphson** [comment]
@keigohtr Thanks, I've added all your APIs to the collection. Two small things, in descriptions you have several instances of "Varios" which should be "Various", and in your https://api.apitore.com/json/0 file, it might be useful for us to have a `version` property as well as the existing `title` and `description` properties.

**Comment by keigohtr** [comment]
@MikeRalphson Thanks for adding our APIs :)
OK, I will fix our typo and add version tag in this json. Please wait for my reply. Thanks.

**Comment by keigohtr** [comment]
@MikeRalphson Done :) Please check our latest file?
https://api.apitore.com/json/0

**Comment by MikeRalphson** [comment]
@keigohtr That's perfect, many thanks.

**Comment by keigohtr** [comment]
@MikeRalphson Me too. Thank you very much:)

**Comment by MikeRalphson** [comment]
Hi @keigohtr - today I'm getting a 500 error trying to access https://api.apitore.com/json/0 - is it something you can fix?

**Comment by MikeRalphson** [comment]
Seems to be working again.

**Comment by keigohtr** [comment]
@MikeRalphson Sorry for late reply. It may caused our server maintenance.
