### ISSUE TITLE
Add "旅行系サイト ごちゃまぜフィード" API

### ISSUE THREAD

**Issue by keigohtr** [APIs-guru/openapi-directory#205]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.apitore.com/json/36
**Name**: 旅行系サイト ごちゃまぜフィード

**Comment by keigohtr** [comment]
@MikeRalphson I fixed it. Please check my APIs again. Thank you :)

**Comment by MikeRalphson** [comment]
@keigohtr apitore.com seems to be down - using a self-signed certificate for example.com - this is causing our updates to fail. How should we proceed?
