### ISSUE TITLE
Extra fields to complement a valid OAuth workflows 

### ISSUE THREAD

**Issue by sanchojaf** [APIs-guru/openapi-directory#207]
Hi @IvanGoncharov, 

To automate OAuth workflows in Cenit IO(https://cenit.io) we  need complement the info in APIs Guru Directory  with some fields like I show bellow:

- https://app.asana.com/-/oauth_authorize:
      * name: Asana
      * response_type: code
      * token_endpoint: https://app.asana.com/-/oauth_token
      * token_method: POST
      * refresh_token_strategy: none
      * type: oauth2

The complete list that we have at his moment 

https://github.com/cenit-io/cenit/blob/master/config/oauth_providers.yaml

The specifications of APIs, at least swagger 2.0 only specific the security scheme

In the case of OAuth an entry for the authorization endpoint, but to be able to complete an authorization using OAuth the Authorization URL is not enough because OAuth has several parameters that can choose between providers

An automatic parser of a specification can not establish an OAuth authorization flow unless you have configured the parameters of the OAuth provider beforehand

The OAuth URL authorization is unique per provider. Then you can use it as a key

Would be great if is possible add this information in the APIs Guru Directory

Regards,
Miguel

**Comment by sanchojaf** [comment]
Hi Mike, 

I am working on your questions for answer you. thanks

**Comment by sanchojaf** [comment]
Hi @MikeRalphson , sorry for our delay with the answer.

I suggest close this issue, and then we will come back when we have a complete proposition.


Thanks for your time.
Miguel

**Comment by MikeRalphson** [comment]
@sanchojaf no problem, feel free to re-open at any point.
