### ISSUE TITLE
Add "Lyft" API

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#210]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.lyft.com/v1/spec
**Name**: Lyft
**Logo**: https://pbs.twimg.com/profile_images/748197248819834880/EvuRzyK8.jpg
**Categories**: location,
Source: https://medium.com/lyft-developer-platform/using-open-api-specification-to-put-lyft-sdk-support-in-the-fast-lane-7b623218e4ee

**Comment by MikeRalphson** [comment]
Thanks!
