### ISSUE TITLE
Add "BeezUP - Marketplaces - Orders" API

### ISSUE THREAD

**Issue by Johnny-Bee** [APIs-guru/openapi-directory#211]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://beezup.github.io/api-user_marketplaces_orders/swagger.json
**Name**: BeezUP - Marketplaces - Orders

**Comment by MikeRalphson** [comment]
API added, many thanks!

**Comment by MikeRalphson** [comment]
@Johnny-Bee your API definition appears to have been deleted by [this commit](https://github.com/BeezUP/beezup.github.io/commit/b954c9207383696e1cb13a91945cb8e5608a00ff). Could you give me a new url for it or reinstate it?

**Comment by Johnny-Bee** [comment]
We are currently putting in place a DNS for the documentation and the swagger.
I will get back to you ASAP.

**Comment by Johnny-Bee** [comment]
Format: OpenAPI(fka Swagger) 2.0
Official: YES
Url: https://api-docs.beezup.com/swagger.json
Name: BeezUP API

**Comment by Johnny-Bee** [comment]
@MikeRalphson Thanks for your patience!

**Comment by MikeRalphson** [comment]
Hi @Johnny-Bee I think I've found a small problem in your latest definition, though it isn't picked up by either of the validators we use (it showed up when test-converting it to OpenAPI 3.0).

```json
          {
            "name": "Accept-Encoding",
            "description": "Allows the client to indicate wether it accepts a compressed encoding to reduce traffic size.",
            "in": "header",
            "required": true,
            "type": "array",
            "items": {
              "type": "string",
              "collectionFormat": "csv"
            }
          }
```

the `collectionFormat` property is only applicable to type `array`, not to type `string` so it should be one level higher, i,e, applying to the `array` not the `array.items`.

```json
          {
            "name": "Accept-Encoding",
            "description": "Allows the client to indicate wether it accepts a compressed encoding to reduce traffic size.",
            "in": "header",
            "required": true,
            "type": "array",
            "collectionFormat": "csv",
            "items": {
              "type": "string"
            }
          }
```

**Comment by Johnny-Bee** [comment]
Thanks again, it's fixed! Just by curiosity, how do you proceed to convert to OpenAPI 3.0 ?
I use this app to check this up ! https://openapi-converter.herokuapp.com/

**Comment by MikeRalphson** [comment]
Yes, that's an app which uses the converter/validator I wrote :smile: The online version lags a little behind the github [master](https://github.com/mermade/swagger2openapi) but they should sync up again when OpenAPI spec 3.0.0-RC2 is released.

**Comment by MikeRalphson** [comment]
CI is all green.
