### ISSUE TITLE
Please add the documentation link to "BeezUP - Marketplaces - Orders"

### ISSUE THREAD

**Issue by Johnny-Bee** [APIs-guru/openapi-directory#212]
Hi Mike,

Could you be ever so kind as to put the link to the documentation for the API "BeezUP - Marketplaces - Orders" (https://beezup.github.io/api-user_marketplaces_orders/swagger.json) ? 

Documentation link: **https://beezup.github.io/api-user_marketplaces_orders/**

Where should put this information in the swagger ?

Thanks,
Johnny

**Comment by MikeRalphson** [comment]
Hi @Johnny-Bee - if you add this link in the `externalDocs` section of the root object, it will be automatically extracted and used on our 'Browse APIs page' and be available for use by all your other API clients.

e.g.

```json
{
  "swagger": "2.0",
  "info": {
    "description": "This API will gives you the ability to manage your orders.",
    "version": "2.0",
    "title": "Marketplaces - Orders",
    "contact": {
      "email": "support@beezup.com"
    },
    "license": {
      "name": "BeezUP",
      "url": "http://www.beezup.com"
    },
    "x-logo": {
      "url": "https://avatars0.githubusercontent.com/u/25665430",
      "backgroundColor": "#FFFFFF"
    }
  },
  "host": "api.beezup.com",
  "basePath": "/v2/user/marketplaces/orders",
  "externalDocs": {
    "description": "BeezUP - Marketplaces - Orders documentation",
    "url": "https://beezup.github.io/api-user_marketplaces_orders/"
  }
}
```

**Comment by Johnny-Bee** [comment]
Thanks ! It's done!
