### ISSUE TITLE
Add "Slicebox" API

### ISSUE THREAD

**Issue by KarlSjostrand** [APIs-guru/openapi-directory#215]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://slicebox.github.io/slicebox-api/swagger.yaml
**Name**: Slicebox

**Comment by MikeRalphson** [comment]
**Valid**: Yes

**Comment by KarlSjostrand** [comment]
Hi Mike,

It is designed to be self-hosted. I am aware that the host as it points now is unusable but never understood what to point at for this type of service. Any suggestions would be greatly appreciated.

Best,
Karl

**Comment by MikeRalphson** [comment]
Hi Karl, thanks for responding so promptly (and thanks for the initial submission). OpenAPI / Swagger 2.0 doesn't really have a solution for this. In one other case we have back-ported the [servers object](https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc1/versions/3.0.md#server-object) from OpenAPI 3.0.0 (which is currently in RC) as a [specification/vendor-extension](https://github.com/mermade/swaggerplusplus), as this allows host templates with replaceable parameters.

However this doesn't fully solve the problem (in the case above the `host` property is pointing to the provider's domain). Is it possible to fire up a test or mock server on heroku or a similar service? I can imagine there may be problems with data retention for this kind of API.

**Comment by KarlSjostrand** [comment]
That is correct; I am worried that if we set up a server we will at some point accidentally receive protected health information from users experimenting with the API. Pointing to localhost could perhaps be one alternative. Users could setup a local server a create calls via the API spec.

Best,
Karl

**Comment by MikeRalphson** [comment]
@KarlSjostrand apologies for the delay in getting back to you.

> I am aware that the host as it points now is unusable but never understood what to point at for this type of service. Any suggestions would be greatly appreciated.

We now have a strategy for adding self-hosted APIs, and bearing in mind the above I thought I'd share it with you.

We will patch the `host` in the definition to `slicebox.local`. This will allow users to use the API definition by simply creating an entry in `/etc/hosts` to point to their running instance (or they could edit the definition file, of course).

Does this sound like a workable plan?

**Comment by KarlSjostrand** [comment]
@MikeRalphson definitely. Many of the users I know already have this setup in their hosts file.

**Comment by MikeRalphson** [comment]
API added, many thanks.
