### ISSUE TITLE
Add "BREX" API

### ISSUE THREAD

**Issue by g30rg** [APIs-guru/openapi-directory#221]
**Format**: openapi_3
**Official**: yes
**Url**:  https://api.brex.io/docs/
**Name**: BREX

**Comment by MikeRalphson** [comment]
@g30rg this API definition fails validation. One problem I can see with it is that there are multiple instances of  parameters with:

```json
"type": "string",
"format": "string"
```

Swagger 1.x only allows a fixed set of `format`s and `string` is not one of them. 

Do you represent brex.io, or have a contact there who can fix the API definition?

**Comment by gcanturk** [comment]
Hi,
I am the representative of brex.io and who is gonna fix the API definition. We have updated our docs according to the openapi 3.0.0 specification. Could you please revalidate our definition in the link below?

**Format:** openapi 3.0.0
**Official**: yes
**Url**: https://api.brex.io/docs/
**Name**: BREX

**Comment by MikeRalphson** [comment]
Hi @gcanturk - the first thing I noticed is that your OpenAPI 3.0.0 definition is missing the `info` object. It has two mandatory properties: `title` and `version`.

**Comment by MikeRalphson** [comment]
Also, for example in https://api.brex.io/docs/v1-system/system_countries.json

```json
{
  "get": {
    "description": "Search for possible products for a particular subject",
    "operationId": "productSearchAction",
    "tags" : [ "v1-system" ],
    "security": [
      {
        "user_key": []
      }
    ],
    "responses": {
      "200": {
        "description": "List of countries",
        "$ref": "/docs/responses.json#/Countries"
      }
    }
  }
}
```

The `description` property is getting [lost](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#reference-object) when the `$ref` is dereferenced, thus your definition fails validation because of the missing `description`s.

**Comment by MikeRalphson** [comment]
@gcanturk also several parameters have an `in: form` which is not valid in OpenAPI3. FormData properties need to be converted into a `requestBody` object.

**Comment by g30rg** [comment]
Hi @MikeRalphson on behalf of @gcanturk I let you know that the latest version of our swagger docs can be found on the above mentioned URL incorporating your recent feedback.
Thanks for your patience and help - we'd kindly ask you to re-evaluate our swagger docs and let us know what needs fixing/improving

thanks again!

**Comment by MikeRalphson** [comment]
@g30rg @gcanturk thanks for your progress!

At path `/paths/~1api~1v1~1product~1availability~1{sku}~1{subjectId}/get/responses/200/content/application~1json/schema/properties/price/type` (and a few other locations) there is the `type: float` which isn't valid in OpenAPI3 schemaObjects. 

I guess this should be `type: number` possibly with a `format`? With those fixed, I think your definition is valid!

**Comment by MikeRalphson** [comment]
Oh, unless your API endpoint is relative to where the definition is downloaded from, you might also be missing a `servers` property at the root of the document.

**Comment by g30rg** [comment]
thanks one more time for the feedback and hints! both corrections, number `format` for `float` and missing `servers` entry in the root of the definition have been corrected.

**Comment by MikeRalphson** [comment]
Just running against another validator as a double-check. The following `$ref`s can't be resolved:

```
"$ref": "#Company"
"$ref": "#PepSanctionCheckResult"
"$ref": "#timestamp"
```
The reference should be to `#/components/schemas/...` in each case, e.g. `#/components/schemas/Company`.

**Comment by gcanturk** [comment]
@MikeRalphson thank you very much for your quick feedback. $ref s have been corrected. could you please re-evaluate our docs please?

**Comment by MikeRalphson** [comment]
```
expected '#/definitions/timestamp' not to start with '#/definitions/' (false negative fail)
#/paths/~1api~1v1~1company~1{id}~1announcements/post/responses/200/content/application~1json/schema/properties/time/$ref
```
As above the `$ref`s should start `#/components/schemas` not `#/definitions`.

**Comment by gcanturk** [comment]
@MikeRalphson I have updated the $ref s. Now they are starting with #/components/schemas. Could you please revalidate our docs? Thanks,

**Comment by MikeRalphson** [comment]
@gcanturk good progress. There are some duplicated `operationIds`, by the spec, these must be unique across the API definition.

**Comment by MikeRalphson** [comment]
Needs resolution support in api-spec-converter.

**Comment by g30rg** [comment]
Sorry for the probably simple-minded question - but is the api-spec-converter version update something we have to wait for - or is there something we can do about your remark from the 14th of Dec (sorry for the rather slow running response times since then)

**Comment by MikeRalphson** [comment]
@g30rg never apologise for asking a question! I can probably work around the api-spec-converter update.

As to the Dec 14th comment, if you check the `operationId` values in across your whole definition, they should be unique. If that's fixed, I think we're good to go. Apologies for the delay in sorting out openapi 3 support on our end.

**Comment by gcanturk** [comment]
@MikeRalphson thank you for your response. As I understand from the openapi specification, operationId is not a MUST value to have. And in our case, there are not any tools or libraries which use these values. Therefore we removed all operationIds in our docs. If it is okay, we're good to go as you said :) Thank you very much.

**Comment by MikeRalphson** [comment]
API added, many thanks for your patience, and for being our first accepted OpenAPI 3.0 definition!
