### ISSUE TITLE
Add "Realtime Forex Quotes" API

### ISSUE THREAD

**Issue by 1forge** [APIs-guru/openapi-directory#222]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://1forge.com/openapi.json
**Name**: Realtime Forex Quotes
**Valid**: Yes
**Logo**: http://1forge.com/logo.png
**Category**: financial

**Comment by MikeRalphson** [comment]
Many thanks for the submission!
