### ISSUE TITLE
Add "SYNQ Video API" API

### ISSUE THREAD

**Issue by paltorg** [APIs-guru/openapi-directory#223]
**Format**: Swagger 2.0
**Official**: YES
**Url**: https://docs.synq.fm/swagger/api.json
**Name**: SYNQ Video API
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/794554168509865985/c1UqSEfh_400x400.jpg
**Category**: media

**Comment by MikeRalphson** [comment]
Many thanks for the submission!
