### ISSUE TITLE
Add VictorOps API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#229]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://portal.victorops.com/public/api-docs/victorops-api-v1.yaml
**Name**: VictorOps API
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/618808966001197056/olm2Yd1M.jpg

VictorOps is an on-call management and incident notification platform.

**Comment by MikeRalphson** [comment]
Added, many thanks for the submission!
