### ISSUE TITLE
Magento API ?

### ISSUE THREAD

**Issue by sanchojaf** [APIs-guru/openapi-directory#230]
Hi Mike, 

The Magento API was visible in some moment? I think that was, but now I have doubt and I can't see on the list.

Please review the issue #118

**Comment by sanchojaf** [comment]
Well, I found, but why the folder name is so different, 't213' ?

**Comment by MikeRalphson** [comment]
> Well, I found, but why the folder name is so different, 't213' 

Magento seem to have changed the host used by the API:

```yaml
swagger: '2.0'
schemes:
  - http
host: t213.vg
basePath: /rest/default
```

and we use that host (not the host the API was supplied from - which might be github etc) to group the APIs. Checking the host it appears to be unregistered / a holding page, so I've no idea what is going on.

I will comment further on your PR.
