### ISSUE TITLE
Add "Kubernetes" API

### ISSUE THREAD

**Issue by sanchojaf** [APIs-guru/openapi-directory#232]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec
**Name**: Kubernetes

I think that is a hot API.

the complete file here:

`https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json`

Please check this version too.

`https://github.com/kubernetes/kubernetes/tree/master/api/swagger-spec`

**Comment by MikeRalphson** [comment]
Hi @sanchojaf the reason we haven't added the Kubernetes API before is that it is a relative-host / self-hosted API. The OpenAPI rules state that a definition without an explicit `host:` is relative to where the definition was loaded from, which would obviously cause us problems.

We basically don't have a good solution for this under OpenAPI 2.0 unless there is a demo hosted version of the API on a fixed URL.

**Comment by sanchojaf** [comment]
Hi @MikeRalphson, 

Is not possibly use the github url like the host?

`https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json`

Here in the documentation URL

https://kubernetes.io/docs/concepts/overview/kubernetes-api/

they say that it is the official place for /swagger.json

**Comment by MikeRalphson** [comment]
@sanchojaf No, that would make `https://raw.githubusercontent.com` the host for the API, which is obviously never going to implement the API in the definition.

**Comment by sanchojaf** [comment]
Understood, thanks @MikeRalphson

**Comment by MikeRalphson** [comment]
In OpenAPI 3.0 it will be possible to template the host URL to get around this problem, but I think it's too early to even put a plan in place for the timescale to convert this repository.

**Comment by MikeRalphson** [comment]
@sanchojaf I've come up with a solution which I hope will work for people.

Relative host APIs will have a host set which uses the `.local` top-level domain. This means all you have to do to use it is to add a local hosts file entry pointing at the correct API instance (or of course you could edit the definition).

**Comment by MikeRalphson** [comment]
API added/deployed.
