### ISSUE TITLE
Add "Icons8" API

### ISSUE THREAD

**Issue by visualpharm** [APIs-guru/openapi-directory#234]
**Format**: API Blueprint
**Official**: YES
**Url**: http://docs.icons8.apiary.io/api-description-document
**Name**: Icons8 API
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/837777358883065857/YCw6bjtl_400x400.jpg
**Category**: Media

**Comment by MikeRalphson** [comment]
See https://github.com/kminami/apib2swagger/issues/22

**Comment by MikeRalphson** [comment]
See also https://github.com/kminami/apib2swagger/issues/24

**Comment by MikeRalphson** [comment]
API added. It's not a perfect conversion, but at least it passes the validators now, and it will continue to improve as the converters used improve.

Many thanks for the submission!
