### ISSUE TITLE
Add "BridgeDb Webservices" API

### ISSUE THREAD

**Issue by egonw** [APIs-guru/openapi-directory#238]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://www.bridgedb.org/swagger/swagger.json
**Name**: BridgeDb Webservices

**Comment by MikeRalphson** [comment]
**Valid**: No

```json
    "definitions":{
    "IdList2":{
        "type":"tsv",
        "properties":{
            "id":{
                "type":"string",
                "description":""
            }
        }

    }
```

`tsv` used as a type, not a `collectionFormat`.

**Comment by egonw** [comment]
@MikeRalphson, thanks! Where are you doing this validation? Then I can make sure we have fully validating OpenAPI before I send another (next) request...

**Comment by MikeRalphson** [comment]
I'm using a collection of validation tools wrapped up into a simple utility called [check_api](https://github.com/mermade/check_api).

For Swagger / OpenAPI 2.0 you can use the online version of the validator, which will give you the same results: http://bigstickcarpet.com/swagger-parser/www/index.html

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
