### ISSUE TITLE
Add "eNanoMapper Database API" API

### ISSUE THREAD

**Issue by egonw** [APIs-guru/openapi-directory#239]
**Format**: Swagger 1.x
**Official**: YES
**Url**: https://data.enanomapper.net/api-docs
**Name**: eNanoMapper Database API

**Comment by MikeRalphson** [comment]
**Valid**: No

```json
{
  "errors": [
    {
      "code": "INVALID_FORMAT",
      "message": "Object didn't pass validation for format email: Ideaconsult Ltd.",
      "path": [
        "info",
        "contact"
      ]
    },
    {
      "code": "ONE_OF_MISSING",
      "message": "Not a valid authorizations definition",
      "path": [
        "authorizations",
        "apiKey"
      ]
}
```

**Comment by MikeRalphson** [comment]
@egonw Thanks for your submissions! Unfortunately each of them contain validation issues against the relevant specification. Do you have contacts regarding these APIs, where we can work to get the problems fixed upstream - this is far better for me than maintaining patches locally in APIs.guru.

**Comment by egonw** [comment]
Yes, just filing the third upstream bug report :)

**Comment by MikeRalphson** [comment]
check_api probably only needs a little work to drop a non-zero exitcode on failure, for it to be used in a CI environment, if you wanted to automate that step. Happy to make those changes.

**Comment by MikeRalphson** [comment]
We no longer support Swagger 1.2, please let us know if you upgrade to 2.0 or OpenAPI 3.x

**Comment by egonw** [comment]
@vedina, which OpenAPI version does the latest AMBIT support?

**Comment by vedina** [comment]
OpenAPI3 is supported by http://api.ideaconsult.net/

**Comment by egonw** [comment]
@MikeRalphson, can you plz have a look at the newer API and reconsider?

**Comment by MikeRalphson** [comment]
That's brilliant, thanks. Both APIs added. Website will update as soon as the CI run finishes. Thanks again.
