### ISSUE TITLE
Add "Kubernetes" API

### ISSUE THREAD

**Issue by mbohlool** [APIs-guru/openapi-directory#242]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json
**Name**: Kubernetes

**Comment by MikeRalphson** [comment]
Please see open issue #232 - thanks.

**Comment by MikeRalphson** [comment]
@mbohlool Just a note that the Kubernetes API has (finally) been added.
