### ISSUE TITLE
Add "Storecove API"

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#245]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.storecove.com/api/v2/openapi.json
**Name**: Storecove API
API docs: https://www.storecove.com/docs
**Valid**: Yes
**Category**: finance
**Logo**: https://www.storecove.com/assets/v2/logo-b0d52166b7aedce1c08416e14480dcefd5db3f8a68704a6b802c37b189dd8894.png

**Comment by MikeRalphson** [comment]
@hkosova Many thanks for the submission!

**Comment by MikeRalphson** [comment]
API added, many thanks.
