### ISSUE TITLE
Add "Airports Web" API

### ISSUE THREAD

**Issue by Bombenleger** [APIs-guru/openapi-directory#246]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://airport-web.appspot.com/api/docs/swagger.json
**Name**: Airports Web
**Valid**: Yes
**Category**: transport

**Comment by Bombenleger** [comment]
@MikeRalphson no, it's just nothing deployed on root

**Comment by MikeRalphson** [comment]
API added,, many thanks for the submission.

**Comment by MikeRalphson** [comment]
![image](https://user-images.githubusercontent.com/21603/37955263-098e5b38-31a0-11e8-96fd-5755b16341e3.png)
