### ISSUE TITLE
Add "dropX.io API"

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#248]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://dropx.io/dropx-swagger.yaml
**Name**: dropX.io API
**Valid**: Yes
**Relative Host**: No
**Category**: ecommerce
**Logo**: http://dropx.io/images/dropx-logo.svg

**Comment by korovinsrg** [comment]
1.

**Comment by MikeRalphson** [comment]
API added, many thanks - apologies for the delay working through these.
