### ISSUE TITLE
Add "eBay Buy Browse API"

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#249]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developer.ebay.com/api-docs/master/buy/browse/openapi/2/buy_browse_v1_beta.json
**Name**: eBay Buy Browse API
**Valid**: Yes
**Relative Host**: No
**Category**: ecommerce
**Logo**: https://pbs.twimg.com/profile_images/667048357307662338/PzXHlU9N_400x400.png

**Comment by korovinsrg** [comment]
Ffrf

**Comment by MikeRalphson** [comment]
Many thanks @hkosova for this and the other submissions. The eBay APIs have been added.
