### ISSUE TITLE
Add "eBay Buy Marketing API"

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#250]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developer.ebay.com/api-docs/master/buy/marketing/openapi/2/buy_marketing_v1_beta.json
**Name**: eBay Buy Marketing API
**Valid**: Yes
**Relative Host**: No
**Category**: ecommerce
**Logo**: https://pbs.twimg.com/profile_images/667048357307662338/PzXHlU9N_400x400.png

**Comment by MikeRalphson** [comment]
API added, many thanks.
