### ISSUE TITLE
Add "eBay Commerce Taxonomy API"

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#251]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developer.ebay.com/api-docs/master/commerce/taxonomy/openapi/2/commerce_taxonomy_v1_beta.json
**Name**: eBay Commerce Taxonomy API
**Valid**: Yes
**RelativeHost**: No
**Category**: ecommerce
**Logo**: https://pbs.twimg.com/profile_images/667048357307662338/PzXHlU9N_400x400.png

**Comment by MikeRalphson** [comment]
API added, many thanks.
