### ISSUE TITLE
Add "Noosh API"

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#252]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.noosh.com/api/swagger.json
**Name**: Noosh API
**Valid**: Yes
**RelativeHost**: Yes? (example.com)
Twitter: NooshInc
Category: collaboration

**Comment by MikeRalphson** [comment]
API added, many thanks.
