### ISSUE TITLE
Add "PI Web API"

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#253]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://devdata.osisoft.com/piwebapi/help/specification
**Name**: PI Web API
**Valid**: Yes
**RelativeHost**: No
**Logo**: https://pbs.twimg.com/profile_images/530511270303129600/zaaVnH1U_400x400.jpeg
**Category**: enterprise

**Comment by MikeRalphson** [comment]
API added - waiting on CI.

**Comment by MikeRalphson** [comment]
CI completed, many thanks!
