### ISSUE TITLE
Add "API2Cart" API

### ISSUE THREAD

**Issue by Nazarii97** [APIs-guru/openapi-directory#254]
**Format**: RAML
**Official**: YES
**Url**: https://api2cart.com
**Name**: API2Cart

**Comment by MikeRalphson** [comment]
@Nazarii97 thanks! Do you have a link to the RAML (or possibly Swagger?) machine-readable API definition?

**Comment by Nazarii97** [comment]
@MikeRalphson Hi Mike, unfortunately no, we have only documentation.

**Comment by MikeRalphson** [comment]
@Nazarii97 unfortunately we won't be able to add the API to the collection, as it's for machine-readable definitions only. If you wanted to produce a client-facing OpenAPI 2.0 definition from your docs, there is a tool called [scrape-to-swagger](https://github.com/bobby-brennan/scrape-to-swagger).
