### ISSUE TITLE
Add "Postmark" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#255]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://postmarkapp.com/swagger/server.yml
**Name**: Postmark
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/879295889185157120/ZYlwxzeY_400x400.jpg
**RelativeHost**: No

**Comment by MikeRalphson** [comment]
Many thanks @hkosova - keep 'em coming!
