### ISSUE TITLE
Add "Postmark Account-level API"

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#256]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://postmarkapp.com/swagger/account.yml
**Name**: Postmark Account-level API
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/879295889185157120/ZYlwxzeY_400x400.jpg
**RelativeHost**: No

This is a different API than #255.

**Comment by MikeRalphson** [comment]
API added, many thanks.
