### ISSUE TITLE
Add "KEL" API

### ISSUE THREAD

**Issue by jillcarter1987** [APIs-guru/openapi-directory#257]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://www.facebook.com/kelly.murphy.9634
**Name**: KEL

**Comment by MikeRalphson** [comment]
@jillcarter1987 is this a real API - do you have a link to a machine-readable API definition to add to the collection?

**Comment by MikeRalphson** [comment]
Closing - assuming spam.
