### ISSUE TITLE
Add Lufthansa API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#258]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/LufthansaOpenAPI/Swagger/master/LH_public_API_swagger_2_0.json
**Name**: Lufthansa Public API
**Valid**: Yes
**Logo**: https://avatars2.githubusercontent.com/u/22329684?v=4&s=200
**Category**: transport

**Comment by MikeRalphson** [comment]
Many thanks for the submissions @hkosova !
