### ISSUE TITLE
Add Lufthansa Partner API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#259]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/LufthansaOpenAPI/Swagger4Partners/master/LH-OpenAPI-Partners-Swagger2.json
**Name**: Lufthansa Partner API
**Valid**: Yes

**Comment by MikeRalphson** [comment]
Many thanks again.
