### ISSUE TITLE
Add "Jumpseller" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#260]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.jumpseller.com/swagger.json
**Name**: Jumpseller
**Valid**: No
**RelativeHost**: No
**Logo**: https://pbs.twimg.com/profile_images/593356776478789632/CvroDphE_400x400.png
**Category**: ecommerce

**Comment by MikeRalphson** [comment]
Definition doesn't have an `info.title` property.

**Comment by MikeRalphson** [comment]
Patched. API added, many thanks!
