### ISSUE TITLE
Add "Public Transport Victoria" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#262]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://timetableapi.ptv.vic.gov.au/swagger/docs/v3
**Name**: Public Transport Victoria
**Valid**: Yes
**Category**: transport
**Logo**: https://pbs.twimg.com/profile_images/544730682023346176/sAia9jJQ_400x400.jpeg

**Comment by MikeRalphson** [comment]
API added, many thanks.
