### ISSUE TITLE
Add "Auckland Museum" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#264]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://api.aucklandmuseum.com/apidoc
**Name**: Auckland Museum
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/3189440223/bdf15148765709ca93c66597839b5589_400x400.png
**Category**: open_data

**Comment by MikeRalphson** [comment]
API added, many thanks!
