### ISSUE TITLE
Add "LotaData" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#265]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developers.lotadata.com/swagger/spec/apiv2.json
**Name**: LotaData
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/664666044754079744/OtP5eqwm_400x400.png
**Category**: location

**Comment by MikeRalphson** [comment]
API added, many thanks!
