### ISSUE TITLE
Add "TVmaze user API"

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#266]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://static.tvmaze.com/apidoc/v1.yaml
**Name**: TVmaze user API
**Valid**: Yes
**Category**: media
**Logo**: https://pbs.twimg.com/profile_images/515600283242463232/-APY1VAo_400x400.png

**Comment by MikeRalphson** [comment]
API added, many thanks again.
