### ISSUE TITLE
Add "O2 Mobility" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#267]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developer.o2.cz/mobility/sandbox/api/swagger.json
**Name**: O2 Mobility
**Valid**: Yes - self-signed or other https issue
**Category**: telecom
**Logo**: https://pbs.twimg.com/profile_images/443742048365985792/Zech6Z-m_400x400.png

**Comment by MikeRalphson** [comment]
API added, many thanks.
