### ISSUE TITLE
Add WMATA Bus Route and Stop Methods API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#270]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Name**: WMATA Bus Route and Stop Methods API
**Url**: https://developer.wmata.com/docs/services/54763629281d83086473f231/export?DocumentFormat=Swagger
**Valid**: Yes

WMATA = Washington Metropolitan Area Transit Authority

**Comment by MikeRalphson** [comment]
API added, many thanks.
