### ISSUE TITLE
Add WMATA Incidents API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#271]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developer.wmata.com/docs/services/54763641281d83086473f232/export?DocumentFormat=Swagger
**Name**: WMATA Incidents API
**Valid**: Yes
**Category**: transport

WMATA = Washington Metropolitan Area Transit Authority

**Comment by MikeRalphson** [comment]
API added, many thanks.
