### ISSUE TITLE
Add WMATA Rail Station Information API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#272]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developer.wmata.com/docs/services/5476364f031f590f38092507/export?DocumentFormat=Swagger
**Name**: WMATA Rail Station Information
**Valid**: Yes
**Category**: transport

WMATA = Washington Metropolitan Area Transit Authority

**Comment by MikeRalphson** [comment]
API added, many thanks.
