### ISSUE TITLE
Add WMATA Real-Time Bus Predictions API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#273]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developer.wmata.com/docs/services/5476365e031f590f38092508/export?DocumentFormat=Swagger
**Name**: WMATA Real-Time Bus Predictions
**Valid**: Yes
**Category**: transport

WMATA = Washington Metropolitan Area Transit Authority

**Comment by MikeRalphson** [comment]
API added, many thanks.
