### ISSUE TITLE
Add WMATA Real-Time Rail Predictions API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#274]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developer.wmata.com/docs/services/547636a6f9182302184cda78/export?DocumentFormat=Swagger
**Name**: WMATA Real-Time Rail Predictions
**Valid**: Yes
**Category**: transport
**Logo**: https://pbs.twimg.com/profile_images/874608810190622720/rRcPRXuu_400x400.jpg
**Twitter**: wmata

WMATA = Washington Metropolitan Area Transit Authority

**Comment by MikeRalphson** [comment]
API added, many thanks.
