### ISSUE TITLE
Add "CallFire" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#275]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.callfire.com/v2/api-docs/swagger.json
**Name**: CallFire
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/537371596508258305/zP_eP2ec_400x400.png
**Category**: telecom

**Comment by MikeRalphson** [comment]
API added, many thanks!
