### ISSUE TITLE
Add "Open Skills" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#276]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://api.dataatwork.org/v1/spec/skills-api.json
**Name**: Open Skills API
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/593962900408008704/WT7rcPhZ_400x400.jpg
**Category**: open_data

**Comment by MikeRalphson** [comment]
API added, many thanks!
