### ISSUE TITLE
Add "Gisgraphy" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#278]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://www.gisgraphy.com/documentation/gisgraphy-swagger.json
**Name**: Gisgraphy
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/441510755695730688/YO5xyggi_400x400.png
**Category**: location

**Comment by MikeRalphson** [comment]
API added, many thanks.
