### ISSUE TITLE
Add "Zalando" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#279]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.zalando.com/schema/swagger.json
**Name**: Zalando
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/706915005350993921/VxX5h1J3_400x400.jpg
**Category**: ecommerce

**Comment by MikeRalphson** [comment]
API added, many thanks!
