### ISSUE TITLE
a path missing from github API

### ISSUE THREAD

**Issue by shaharsol** [APIs-guru/openapi-directory#28]
I'd like to use `PUT /orgs/:org/memberships/:username` in the [github API](https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership) but think it's missing from the swagger file.

**Comment by IvanGoncharov** [comment]
@shaharsol This is actually a complicated issue.
I use Mulesoft`s [raml spec](https://github.com/raml-apis/GitHub/tree/production) and just convert it to Swagger. You can try to open issue there but in my experience they will just ignore it.
I plan to create  separate repos for non-official specs like Github to maintain them independently.
But before that I want convert all information from RAML spec. Right now I missing some non-essential stuff like examples, per-operation oauth scopes, etc. I plan to finish this work sometime next week, so I can't fix it until then.

**Comment by MikeRalphson** [comment]
@shaharsol if this is still an issue for you, I can try and transplant the path from [this](https://raw.githubusercontent.com/bobby-brennan/scrape-to-swagger/master/output/github.swagger.json) repository's GitHub definition. It may depend on how many models it references.

**Comment by MikeRalphson** [comment]
Alternative OAS definition from `octokit/routes` on the way? https://github.com/octokit/routes/pull/168

**Comment by MikeRalphson** [comment]
This route is now present in `APIs/github.com/9.0.0/openapi.yaml`
