### ISSUE TITLE
Add "NPR One" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#280]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.npr.org/documentation/calcium/swagger.json
**Name**: NPR One
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/722199003845304320/s2zwEoao_400x400.jpg
**Category**: media

**Comment by MikeRalphson** [comment]
API added, many thanks.
