### ISSUE TITLE
Add "OpenSTF" API

### ISSUE THREAD

**Issue by vbanthia** [APIs-guru/openapi-directory#286]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/openstf/stf/master/lib/units/api/swagger/api_v1_generated.json
**Name**: OpenSTF

**Comment by MikeRalphson** [comment]
Thanks! Is this a relative host / IoT API?

**Comment by vbanthia** [comment]
Yes, it is a relative host. User host this tool/service on their on domain.

**Comment by MikeRalphson** [comment]
Unfortunately, until we convert the project to OpenAPI 3.0 we don't really have a good solution for relative-host APIs. Will keep this issue open until the way forward is known.

**Comment by MikeRalphson** [comment]
Hi @vbanthia, we now have a solution for this. We will set the `host` property in the definition to `openstf.local` and users can either amend this or add such an entry to their `hosts` file.

API added, many thanks and apologies for the delay.
