### ISSUE TITLE
WMATA - Rail and Bus APIs are reversed

### ISSUE THREAD

**Issue by bobby-brennan** [APIs-guru/openapi-directory#288]
Specifically, the specs for `rail-realtime` and `bus-realtime` are swapped:

https://github.com/APIs-guru/openapi-directory/blob/master/APIs/wmata.com/bus-realtime/1.0/swagger.yaml

https://github.com/APIs-guru/openapi-directory/blob/master/APIs/wmata.com/rail-realtime/1.0/swagger.yaml

**Comment by MikeRalphson** [comment]
Thanks for spotting this @bobby-brennan ! The definitions should be under the right headings now.

**Comment by bobby-brennan** [comment]
Thanks for the quick fix!
