### ISSUE TITLE
Consolidate "finance" and "financial" categories

### ISSUE THREAD

**Issue by bobby-brennan** [APIs-guru/openapi-directory#290]
Under `x-apisguru-categories`, I'm seeing "finance" used by Storecove, but "financial" used by spectrocoin, yunbi, and others.

**Comment by MikeRalphson** [comment]
Corrected two instances of 'finance' (storecove and openbanking.org.uk) to 'financial' as per `categories.yaml`. Just waiting on CI to finish.

**Comment by MikeRalphson** [comment]
Many thanks for spotting this and letting me know.
