### ISSUE TITLE
Add "Fruit Shop Demo API" API

### ISSUE THREAD

**Issue by predic8** [APIs-guru/openapi-directory#291]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.predic8.de/shop/swagger
**Name**: Fruit Shop Demo API

**Comment by MikeRalphson** [comment]
Hi @predic8 many thanks for the submission.

Unfortunately we do not include demo APIs in the collection. 

Additionally, I noticed there were a few validation errors in the definition. See http://bigstickcarpet.com/swagger-parser/www/index.html
