### ISSUE TITLE
Add "Circuit" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#293]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://circuitsandbox.net/rest/v2/swagger
**Name**: Circuit
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/463690034235731970/0fImzk_g_400x400.png
**Category**:  messaging

**Comment by MikeRalphson** [comment]
API added, many thanks.
