### ISSUE TITLE
Add "RiteKit" API

### ISSUE THREAD

**Issue by pavelhouzva** [APIs-guru/openapi-directory#294]
**Format**: API Blueprint
**Official**: YES
~~**Url**: http://docs.ritekit.apiary.io/~~
**Url**: https://raw.githubusercontent.com/RiteKit/api-docs/master/apiary.apib
**Name**: RiteKit
**Category**: social
**Logo**: https://pbs.twimg.com/profile_images/781729376161366016/qdUFUsCN_400x400.jpg

**Comment by MikeRalphson** [comment]
API added, many thanks for the submission!
