### ISSUE TITLE
Add "Australian Taxation Office Business Registries" API

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#295]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
~~**Url**: https://github.com/ato-team/business-registries-rest-api-specification~~
**Url**: https://ato-team.github.io/business-registries-rest-api-specification/swagger.yaml
**Name**: Australian Taxation Office Business Registries
**Valid**: Yes
**Category**: financial
**Logo**: already present

**Comment by MikeRalphson** [comment]
API added, many thanks! :)
