### ISSUE TITLE
Add "Zuora" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#296]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.zuora.com/wp-content/themes/zuora/yaml/swagger.yaml?v-7.0
**Name**: Zuora
**Valid**: Yes
**Logo**: ~~https://pbs.twimg.com/profile_images/668119405658697728/-9vZg-QM_400x400.jpg~~ already present
**Category**: financial

**Comment by MikeRalphson** [comment]
@hkosova the logo referenced in the API definition 404s for me, can this be updated?

**Comment by MikeRalphson** [comment]
Logo patched locally to allow CI deploy to continue.
