### ISSUE TITLE
Add "Twine Health" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#297]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://twinehealth.github.io/TwineDeveloperDocs/swagger.yaml
or
https://raw.githubusercontent.com/TwineHealth/TwineDeveloperDocs/master/spec/swagger.yaml
**Name**: Twine Health
**Valid**: Yes
**Logo**: ~~https://pbs.twimg.com/profile_images/668845182394200064/D5A1sjF1_400x400.png~~ already present
**Category**: support

**Comment by MikeRalphson** [comment]
@hkosova thanks again for this. The `info.x-logo.url` property should be an absolute URL, otherwise there is ambiguity over whether it should be relative to where the API definition was downloaded from or the API basepath.

**Comment by hkosova** [comment]
Opened an issue in the Twine repo: TwineHealth/TwineDeveloperDocs/issues/7.

**Comment by hkosova** [comment]
The Twine team updated the spec.

**Comment by MikeRalphson** [comment]
Apologies, forgot to close this issue.
