### ISSUE TITLE
Add "Budget Insight Budgea API" API

### ISSUE THREAD

**Issue by jukebox** [APIs-guru/openapi-directory#298]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://budgea.biapi.pro/2.0/doc/
**Name**: Budget Insight Budgea API
**Valid**: No (ids)
**Category**:
**Logo**:

**Comment by MikeRalphson** [comment]
@jukebox Thanks for the submission. Unfortunately there are some validation errors found when checking this API definition.

The first issue involves extraneous `id` and `$schema` properties, which are not part of the Swagger 2.0 `schema` object. Also, Swagger 2.0 mandates the use of JSON schema draft 4, not draft 3 as referenced in the `$schema` properties.

As the validator aborts on the first error, there may be additional issues.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
