### ISSUE TITLE
Add "OpenFinTech.io" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#299]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://docs.openfintech.io/swagger.yaml
**Name**: OpenFinTech.io
**Valid**: Yes
**Category**: financial
**Logo**: https://pbs.twimg.com/profile_images/801106543160754176/VGeBUAhr_400x400.jpg

**Comment by MikeRalphson** [comment]
API added, many thanks.
