### ISSUE TITLE
Add "Registered Domain Names Search" API

### ISSUE THREAD

**Issue by sneg55** [APIs-guru/openapi-directory#302]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://domains-index.com/apidomainsdb/swagger.json
**Name**: Registered Domain Names Search
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/769216960504532996/rctG95A0_400x400.jpg
**Category**: hosting

**Comment by MikeRalphson** [comment]
API added, many thanks!
