### ISSUE TITLE
Incorect "x-description-language": "jp" values

### ISSUE THREAD

**Issue by darosh** [APIs-guru/openapi-directory#308]
_Thank you very much for the "[x-description-language](https://github.com/APIs-guru/openapi-directory/wiki/specification-extensions#x-description-language)" it is very useful for search indexing!_

Specs marked as Japanese `"x-description-language": "jp"` are in English language. 

See in: https://github.com/APIs-guru/openapi-directory/search?p=4&q=%22x-description-language%3A++jp%22&type=&utf8=%E2%9C%93

For example: https://github.com/APIs-guru/openapi-directory/blob/f6a15723fdeff83b581dd6a48a61a22890699be7/APIs/apitore.com/documentFrequencyApis/0.0.1/swagger.yaml

I believe this affects all apitore.com APIs via this script: https://github.com/APIs-guru/openapi-directory/blob/751d9c5f3d1eea8facf0b1bac67f9f0ac659359a/scripts/spec_sources/apitore.js#L24

I guess, the origin was probably translated into English some time ago.

**Comment by MikeRalphson** [comment]
Many thanks for spotting this @darosh ! Indeed, the descriptions were in Japanese when they were originally being added, but the upstream must have decided to translate them in the mean time.

Scripts, patch.yaml files and swagger.yaml files updated, just waiting on CI to complete.

**Comment by MikeRalphson** [comment]
Should be all republished now, thanks again.
