### ISSUE TITLE
Bug; update script ignores new APIs from spec_sources unless run for that directory only.

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/openapi-directory#309]
It appears we still have a bug in the update script (which I'd suspected) where if the list of APIs from an organisation is dynamic (i.e. there is a `spec_source` 'provider' for them), new APIs don't get added during the normal update process, only if update is run for that specific directory... 

This section is obviously not doing the do.

https://github.com/APIs-guru/openapi-directory/blob/44f4424e62363d9e9973e597566d2e8128dee3dc/scripts/spec_sources/index.js#L47-L55

Confirmed during processing for #308

**Comment by IvanGoncharov** [comment]
@MikeRalphson It was intentional, I made separate `leads` subcomand for that.

**Comment by MikeRalphson** [comment]
Doh!
