### ISSUE TITLE
Add "EtMDB (Ethiopian Movie Database)" API

### ISSUE THREAD

**Issue by dawitnida** [APIs-guru/openapi-directory#312]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://etmdb.com/api/docs/endpoints/?format=openapi
**Name**: EtMDB (Ethiopian Movie Database)
**Valid**: Yes
**Category**: media

**Comment by dawitnida** [comment]
Logo: https://etmdb.com/static/images/xprofile.png.pagespeed.ic.O-UriIYhZO.webp

**Comment by MikeRalphson** [comment]
@dawitnida Thanks for the submission. There's just a couple of validation errors with your definition.

In the `securityDefinitions/oauth2` object:

* `name` as a property is only applicable to `apiKey` securitySchemes, not `oauth2` - you can remove this
* `tokenUrl` as a property is only [applicable](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-15) to a `flow` of "password", "application", or "accessCode", not "implicit". Here I'm not sure if the flow is incorrect or your API actually allows authorisation by more than one oauth2 flow, in which case there should be 2 or more `securityDefinitions`.

You can re-check your definition at http://bigstickcarpet.com/swagger-parser/www/index.html

**Comment by dawitnida** [comment]
@MikeRalphson Just updated and it passes the validation. Thanks for the feedback.

**Comment by MikeRalphson** [comment]
Great stuff @dawitnida thanks for getting back to me. Confirmed, will add.

**Comment by MikeRalphson** [comment]
API added, many thanks again.
