### ISSUE TITLE
Add "External Communication Microservice" API

### ISSUE THREAD

**Issue by ZainabOlapade01** [APIs-guru/openapi-directory#313]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: NO
**Url**: http://apis.shoppi.ng/communication/documentation/index.html
**Name**: External Communication Microservice

**Comment by MikeRalphson** [comment]
@ZainabOlapade01 that URL is not resolvable for me. Is it correct? We also need a link to the machine-readable API definition, not an `index.html` page.

**Comment by MikeRalphson** [comment]
Closing in favour of #318
