### ISSUE TITLE
Add "SelectPdf" API

### ISSUE THREAD

**Issue by selectpdf** [APIs-guru/openapi-directory#316]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://selectpdf.com/api/selectpdf-swagger.json
**Name**: SelectPdf
**Valid**: Yes
**Logo**: https://pbs.twimg.com/profile_images/566507399226212354/KWXTM5rW_400x400.jpeg
**Category**: text

**Comment by MikeRalphson** [comment]
@selectpdf thanks for the submission! Do you have a copy of the definition which points at a live server rather than the 'virtserver.swaggerhub.com' mock server?

**Comment by selectpdf** [comment]
Url: [https://selectpdf.com/api/selectpdf-swagger.json](https://selectpdf.com/api/selectpdf-swagger.json)
Definition updated to point to our liver server.

**Comment by MikeRalphson** [comment]
API added, just running CI now. Congratulations on having a first-time valid definition!

**Comment by selectpdf** [comment]
Thank you!

**Comment by selectpdf** [comment]
Seems that CI/deployment failed. Can you please check?

**Comment by MikeRalphson** [comment]
Yes, it was an unrelated error with another API's logo. You should see it now at https://apis.guru/browse-apis/ e.g. if you search for 'pdf'.
