### ISSUE TITLE
Add "TaxRates.io" API

### ISSUE THREAD

**Issue by dcacik** [APIs-guru/openapi-directory#319]
**Format**: Swagger 2.0
**Official**: YES
**Url**: https://api.taxrates.io/taxrates_io_API.yaml
**Name**: TaxRates.io
**Valid**: Yes
**Category**: financial
**Logo**: https://pbs.twimg.com/profile_images/919999226955927553/lLFntE3W_400x400.jpg

**Comment by MikeRalphson** [comment]
Many thanks for the submission @dcacik - API added.
