### ISSUE TITLE
Add "Fun Translations" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#320]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://api.funtranslations.com/yaml/funtranslations.yaml
**Name**: Fun Translations
**Valid**: Yes
**Category**: text
~~**Logo**: http://funtranslations.com/img/pirate.png~~
**Twitter**: https://twitter.com/funtranslate

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
