### ISSUE TITLE
Add "GeoDB City API" API

### ISSUE THREAD

**Issue by wirefreethought** [APIs-guru/openapi-directory#323]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://wirefreethought.github.io/geo-db-city-api-docs/swagger.json
**Name**: GeoDB City API
**Valid**: Yes
**Category**: developer_tools,location
**Logo**: https://wirefreethought.github.io/geo-db-city-api-docs/images/logo.png

**Comment by MikeRalphson** [comment]
Hi @wirefreethought thanks for the contribution!

Just one small validation issue to take care of, the `security` object should be an array of `securityRequirement` objects, even if it has only one entry.

**Comment by wirefreethought** [comment]
@MikeRalphson This is done.

**Comment by MikeRalphson** [comment]
API added, many thanks again.
