### ISSUE TITLE
Add "nfusion solutions precious metals" API

### ISSUE THREAD

**Issue by nfusionsolutions** [APIs-guru/openapi-directory#328]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.nfusionsolutions.biz/swagger/1/swagger.json
**Name**: nfusion solutions precious metals
**Valid**: Yes
**Twitter**: nfusionsolution
**Category**: financial

**Comment by MikeRalphson** [comment]
API added, and caongratulations on having a first-time valid definition!
