### ISSUE TITLE
Add "Instawell" API

### ISSUE THREAD

**Issue by instawell** [APIs-guru/openapi-directory#329]
**Format**: RAML 1.0
**Official**: YES
**Url**: https://github.com/instawell/Instawell/blob/master/APIDocs/InstawellAPIDocs.raml
**Name**: Instawell

**Comment by MikeRalphson** [comment]
Hi @instawell , many thanks for the submission.

The RAML 1.0 parser I use flagged up the following issues:

```
[ { code: 'SUSPICIOUS_DOUBLEQUOTE',
    message: 'Suspicious double quoted multiline scalar, it is likely that you forgot closing "The Instawell API gives you access to  helpers all over the world. Integrate Instawell with your app using our API to get help wherever you are. Follow the instructions below to get started.\r\n\r\nBase URL\r\n----\r\nThe Instawell API supports a sandbox mode by making API calls to our sandbox server. Using the Sandbox server, you can make sure your integrations are working before deploying them to production. \r\n\r\nSandbox mode is accessed by using the following base URL\r\n\r\n~~~~\r\nhttps://api-sandbox.instawell.com/\r\n~~~~\r\n\r\nProduction mode is acccessed by using the following base URL\r\n\r\n~~~~\r\nhttps://api.instawell.com/\r\n~~~~\r\n\r\n\r\nGet your Access Token\r\n-----\r\n\r\nThe token to access the Campaign API is available when you create your first Campaign or when you request your first Plan. Have a look at the Create Campaign method to find out how to do this.\r\n\r\nMost requests made to the Instawell API require the auth token to be sent as part of the header. Exceptions will be noted in the docs. The name of the header to be used is X-instawell-token\r\n\r\n~~~~\r\nX-instawell-token: TEST_TOKEN\r\n~~~~\r\n\r\nOnce you have your token, you\'re ready to go.',
    path: 'insta.yaml',
    range:
     { start: { line: 7, column: 11, position: 154 },
       end: { line: 7, column: 1212, position: 1355 } },
```

I'm not 100% sure about that as an error, but it can be worked-around by indenting the text and adding the yaml `>-` indicator for a multi-line string.

In your examples, the `id` and `price` properties should be quoted strings (or otherwise, the types in the models are wrong). Lines 14,18,20,565,569,571

No rush, as we still have some [work to do](https://github.com/LucyBot-Inc/api-spec-converter/issues/109) to support RAML 1.0

**Comment by instawell** [comment]
Hey Mike
Thank you for getting back to us so quickly. 

Will look at this as quickly as possible. To clarify, would you be able to use this version for now?

Thanks
Abhi

**Comment by MikeRalphson** [comment]
Hi Abhi, as above we need to do some work on the converter used by our scripts to handle RAML 1.0, as soon as this is done I'll try and use your definition as-is.

**Comment by instawell** [comment]
Hey
Oh ok, great! 

If you prefer we could convert to another format you folks love?

**Comment by MikeRalphson** [comment]
As a stop-gap measure that would be great. The 'native' format for the collection is Swagger/OpenAPI 2.0. Thanks.

**Comment by instawell** [comment]
Ok great! Will look into it right away.
Thank you!

**Comment by instawell** [comment]
We are using APIMatic to do the conversion. Would you be able to help us select the best one for your end? I suspect its Swagger 2.0 (JSON)?

**Comment by MikeRalphson** [comment]
Yes, Swagger 2.0 (either JSON or YAML) is fine. Make sure APIMatic doesn't set a default license on the output, it seems to love linking to the grunt project for some reason (bug reported some time ago).

**Comment by instawell** [comment]
https://github.com/instawell/Instawell/blob/master/APIDocs/Instawell_API_Docs.json <https://github.com/instawell/Instawell/blob/master/APIDocs/Instawell_API_Docs.json>

Could you please see if this works?

Thank you
Abhi

**Comment by MikeRalphson** [comment]
Yes, that's valid. Will add from this url.

**Comment by instawell** [comment]
Hey Mike

Check out https://github.com/instawell/Instawell/blob/master/APIDocs/Instawell_API_Docs.json <https://github.com/instawell/Instawell/blob/master/APIDocs/Instawell_API_Docs.json>

Hope all works this time.

Thank you

**Comment by MikeRalphson** [comment]
LGTM!

**Comment by MikeRalphson** [comment]
API deployed. Many thanks again for the submission!

**Comment by instawell** [comment]
thank you!

**Comment by instawell** [comment]
Hey Mike
Quick question

- how do we edit the description of our listed API
- how do we add a link to our name (Instawell) in the listing

Thank you.

**Comment by MikeRalphson** [comment]
Hi. The description comes direct from the OpenAPI document's `info.description` property. You can include raw URLs or use markdown link (`[tag](url)`) syntax.

When our update script runs again, it will pick up your changed definition and pull in the description (and any other changes), re-validate the definition etc etc. Just ping me when it's done and I can update just for your API.
