### ISSUE TITLE
Add "SalesLoft Platform" API

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#330]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developers.salesloft.com/v2_api_def.json
**Name**: SalesLoft Platform

https://twitter.com/SalesLoft

**Comment by MikeRalphson** [comment]
Some validation errors around the oauth security.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution ;)
