### ISSUE TITLE
Add "Adyen Wherever People Pay" API

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#336]
**Format**: Swagger 1.x
**Official**: YES
**Url**: https://www.adyen.com/apidocs/api.json
**Name**: Adyen Wherever People Pay
**Valid**: No (doesn't resolve)
**Twitter**: Adyen

**Comment by MikeRalphson** [comment]
Closing in favour of #392 from contributor / OpenAPI 2.0 & 3.0 definitions.
