### ISSUE TITLE
Add "Syriac Electronic Data Research Archive" API

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#338]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://sedra.bethmardutho.org/api/openapi
**Name**: Syriac Electronic Data Research Archive
**Valid**: No (doesn't resolve)
**Twitter**: bethmardutho

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
