### ISSUE TITLE
Add "Discourse" API

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#339]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: http://docs.discourse.org/openapi.json
**Name**: Discourse
**Valid**: No
**Twitter**: Discourse

**Definition uses example.com as host**
Has `null` descriptions.

**Comment by korovinsrg** [comment]
714552c6148e1617aeab526d0606184b94a80ec048fc09894ff1a72b740c5f19

**Comment by IvanGoncharov** [comment]
@MikeRalphson I think @korovinsrg referring to plain text API key from discourse swagger file.
https://github.com/search?q=714552c6148e1617aeab526d0606184b94a80ec048fc09894ff1a72b740c5f19&type=Code&utf8=%E2%9C%93

> Definition uses example.com as host

Can you fix it with `patch.yaml`?

**Comment by MikeRalphson** [comment]
> Can you fix it with patch.yaml?

Not unless it has a real static host? If it's self-hosted, it would be like adding any other localhost API.

**Comment by IvanGoncharov** [comment]
> Not unless it has a real static host? If it's self-hosted, it would be like adding any other localhost API.

I see 😞

**Comment by MikeRalphson** [comment]
And that's just an example API key surely? Not sure what the issue is supposed to be.

**Comment by IvanGoncharov** [comment]
@MikeRalphson Agreed, just wanted to provide context for @korovinsrg comment

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
