### ISSUE TITLE
Add "XML To JSON Transformation" API

### ISSUE THREAD

**Issue by manjulaRathnayaka** [APIs-guru/openapi-directory#340]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developers.wso2apistore.com/api-docs/manjular-AT-wso2.com-AT-developer/Transform/1.0.0
**Name**: XML To JSON Transformation

**Comment by MikeRalphson** [comment]
Many thanks for the contribution! API added, and congratulations on having a 100% valid definition!
