### ISSUE TITLE
Add "Halo Metadata" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#341]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developer.haloapi.com/docs/services/58ace18c21091812784ce8c5/export?DocumentFormat=Swagger
**Name**: Halo Metadata API

Are APIs marked "public beta" acceptable? Halo API is in beta [since 2015](https://www.halowaypoint.com/en-us/forums/01b3ca58f06c4bd4ad074d8794d2cf86/topics/intro-to-the-halo-public-api/2db2f03a-3d60-4ef7-bff0-e969ecc86509/posts) and appears to have an active community.

**Comment by MikeRalphson** [comment]
Hi @hkosova yes, public beta APIs are fine for inclusion.

Many thanks again for the contribution.
