### ISSUE TITLE
AWS cloudwatch logs API?

### ISSUE THREAD

**Issue by bobby-brennan** [APIs-guru/openapi-directory#346]
I'm looking for the Open API spec that I assumed would be generated from [this spec in aws/aws-sdk-js](https://github.com/aws/aws-sdk-js/blob/4c75cada2893fb833ec2b0d6035f4fb1a4538ca0/apis/logs-2014-03-28.normal.json)

Not seeing it anywhere here though...is it excluded intentionally?

**Comment by MikeRalphson** [comment]
No, not intentionally. It was an over-zealous `.gitignore` rule.

It should be present in the repo now, and in the API when the CI run finishes its deploy.

Sorry about that!

**Comment by bobby-brennan** [comment]
Thanks for the quick fix!
