### ISSUE TITLE
Missing DeleteFunction in AWS lambda

### ISSUE THREAD

**Issue by bobby-brennan** [APIs-guru/openapi-directory#347]
Any idea why this HTTP method didn't make it through to the Open API spec?

https://github.com/aws/aws-sdk-js/blob/master/apis/lambda-2015-03-31.normal.json#L118

**Comment by bobby-brennan** [comment]
Looks like [Add Permission](https://github.com/aws/aws-sdk-js/blob/master/apis/lambda-2015-03-31.normal.json#L12) is missing as well.

**Comment by MikeRalphson** [comment]
Looks like a typo/thinko in `aws2openapi`. CI is running now.

**Comment by MikeRalphson** [comment]
Those operations should be visible now.

**Comment by bobby-brennan** [comment]
Thanks!
