### ISSUE TITLE
API: `preferred` not set for AWS autoscaling

### ISSUE THREAD

**Issue by bobby-brennan** [APIs-guru/openapi-directory#348]
Is this intended? It looks like it's set for `amazonaws.com:application-autoscaling`, but not `amazonaws.com:autoscaling`. Maybe due to a rename?

**Comment by MikeRalphson** [comment]
Fixed setting of preferred flags based on serviceNames extracted from filenames, not `endpointprefix`. Thanks for pointing it out!
