### ISSUE TITLE
Add "Xero" API

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#349]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: ~~https://github.com/XeroAPI/Xero-OpenAPI/blob/master/spec/accounting2.yaml~~
**Url**: https://raw.githubusercontent.com/XeroAPI/Xero-OpenAPI/master/spec/accounting2.yaml
**Name**: Xero
**Valid**: Yes
**Category**: financial
**Twitter**: XeroAPI

**Comment by MikeRalphson** [comment]
API added, many thanks :)
