### ISSUE TITLE
Google: Security Definitions missing (apiKey)

### ISSUE THREAD

**Issue by rbren** [APIs-guru/openapi-directory#35]

**Comment by IvanGoncharov** [comment]
Do you mean it require api key?

**Comment by bobby-brennan** [comment]
I'm not sure how it's supposed to handle auth, but it's a paid API so I
know it uses some kind of auth

Bobby Brennan
bobby.brennan@gmail.com

**Comment by IvanGoncharov** [comment]
@bobby-brennan All Google APIs have this parameter:
https://github.com/APIs-guru/api-models/blob/master/APIs/googleapis.com/translate/v2/swagger.yaml#L40

**Comment by bobby-brennan** [comment]
I'd argue that key and oauth_token should be in security definitions. For
example you have to re-enter your API key in the lucybot console each time
you change operations, but if it's a secdef the console will remember it

Having it as a parameter is sufficient though, especially if it's not an
easy fix

**Comment by IvanGoncharov** [comment]
Problem that I can distinguish between APIs that work with keys and one working without.
So I will add security definition but will make it optional
It's not ideal but definitely step in the right direction.
Sounds good?
