### ISSUE TITLE
Add "Sphere Engine Compilers" API

### ISSUE THREAD

**Issue by kopringo** [APIs-guru/openapi-directory#350]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://sphere-engine.com/static/spec/sec-v3.yml
**Name**: Sphere Engine Compilers
**Valid**: No

**Comment by MikeRalphson** [comment]
Hi @kopringo , thanks for the contribution!

Just a couple of small validation errors to take care of:

* `type: float` should be `type:number, format:float`
* `se_dependency` looks like it should be a specification-extension, i..e `x-se_dependency`

**Comment by kopringo** [comment]
Hi @MikeRalphson, thank you for suggestions. We will fix this soon.

**Comment by MikeRalphson** [comment]
Responding with a `500` status code.

**Comment by MikeRalphson** [comment]
Access to API seems to be behind registration-wall.
