### ISSUE TITLE
Some API definitions references non-existent files

### ISSUE THREAD

**Issue by BigstickCarpet** [APIs-guru/openapi-directory#351]
The [latest Swagger Parser build](https://travis-ci.org/BigstickCarpet/swagger-parser/jobs/314394615#L3937-L3945) failed, and upon investigating the cause, I determined that many of the Microsoft Azure API definitions reference external files that don't exist.  

Here are some examples:

- [Azure Application Gateway API references `networkInterface.json`](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/azure.com/network-applicationGateway/2016-09-01/swagger.yaml#L361)

- [Azure Route Circuit API references `routeFilter.json`](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/azure.com/network-expressRouteCircuit/2016-12-01/swagger.yaml#L833)

- [Azure Network Interface API referneces `loadBalancer.json`](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/azure.com/network-networkInterface/2015-06-15/swagger.yaml#L347)

- [Azure Security Group API references `networkInterface.json`](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/azure.com/network-networkSecurityGroup/2015-06-15/swagger.yaml#L432)

- [Azure Public IP API references `networkInterface.json`](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/azure.com/network-publicIpAddress/2015-06-15/swagger.yaml#L258)

**Comment by MikeRalphson** [comment]
@BigstickCarpet Thanks for letting me know, will take a look to see why the external `$ref`s haven't been resolved.

**Comment by MikeRalphson** [comment]
Hi @BigstickCarpet this *should* be fixed now, but would appreciate your confirmation. For some reason the latest version of `sway` seems to think these are circular references, so needed another option set.

**Comment by MikeRalphson** [comment]
Just investigating `network-networkInterface` definitions. See [this issue](https://github.com/Azure/azure-rest-api-specs/issues/2176).

**Comment by BigstickCarpet** [comment]
I finally got a chance to test this out again today.  A lot of the Azure APIs still reference non-existent files.  For example, all of the following APIs reference `./definitions.json`:

- https://api.apis.guru/v2/specs/azure.com/automation-dscCompilationJob/2015-10-31/swagger.yaml

- https://api.apis.guru/v2/specs/azure.com/automation-job/2015-10-31/swagger.yaml

- https://api.apis.guru/v2/specs/azure.com/automation-runbook/2015-10-31/swagger.yaml

- https://api.apis.guru/v2/specs/azure.com/automation-softwareUpdateConfiguration/2017-05-15-preview/swagger.yaml

- https://api.apis.guru/v2/specs/azure.com/automation-softwareUpdateConfiguration/2017-05-15-preview/swagger.yaml

- https://api.apis.guru/v2/specs/azure.com/automation-softwareUpdateConfigurationMachineRun/2017-05-15-preview/swagger.yaml

**Comment by MikeRalphson** [comment]
@BigstickCarpet @sergey-tihon this has been resolved by a combination of using the latest `sway` in `api-spec-converter` as well as directly in the `openapi-directory` scripts, and removing ~30 Azure API definitions which still failed to resolve completely. Please chase if you see any further problems.
