### ISSUE TITLE
Add "Word Associations Network API" API

### ISSUE THREAD

**Issue by sevyura** [APIs-guru/openapi-directory#357]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.wordassociations.net/documentation/swagger.json
**Name**: Word Associations API
**Valid**: Yes
**Category**: text
**Twitter**: n/a
**Logo**: https://wordassociations.net/en/images/network.png

**Comment by MikeRalphson** [comment]
Many thanks for the contribution, and excellent 100% valid definition!
