### ISSUE TITLE
Add "ClickSend" API

### ISSUE THREAD

**Issue by ewan-clicksend** [APIs-guru/openapi-directory#358]
**Format**: API Blueprint
**Official**: YES
**Url**: ~~http://docs.clicksend.apiary.io/~~
**Url**: https://clicksend.docs.apiary.io/api-description-document
**Name**: ClickSend
**Valid**: Yes
**Twitter**: ClickSendSMS

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. We're investigating some errors in the process of converting your API definition to OpenAPI 2.0. Please bear with us.

**Comment by ewan-clicksend** [comment]
Thanks @MikeRalphson. Is it any help if I try a conversion myself, and fix any errors encountered in our blueprint spec?

**Comment by MikeRalphson** [comment]
That would probably be a great way forward, thanks.

**Comment by MikeRalphson** [comment]
We (finally) have a workaround for the blocking issues.

API added, many thanks for the contribution! Will be live on the site once the CI run finishes.
