### ISSUE TITLE
Add "Marketcheck Cars API" API

### ISSUE THREAD

**Issue by zerebral** [APIs-guru/openapi-directory#359]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://stagingapi.marketcheck.com/api-docs
**Name**: Marketcheck Cars Search API
**Valid**: Yes
**Logo**: https://marketcheck-mccarsapiportal.apigee.io/files/logo.png
**Category**: ecommerce

**Comment by MikeRalphson** [comment]
API added, many thanks!

**Comment by zerebral** [comment]
Thanks @MikeRalphson

**Comment by zerebral** [comment]
@MikeRalphson Could you link the title to http://apidocs.marketcheck.com or http://developer.marketcheck.com please?

**Comment by MikeRalphson** [comment]
Hi @zerebral this link is created directly from the top level `externalDocs.url` property within the OpenAPI definition. If you create this property, I can run our update script to pull it in.

**Comment by zerebral** [comment]
Also if I search for "cars" on the Browse API page it does not show Marketcheck's API. If the title needs correction for this to work then please change it to - "Marketcheck Cars Search API"

**Comment by zerebral** [comment]
@MikeRalphson Added the docs URL - please could you reimport the specs hosted here -
 https://stagingapi.marketcheck.com/api-docs  Thanks.

**Comment by MikeRalphson** [comment]
Link to your externalDocs is now showing on the browse APIs page, and the `serviceName` has been updated to be `marketcheck-cars` so it is found by a search for `car` or `cars`.
