### ISSUE TITLE
Add "Cloudmersive OCR (Optical Character Recognition) API" API

### ISSUE THREAD

**Issue by Cloudmersive** [APIs-guru/openapi-directory#361]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.cloudmersive.com/ocr/docs/v1/swagger
**Name**: Cloudmersive OCR (Optical Character Recognition) API

**Comment by MikeRalphson** [comment]
Added, Many thanks!
