### ISSUE TITLE
Add "Ticketmaster" APIs

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#362]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: 
https://github.com/ticketmaster-api/ticketmaster-api.github.io/blob/dev/_data/orgs/discovery-api/v2/api.json
https://github.com/ticketmaster-api/ticketmaster-api.github.io/blob/dev/_data/orgs/publish-api/v1/api.json
https://github.com/ticketmaster-api/ticketmaster-api.github.io/blob/dev/_data/orgs/commerce-api/v2/api.json
**Name**: Ticketmaster APIs

**Comment by MikeRalphson** [comment]
* https://raw.githubusercontent.com/ticketmaster-api/ticketmaster-api.github.io/dev/_data/orgs/discovery-api/v2/api.json Valid: no
* https://raw.githubusercontent.com/ticketmaster-api/ticketmaster-api.github.io/dev/_data/orgs/publish-api/v1/api.json Valid: no
* https://raw.githubusercontent.com/ticketmaster-api/ticketmaster-api.github.io/dev/_data/orgs/commerce-api/v2/api.json Valid: yes

**Comment by MikeRalphson** [comment]
Added the `commerce` API.

**Comment by MikeRalphson** [comment]
Added the `publish` API. The `discovery` API contains an invalid schema `pattern` value.

**Comment by MikeRalphson** [comment]
Discovery API patched and added.
