### ISSUE TITLE
Add "Envoice" API

### ISSUE THREAD

**Issue by mnikolovski** [APIs-guru/openapi-directory#364]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.envoice.in/docs/api/v1/specification
**Name**: Envoice
**Valid**: Yes
**Twitter**: envoicein
**Category**: financial

**Comment by MikeRalphson** [comment]
Many thanks for the contribution, a nice valid definition! API added.
