### ISSUE TITLE
Add "Kingsalman88" API

### ISSUE THREAD

**Issue by kingsalman88** [APIs-guru/openapi-directory#365]
**Format**: Google API Discovery
**Official**: YES
**Url**: https://www.google.com.sa/webhp?client=ms-android-samsung&source=android-home&gws_rd=cr,ssl&dcr=0&ei=TZBrWurLCsLiUdLLjtgL
**Name**: Kingsalman88

**Comment by MikeRalphson** [comment]
Looks like this has been opened in error. If not, please chase this issue.
