### ISSUE TITLE
Add "Zoom" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#366]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/zoom/api/master/openapi.v2.json
**Name**: Zoom
**Valid**: Yes
**Twitter**: zoom_us
**Category**: telecom

This is a different service than Zoom Connect which is already in this directory.

**Comment by MikeRalphson** [comment]
Thanks for clarifying.

**Comment by MikeRalphson** [comment]
API added, many thanks!
