### ISSUE TITLE
Minimize CDN Usage

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#367]
In the last 6 months hosting cost increased from ~5$ to > 18$ per month and it continues to increase.
Most expenses are from CloudFront and here is daily traffic by object:
![image](https://user-images.githubusercontent.com/8336157/35767419-9e77cf74-08f4-11e8-99ec-4dacb0cfcd04.png)

We can replace those images with something smaller like Twitter profile picture or something.

**Comment by MikeRalphson** [comment]
Will do some work on this during the week ahead.

**Comment by MikeRalphson** [comment]
* Wikipedia logo size:
* Twitter profile (original): 18136 bytes
* Twitter profile (bigger): 2973 bytes
* Twitter profile (normal): 2111 bytes
* Twitter profile (mini): 1556 bytes

**Comment by MikeRalphson** [comment]
I've updated the top 6 images as above, but if you can send me the complete report I will try and amend the remainder of the large ones.

**Comment by IvanGoncharov** [comment]
@MikeRalphson Thank you a lot 👍 
I think those six were responsible for half of traffic, so changing rest is less critical.
![image](https://user-images.githubusercontent.com/8336157/35798212-c393ce30-0a6a-11e8-8072-6f3434a86c3a.png)

**Comment by IvanGoncharov** [comment]
Not relevant anymore since we moved back to GitHub Pages.
