### ISSUE TITLE
Add "OpenUV - Global real-time UV Index Forecast API" API

### ISSUE THREAD

**Issue by aershov24** [APIs-guru/openapi-directory#368]
**Format**: RAML
**Official**: YES
**Url**: https://api.openuv.io/openuv.raml
**Name**: OpenUV - Global real-time UV Index Forecast API

**Comment by MikeRalphson** [comment]
Many thanks for the submission, we're waiting on a PR (https://github.com/mulesoft/oas-raml-converter/pull/19) to our RAML converter, then we should be able to add this API.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
