### ISSUE TITLE
Add "Adafruit IO" API

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#371]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
~~**Url**: https://github.com/adafruit/io-api/blob/gh-pages/v2.json~~
**Url**: https://raw.githubusercontent.com/adafruit/io-api/gh-pages/v2.json
**Name**: Adafruit IO
**Valid**:  Yes (and has logo)
**Category**: iot

**Comment by MikeRalphson** [comment]
API added, thank you very much for your kind contribution! :1st_place_medal:
