### ISSUE TITLE
Add "Who Hosts This API" API

### ISSUE THREAD

**Issue by WhatCMSAdmin** [APIs-guru/openapi-directory#374]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.who-hosts-this.com/API-Specification.json
**Name**: Who Hosts This API
**Valid**: Yes (contains APIs.guru metadata at source)

**Comment by MikeRalphson** [comment]
Thanks very much for the submission, and excellent attention to detail on the APIs.guru metadata!

API added.
