### ISSUE TITLE
Add "WeGA" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#379]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://weber-gesamtausgabe.de/api/v1/swagger.json
**Name**: WeGA (abbreviation for "Carl Maria von Weber Complete Edition")
**Valid**: Yes
Logo: https://weber-gesamtausgabe.de/resources/img/logo_weber.png
Category: open_data

**Comment by MikeRalphson** [comment]
API added, many thanks!
