### ISSUE TITLE
Add "ISBNdb" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#382]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://isbndb.com/modules/isbndb_api_docs/swagger.json
**Name**: ISBNdb
Valid: Yes
Category: open_data
Logo: https://isbndb.com/sites/default/files/ISBN-295x62_4.jpg

**Comment by MikeRalphson** [comment]
API added, many thanks!
