### ISSUE TITLE
Add "Water Linked Underwater GPS" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#383]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://demo.waterlinked.com/swagger/swagger.json
**Name**: The Water Linked Underwater GPS API
Valid: Yes
Twitter: waterlinkedas
Category: location

**Comment by MikeRalphson** [comment]
API added, many thanks!
