### ISSUE TITLE
Add "Storm Glass Marine Weather API" API

### ISSUE THREAD

**Issue by pellepersson** [APIs-guru/openapi-directory#388]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.stormglass.io/specifications/api-specifications.yaml
**Name**: Storm Glass Marine Weather API
**Valid**: Yes
**Logo**: https://stormglass.io/img/logo.png
**Category**: location

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution.
