### ISSUE TITLE
Add "Oh Dear!" API

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/openapi-directory#390]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://ohdearapp.com/swagger.json
**Name**: Oh Dear!
**Twitter**: ohdearapp
**Valid**: No - https://github.com/swagger-api/swagger-ui/issues/4362

Placeholder issue.

**Comment by sssw2** [comment]
😄

**Comment by MikeRalphson** [comment]
Definition no longer available.
