### ISSUE TITLE
Add "Shinobi" API

### ISSUE THREAD

**Issue by RickySan65** [APIs-guru/openapi-directory#396]
**Format**: swagger_2
**Official**: Yes
**Url**: https://api.hillbillysoftware.com/swagger/docs/v1
**Name**: Shinobi
**Valid**: Yes
**Category**: media
**Logo**: https://hillbillysoftware.com/img/logo.png

**Comment by MikeRalphson** [comment]
Thanks for the suggestion. Do you have a link to **machine-readable** documentation for this API?

**Comment by RickySan65** [comment]
There's a swagger link, not sure if that helps
https://api.hillbillysoftware.com/swagger/ui/index

**Comment by MikeRalphson** [comment]
Thanks - that gives us: https://api.hillbillysoftware.com/swagger/docs/v1

**Comment by MikeRalphson** [comment]
Sorry for the delay - we had a few unrelated deployment issues. The API is now in the directory.

Many thanks again.
