### ISSUE TITLE
Move API from AWS to GitHub Pages

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#397]
GitHub now supports custom domains so we can move `api.apis.guru` to gh_pages branch of this repo:
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
Probably makes sense to deploy using Travis:
https://docs.travis-ci.com/user/deployment/pages/

**Comment by IvanGoncharov** [comment]
@MikeRalphson What do you think?

**Comment by MikeRalphson** [comment]
Sounds good. Will have a go at deploying to the `gh_pages` branch first and then look at switching the domain over.

**Comment by bobby-brennan** [comment]
FYI - I usually have an easier time deploying to the `docs/` folder on the master branch. That way you can easily put your build script in package.json

**Comment by MikeRalphson** [comment]
Thanks @bobby-brennan but in this case I think having the deployed APIs  also visible in a `docs/` folder in the main branch would be confusing.

**Comment by MikeRalphson** [comment]
@IvanGoncharov `deploy` dir now pushed to `gh-pages` branch. Is that ok, or does it need to live inside a 'v2` subdirectory?

**Comment by IvanGoncharov** [comment]
@MikeRalphson Without `v2` it would be a breaking change. Plus versioning allows you to switch JSON format, e.g. provide only OAS3 urls.

**Comment by MikeRalphson** [comment]
@IvanGoncharov I wasn't querying the need for `/v2/` in the current paths, I was trying to ask which files/directories in the current `deploy` directory / root of `gh-pages` need to be under `v2`?

**Comment by IvanGoncharov** [comment]
Same as S3 all content of `deploy` dir:
![image](https://user-images.githubusercontent.com/8336157/39767200-d99fbe38-52ee-11e8-9a6e-6cd863196572.png)

![image](https://user-images.githubusercontent.com/8336157/39767168-bfcf29b2-52ee-11e8-92ee-60337d9c4087.png)

**Comment by MikeRalphson** [comment]
Directory structure of `gh-pages` branch should be OK now.

**Comment by bobby-brennan** [comment]
FYI - I think you'll need a proxy like CloudFlare or AWS CloudFront to maintain support for HTTPS

[relevant issue](https://github.com/isaacs/github/issues/156)

**Comment by MikeRalphson** [comment]
@bbrennan isn't that exactly the issue addressed by the blog posting Ivan linked to initially (https://blog.github.com/2018-05-01-github-pages-custom-domains-https/)? One person who needed www. support as well should not block us.

**Comment by bobby-brennan** [comment]
Oh nice! I missed that, thanks

**Comment by IvanGoncharov** [comment]
Migration completed a few weeks ago ⏳ 
Everything is working 👍
