### ISSUE TITLE
Add "Mastercard" API

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#398]
Reported by @darklynx
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://developer.mastercard.com/devzone/api/portal/apis
**Name**: Mastercard

Example specs:
https://developer.mastercard.com/devzone/api/portal/swagger/masterpass-merchant-integration-v7 (Swagger 2)
https://developer.mastercard.com/devzone/api/portal/servicespec/masterpasscheckoutv7/swaggerui (OpenAPI ver. 3)

SwaggerUI:
https://developer.mastercard.com/swagger/masterpasscheckoutv7

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
