### ISSUE TITLE
Add "redirection.io" API

### ISSUE THREAD

**Issue by xavierlacot** [APIs-guru/openapi-directory#401]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: Yes
**Url**: https://api.redirection.io/docs.json
**Name**: redirection.io
**Valid**: Yes
**Category**: hosting
**Twitter**: redirectionio

**Comment by MikeRalphson** [comment]
Could you check your API definition validates?

```
Swagger schema validation failed. 
  Missing required property: responses at #/paths//organizations/get
```

I would link to an online validator but your API definition does not appear to be hosted with CORS enabled.

Thanks.

**Comment by xavierlacot** [comment]
Hi @MikeRalphson, the issues have been fixed.

**Comment by MikeRalphson** [comment]
API added, many thanks!
