### ISSUE TITLE
Add "MakCorps-Hotel Price comparison API" API

### ISSUE THREAD

**Issue by manthankool** [APIs-guru/openapi-directory#403]
**Format**: I/O Docs
**Official**: YES
**Url**: https://www.makcorps.com/
**Name**: MakCorps-Hotel Price comparison API

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, WADL, Google Discovery format etc)? Without this we cannot add the API to the directory.

**Comment by MikeRalphson** [comment]
As above, the API description needs to be in a *machine-readable* format, such as OpenAPI, RAML, API Blueprint, WADL, or Google Discovery format. Without this, we cannot add your API to the directory.
