### ISSUE TITLE
Add "Daymet Single Pixel Tool" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#405]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://daymet.ornl.gov/single-pixel/static/swagger.json
**Name**: Daymet Single Pixel Tool
**Category**: location (weather)
**Valid**: Yes
**Twitter**: NASAEarthData

**Comment by MikeRalphson** [comment]
API added, many thanks!
