### ISSUE TITLE
Add "Enterobase" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#406]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://enterobase.warwick.ac.uk/api/v2.0/swagger
**Name**: Enterobase
**Valid**: Yes
**Host**: Relative
**Logo**: https://logo-core.clearbit.com/enterobase.warwick.ac.uk/
**Category**: open_data

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
