### ISSUE TITLE
Add "Call Control" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#410]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.callcontrol.com/js/swagger/swagger.json
**Name**: Call Control
**Valid**: Yes
**Category**: telecom
**Twitter**: n/a ?
**Logo**: https://www.callcontrol.com/images/logo.svg

**Comment by MikeRalphson** [comment]
API added, many thanks!
