### ISSUE TITLE
Add "EVEMarketer Marketstat" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#411]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.evemarketer.com/ec/swagger.yaml
**Name**: EVEMarketer Marketstat
**Twitter**: EVEMarketer
**Valid**: Yes
**Category**: entertainment

**Comment by MikeRalphson** [comment]
API added, many thanks!
