### ISSUE TITLE
Add "Setlist.fm" API

### ISSUE THREAD

**Issue by zbrox** [APIs-guru/openapi-directory#413]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.setlist.fm/docs/1.0/ui/swagger.json
**Name**: Setlist.fm
**Valid**: Yes
**Host**: Relative
**Twitter**: setlistfm
**Category**: media

**Comment by MikeRalphson** [comment]
Thanks for the contribution @zbrox - could I just confirm if the API's host is as per the source of the OpenAPI definition (`api.setlist.fm`) or whether it is intended/possible to host setlist.fm on your own server?

**Comment by zbrox** [comment]
@MikeRalphson Unfortunately the service cannot be self hosted.

**Comment by MikeRalphson** [comment]
No problem, it was just a question of knowing what to set the `host` property to once the API is added to the directory - we can't use a relative host otherwise it would appear that `raw.githubusercontent.com` or `apis.guru` was intended to be the API host.

**Comment by MikeRalphson** [comment]
Note: also patched up empty `schemes` array with value `https`.

**Comment by MikeRalphson** [comment]
API added, many thanks!
