### ISSUE TITLE
Add "Otoroshi Admin" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#417]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/MAIF/otoroshi/master/docs/manual/code/swagger.json
**Name**: Otoroshi Admin API
**Valid**: Yes
**Logo**: https://maif.github.io/otoroshi/assets/images/svg/otoroshi_logo.svg

Treated as a relative-host API as host set to `foo.bar`.

**Comment by MikeRalphson** [comment]
API added, many thanks!
