### ISSUE TITLE
Add "Crossbrowsertesting.com Screenshot Comparisons" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#418]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://crossbrowsertesting.com/apidocs/definitions/screenshot-comparisons.json
**Name**: Crossbrowsertesting.com Screenshot Comparisons
**Valid**: Yes
**Category**: developer_tools
**Twitter**: xbrowsertesting

**Comment by MikeRalphson** [comment]
Many thanks again!
