### ISSUE TITLE
Add "Musixmatch" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#420]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/musixmatch/musixmatch-sdk/master/swagger/swagger.yaml
**Name**: Musixmatch
**Valid**: Yes
**Twitter**: Musixmatch

**Comment by MikeRalphson** [comment]
Many thanks!
