### ISSUE TITLE
Add "Bandsintown" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#421]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.swaggerhub.com/apis/Bandsintown/PublicAPI/3.0.0/swagger.yaml
**Name**: Bandsintown
**Valid**: Yes
**Category**: social
**Twitter**: Bandsintown

**Comment by MikeRalphson** [comment]
Many thanks!
