### ISSUE TITLE
Submit to Awesome Public Datasets

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#422]
https://github.com/awesomedata/awesome-public-datasets
https://github.com/awesomedata/apd-core/wiki/HOW_TO_CONTRIBUTE-%E5%A6%82%E4%BD%95%E8%B4%A1%E7%8C%AE

**Comment by MikeRalphson** [comment]
Do you think our dynamic nature meets the definition of a dataset?
