### ISSUE TITLE
Add "Request Baskets" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#424]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/darklynx/request-baskets/master/doc/api-swagger.yaml
**Name**: Request Baskets
**Valid**: Yes
**Logo**: present
**Category**: developer_tools

**Comment by MikeRalphson** [comment]
API added, many thanks!
