### ISSUE TITLE
Add Zenoti API

### ISSUE THREAD

**Issue by bobby-brennan** [APIs-guru/openapi-directory#425]
**Format**: swagger_2
**Valid**: Yes
**Twitter**: ZenotiSoftware
**Category**: customer_relation

Here are the docs: https://zenotiopenapi.docs.apiary.io/

Here's the spec: https://zenotiopenapi.docs.apiary.io/api-description-document

I can't find a list of users of docs.apiary.io, but this might be a great source of new specs:

https://www.google.com/search?q=site%3Adocs.apiary.io

**Comment by MikeRalphson** [comment]
API added, many thanks! (CI pending)
