### ISSUE TITLE
Add "BioLink API" API

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#426]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.monarchinitiative.org/api/swagger.json
**Name**: BioLink API
**Valid**: No - has duplicate tags for instance

https://github.com/biolink/biolink-api

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
