### ISSUE TITLE
Add "Poemist" API

### ISSUE THREAD

**Issue by sezginriggs** [APIs-guru/openapi-directory#427]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.poemist.com/api-docs.json
**Name**: Poemist
**Twitter**: poemistcom / has logo

**Comment by MikeRalphson** [comment]
Hi, thanks for the contribution. Your `responses: 200` object is missing a mandatory `description` property. Could you add it? `OK` is fine.

**Comment by sezginriggs** [comment]
Hello @MikeRalphson 
Can you check again please? I think it should be okay now.

**Comment by MikeRalphson** [comment]
@sezginriggs looks great now, thanks!

**Comment by MikeRalphson** [comment]
Oh - I've just noticed, you have `/api/v1` in both your `basePath` and `pathItem` entry. Unless your api is actually accessed at `/api/v1/api/v1/randompoems`, this looks wrong. Probably the `paths` entry should be just `/randompoems` (as the `basePath` gets prepended).

**Comment by sezginriggs** [comment]
@MikeRalphson thank you very much, fixed this also! It should be okay now.

**Comment by sezginriggs** [comment]
@MikeRalphson I think I can improve the "info". Can you wait for a while before adding it please? I'll make changes in a hour.

**Comment by MikeRalphson** [comment]
@sezginriggs no problem - just ping me when ready.

**Comment by MikeRalphson** [comment]
BTW - any changes you make subsequently will be picked up automatically by our update scripts, but yes, a more complete `info` section will help the display/discoverability of your API.

**Comment by sezginriggs** [comment]
@MikeRalphson I think it's complete now :)

**Comment by sezginriggs** [comment]
@MikeRalphson it's labeled with "waiting for response". Do you need anything from my side?

**Comment by MikeRalphson** [comment]
No, that was just to remind me to hold off. Will add shortly.

**Comment by MikeRalphson** [comment]
API added, many thanks!
