### ISSUE TITLE
Add "api.video" API

### ISSUE THREAD

**Issue by apivideo** [APIs-guru/openapi-directory#429]
**Format**: RAML
**Official**: YES
**Url**: https://docs.api.video/5.1/introduction/api-conventions
**Name**: api.video
**Valid**: No (RAML) / No (OAS)

**Comment by MikeRalphson** [comment]
Note to self: OAS link: https://api.stoplight.io/v1/versions/9SNHChS5XhqPTQJCe/export/oas.json - though will that reflect changes? RAML version is 0.8 and has a similar export link.

**Comment by MikeRalphson** [comment]
https://docs.api.video/openapi/5f0d4679158b8d006ea6f068

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
