### ISSUE TITLE
Add "FraudLabs Pro Fraud Detection" API

### ISSUE THREAD

**Issue by chrislim2888** [APIs-guru/openapi-directory#430]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://app.swaggerhub.com/apis/fraudlabspro/fraudlabspro-fraud-detection/1.0
**Name**: FraudLabs Pro Fraud Detection
**Valid**: Yes
**Category**: ecommerce
**Twitter**: fraudlabspro

**Comment by MikeRalphson** [comment]
Note to self: think we need to do a little work on filtering out SwaggerHub's virtserver from the `servers` array before we can add this.

**Comment by chrislim2888** [comment]
If I uploaded the json format into my server at https://www.fraudlabspro.com/openapi/fraudlabspro-fraud-detection_1.0_swagger.json, will that ease the processing.

**Comment by MikeRalphson** [comment]
@chrislim2888 the location itself isn't really the issue (and in fact a static URL **without** a version number in it is better for us to keep your definition up-to-date).

Your `servers` array looks like this

```yaml
  "servers": [
    {
      "description": "SwaggerHub API Auto Mocking",
      "url": "https://virtserver.swaggerhub.com/fraudlabspro/fraudlabspro/1.0"
    },
    {
      "url": "https://api.fraudlabspro.com"
    }
  ],
```

and we just need to amend our scripts to skip the `virtserver.swaggerhub.com` entry and use the `api.fraudlabspro.com` entry for the purposes of naming your API in the directory.

Alternatively, I don't know if you would be able to re-order those two server entries without causing any problems for you testing your API?

**Comment by chrislim2888** [comment]
Thanks for pointing this out. Sure, I have reserved the server order, can you please check if this will works for your side?

Please let me know if any fixes still required.

https://app.swaggerhub.com/apis/fraudlabspro/fraudlabspro-fraud-detection/1.1

**Comment by MikeRalphson** [comment]
API added, many thanks!
