### ISSUE TITLE
Feature Request: 2.0 vs 3.0 field in list.json

### ISSUE THREAD

**Issue by rbren** [APIs-guru/openapi-directory#434]
Minor nit:

I'm working on pulling the latest and downconverting the 3.0 specs to 2.0. Looking at list.json it wasn't clear how to distinguish the two (I thought about using `x-origin` but that won't work when we're converting RAML to OAI3). Eventually found a Gitter message that says 3.0 filenames are `openapi.json` and 2.0 is `swagger.json`

I'd consider adding an `openapi_version` field so the list is self-documenting.

**Comment by MikeRalphson** [comment]
With the pending release of OpenAPI 3.1 this will become an issue. Prioritising.

**Comment by MikeRalphson** [comment]
The `list.json` endpoint now includes an `openapiVer` property, containing the value of the `openapi` or `swagger` fields from each definition.
