### ISSUE TITLE
Add "FraudLabs Pro SMS Verification" API

### ISSUE THREAD

**Issue by fraudlabspro** [APIs-guru/openapi-directory#435]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://app.swaggerhub.com/apis/fraudlabs-pro/fraudlabspro-sms-verification/1.0
**Url**: https://app.swaggerhub.com/apiproxy/schema/file/fraudlabs-pro/fraudlabspro-sms-verification/1.0/swagger.json
**Name**: FraudLabs Pro SMS Verification

**Comment by MikeRalphson** [comment]
Hi @fraudlabspro - we will need to move your other API slightly to give it a `service` identifier to distinguish it from your SMS Verification API. What would be a good id for the other API?

**Comment by fraudlabspro** [comment]
fraudlabspro-sms-verification

**Comment by MikeRalphson** [comment]
For the **other** API?

**Comment by hkosova** [comment]
@MikeRalphson this is the same API, the 1st link just points to the API docs.

For the definition link, consider using
https://api.swaggerhub.com/apis/fraudlabs-pro/fraudlabspro-sms-verification/1.0/swagger.yaml
(note `https://api...` instead of `.../apiproxy/schema/file`)

**Comment by fraudlabspro** [comment]
Please use https://app.swaggerhub.com/apis/fraudlabs-pro/fraudlabspro-sms-verification/1.0
Thank you.

**Comment by MikeRalphson** [comment]
? That is the same URL you posted originally.

What we need is a one or two word indicator which describes what the difference is between this API (the SMS verification one) and the first API you submitted - this will allow us to have both your APIs under the `fraudlabs-pro` directory in the collection.

So - for complete clarity - would it be ok to use `detection` for the first API you submitted (in issue #430) and `verification` or `sms-verification` for this one?

**Comment by fraudlabspro** [comment]
Yes. 
#430 remain as fraudlabspro-fraud-detection
#435 use fraudlabspro-sms-verifcation

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! Apologies for the delay.
