### ISSUE TITLE
Add "Image Moderation" API

### ISSUE THREAD

**Issue by ModerateContent** [APIs-guru/openapi-directory#443]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.moderatecontent.com/api/swagger.yaml
**Name**: Image Moderation
**Valid**: Yes
**Category**: media
**Twitter**: No
**Logo**: https://www.moderatecontent.com/img/moderate_content_com_logo.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
