### ISSUE TITLE
Directory UI 

### ISSUE THREAD

**Issue by macarlet** [APIs-guru/openapi-directory#444]
Hi, I want to kindly ask If there is a web UI that can be deployed on an hosted machine in order to have a private catalog.
Thank you

**Comment by MikeRalphson** [comment]
You could adapt https://github.com/APIs-guru/APIs-guru.github.io though it isn't a 'white-box' solution.

This is the code behind https://apis.guru/browse-apis/

**Comment by macarlet** [comment]
thanks @MikeRalphson

**Comment by MikeRalphson** [comment]
No problem, let me know if you need anything further.
