### ISSUE TITLE
Add "ID4i" API

### ISSUE THREAD

**Issue by wwerner** [APIs-guru/openapi-directory#445]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://backend.id4i.de/docs/swagger.json
**Name**: ID4i

**Comment by MikeRalphson** [comment]
Could you check your definition for validation errors, e.g.

```text
Swagger schema validation failed. 
  Additional properties not allowed: allowEmptyValue at #/definitions/WhoIsResponse/properties/organizationAddress/properties/telephone
```

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
