### ISSUE TITLE
Add "Api2Pdf" API

### ISSUE THREAD

**Issue by apexdodge** [APIs-guru/openapi-directory#446]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://app.swaggerhub.com/apiproxy/schema/file/api2pdf/api2pdf/1.0.0/swagger.json
**Name**: Api2Pdf

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! Apologies I didn't close this back in January.
