### ISSUE TITLE
Add "Currency Authority: Exchange Rate of 1453 country currencies and crypto currencies" API

### ISSUE THREAD

**Issue by lx4241** [APIs-guru/openapi-directory#447]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**:https://sonar.trading/docs/api-docs.json ~~https://sonar.trading/api/~~
**Name**: Currency Authority: Exchange Rate of 1453 country currencies and crypto currencies
**Valid**: Yes
**Category**: financial
**Twitter**: tradingsonar

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
