### ISSUE TITLE
Add "Climate FieldView Platform" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#449]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://dev.fieldview.com/openapi/platform.yaml
**Name**: Climate FieldView Platform
**Valid**: No - missing scopes (anything else?)

**Comment by MikeRalphson** [comment]
We now have an option to ignore 'missing' top-level scopes.

API added, many thanks for the contribution!
