### ISSUE TITLE
EPS APIs

### ISSUE THREAD

**Issue by darosh** [APIs-guru/openapi-directory#45]
- is actually list of Swagger 2.0 APIs http://epscass.prd-prsn.com/api/institution for example http://eps.openclass.com/india/api/
- on the other hand: **OpenClass will retire on January 1, 2018** pasted from http://www.pearsonhighered.com/openclass/
- this page should contain list of their API stack but it is hacked: http://code.pearson.com/open-class

**Comment by IvanGoncharov** [comment]
@darosh Cool. Thank you for researching it. :+1: 
Right now I'm in the middle of refactoring, basically paying longstanding technical depth :(
One of the features will be pluggable spec sources. So you can create a separate file with one function which return a list of URLs to spec + patches(to provide data missing in Swagger itself).
The list that you found is a candidate for adding.

**Comment by IvanGoncharov** [comment]
@darosh as for retired API there is nothing I can do except adding this information into `description`.
In future, we create some vendor extension for such dates(something like `x-retireDate`).

**Comment by IvanGoncharov** [comment]
> is actually list of Swagger 2.0 APIs http://epscass.prd-prsn.com/api/institution for example http://eps.openclass.com/india/api/

@darosh APIs.guru now supports  pluggable spec sources.
So technically it's easy to add it, but it looks like its different instances of the same API. Right?
And in general, do you think this APIs could be useful to somebody?

**Comment by darosh** [comment]
@IvanGoncharov 

> So technically it's easy to add it, but it looks like its different instances of the same API. Right?

It looks like, but I checked just 4 of them.

> And in general, do you think this APIs could be useful to somebody?

In general, based on my experience, developers/researchers may be interested not only in particular API and/or its instance but also in similar area the API solves for inspiration etc. This case looks like [LMS](https://en.wikipedia.org/wiki/Learning_management_system) which is pretty interesting topic for schools and companies ... from this "general" point of view it is interesting sometimes to see retired/outdated APIs too.

**Comment by IvanGoncharov** [comment]
@darosh Thank you for a response.
It definitely something to consider in the future.
But until someone will show practical interest in those APIs I don't think it worth investing time.

**Comment by MikeRalphson** [comment]
Closing as above.
