### ISSUE TITLE
Add "Fortnite" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#457]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: NO
**Url**: https://raw.githubusercontent.com/SkYNewZ/rest-fornite-api/develop/src/public/swagger.yaml
**Name**: Fortnite
**Category**: entertainment
**Twitter**: FortniteGame

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
