### ISSUE TITLE
Add "TomTom Online Maps" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#458]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: <s>https://developer.tomtom.com/system/files/swagger_models/online_maps.yaml</s>
https://developer.tomtom.com/system/files/swagger_models/maps_api_0.yaml
**Name**: TomTom Online Maps

**Comment by hkosova** [comment]
Updated the file link.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
