### ISSUE TITLE
Support for Oauth 1.0

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#46]
Suggested by @sanchojaf on Gitter:

> we know OAuth 1.0 is not supported by Swagger 2.0, is possible and make sense add to `patch.yaml` ?

**Comment by maryguirola** [comment]
Hi, these collections use OAuth 1.0 authentication:
1. thenounproject 
2. audiosear.ch
3. slideroom

**Comment by IvanGoncharov** [comment]
@maryguirola Thank you. It's very helpful.

**Comment by maryguirola** [comment]
@IvanGoncharov  You're welcome.

**Comment by MikeRalphson** [comment]
@maryguirola One possible way to represent oAuth1 is to declare a securityDefinition of:

```json
{
"type": "apiKey",
"in": "header",
"name": "Authorization",
"description": "oAuth1"
}
````

It would be up to the client to negotiate oAuth1 and build the `Authorization` header 'manually'. I'm thinking of doing something similar for Amazon AWS's HMAC security scheme.

**Comment by MikeRalphson** [comment]
See https://github.com/OAI/OpenAPI-Specification/issues/61
