### ISSUE TITLE
Add "TomTom Online Search" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#460]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: <s>https://developer.tomtom.com/system/files/swagger_models/online_search.yaml</s>
https://developer.tomtom.com/system/files/swagger_models/search_api.yaml
**Name**: TomTom Online Search

**Comment by MikeRalphson** [comment]
Url (now?) seems to require login. :cry:

**Comment by hkosova** [comment]
The current link is https://developer.tomtom.com/system/files/swagger_models/search_api.yaml

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
