### ISSUE TITLE
Add "OpenLink Smart Data Bot (OSDB)" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#461]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://osdb.openlinksw.com/osdb/osdb_rest_api.openapi.json
**Name**: OpenLink Smart Data Bot (OSDB)
**Valid**: Yes
**Twitter**: OpenLink
**Category**: developer_tools

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
