### ISSUE TITLE
Add "groov Public API"

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#462]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://developer.opto22.com/static/generated/groov-rest-api/swagger.yaml
**Name**: groov Public API
**Valid**: Yes
**Host**: Relative
**Twitter**: opto22
**Category**: iot

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
