### ISSUE TITLE
Add "OpenTrials" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#464]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/opentrials/api/master/api/swagger/swagger.yaml
**Name**: OpenTrials
**Valid**: Yes
**Host**: Relative
**Logo**: https://avatars1.githubusercontent.com/u/13900836?s=200&v=4
**Category**: open_data

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
