### ISSUE TITLE
Add "Global Wine Score API" API

### ISSUE THREAD

**Issue by globalwinescore** [APIs-guru/openapi-directory#468]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: ~~https://globalwinescore.docs.apiary.io/#~~
**Url**: https://globalwinescore.docs.apiary.io/api-description-document
**Name**: Global Wine Score API

**Comment by MikeRalphson** [comment]
Is this a dupe/update of #467 ?

**Comment by globalwinescore** [comment]
yes this is a dupe of 467

**Comment by MikeRalphson** [comment]
Closing in favour of #467
