### ISSUE TITLE
Add "trash nothing!" API

### ISSUE THREAD

**Issue by scyclops** [APIs-guru/openapi-directory#474]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://trashnothing.com/api/trashnothing-openapi.yaml
**Name**: trash nothing!
**Valid**: Yes
**Twitter**: trashnothing
**Category**: social

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! Sorry - I should have closed this issue when I resolved the breaking build. Apologies.
