### ISSUE TITLE
Add "TisaneAPI" API

### ISSUE THREAD

**Issue by cheng-zuo** [APIs-guru/openapi-directory#479]
**Format**: Swagger 1.x
**Official**: YES
**Url**: https://dev.tisane.ai/docs/services/5a3b6668a3511b11cc292655/export?DocumentFormat=Swagger
**Name**: TisaneAPI
**Valid**: No

**Comment by MikeRalphson** [comment]
Hi, thanks for the contribution!

Could you look at the following validation errors please?

https://online.swagger.io/validator/debug?url=https%3A%2F%2Fdev.tisane.ai%2Fdocs%2Fservices%2F5a3b6668a3511b11cc292655%2Fexport%3FDocumentFormat%3DSwagger

**Comment by MikeRalphson** [comment]
Was actually added in #528
