### ISSUE TITLE
Add "Rig Veda API" API

### ISSUE THREAD

**Issue by AninditaBasu** [APIs-guru/openapi-directory#480]
**Format**: Swagger 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/AninditaBasu/indica/master/rv_SDKs/rv.yaml
**Name**: Rig Veda API
**Valid**: Yes

**Comment by MikeRalphson** [comment]
Same as issue #481

**Comment by AninditaBasu** [comment]
Hi Mike,
Sorry for the delayed response. The URL has now changed to https://sheetlabs.com/IND/rv

**Comment by MikeRalphson** [comment]
Still same issue as #481

**Comment by AninditaBasu** [comment]
@MikeRalphson  Is this a valid file for definition: https://github.com/AninditaBasu/indica/blob/master/rv_SDKs/rv.yaml ?

**Comment by MikeRalphson** [comment]
Yes, again, that's what we needed, and is 100% valid!

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
