### ISSUE TITLE
Add "Vedic Society API" API

### ISSUE THREAD

**Issue by AninditaBasu** [APIs-guru/openapi-directory#481]
**Format**: Swagger 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/AninditaBasu/indica/master/vs_SDKs/vs.yaml
**Name**: Vedic Society API

**Comment by MikeRalphson** [comment]
Hi, thanks for the contribution. When I visit that URL, I get

```json
{
    "errormsg": "Web service not found",
    "errorcode": 404
}
```

**Comment by AninditaBasu** [comment]
Hi Mike,
Sorry for the delayed response. The URL has now changed to https://sheetlabs.com/IND/vs

**Comment by MikeRalphson** [comment]
@AninditaBasu that doesn't seem to be a Swagger/OpenAPI definition...

**Comment by AninditaBasu** [comment]
um, can this be called a Swagger definition: https://github.com/AninditaBasu/indica/blob/master/vs_SDKs/vs.yaml

(sorry, not a coder so not really sure...)

**Comment by MikeRalphson** [comment]
Yes, that's absolutely great, thanks.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
