### ISSUE TITLE
Update NPR One APIs

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#482]
The API definition from #280 is no longer available on the NPR One site.

NPR One currently provides the following (valid) API definitions:

NPR Authorization Service: https://authorization.api.npr.org/v2/swagger.json
NPR Listening Service: https://listening.api.npr.org/v2/swagger.json
NPR Station Finder Service: https://station.api.npr.org/v3/swagger.json
NPR Sponsorship Service: https://sponsorship.api.npr.org/v2/swagger.json

**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Twitter**: NPR
**Category**: entertainment

**Comment by MikeRalphson** [comment]
Thanks! Apologies for the delay in adding new APIs.

**Comment by MikeRalphson** [comment]
APIs (+ identity) added. Many thanks as usual.
