### ISSUE TITLE
Add "Hydra Movies" API

### ISSUE THREAD

**Issue by Kay-Tan** [APIs-guru/openapi-directory#483]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://hydramovies.com/api-v2/swagger.yaml
**Name**: Hydra Movies
**Valid**: Yes
**Category**: entertainment

**Comment by MikeRalphson** [comment]
Please be advised that although this API meets our current submission guidelines, if we receive a single report of malware being linked to by this API, it will be removed.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
