### ISSUE TITLE
Add "megaventory" API

### ISSUE THREAD

**Issue by ellieAn** [APIs-guru/openapi-directory#484]
**Format**: Swagger 1.x
**Official**: YES
**Url**: https://api.megaventory.com
**Name**: megaventory

**Comment by ellieAn** [comment]
Hello there,

will something like this suffice? https://api.megaventory.com/v2017a/soap12

**Comment by MikeRalphson** [comment]
No, I'm sorry, but at the moment we do not support SOAP web-services.
