### ISSUE TITLE
Add "OpenFIGI" API

### ISSUE THREAD

**Issue by Narvey** [APIs-guru/openapi-directory#487]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.openfigi.com/schema
**Name**: OpenFIGI

Just don't hit the /schema endpoint too often unauthenticated or you will hit their rate limit.

**Comment by MikeRalphson** [comment]
Valid: No (? - `default` used against a `oneOf`, where it looks as if they are trying to indicate which one of the allowed **types** is the default, not what the default **value** actually is.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
