### ISSUE TITLE
Add "Geodatasource Location Search API" API

### ISSUE THREAD

**Issue by geodatasource** [APIs-guru/openapi-directory#488]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://app.swaggerhub.com/apiproxy/schema/file/geodatasource/geodatasource-location-search/1.0/swagger.yaml
**Name**: Geodatasource Location Search API

**Comment by MikeRalphson** [comment]
Need link to actual JSON / YAML file (possibly from swaggerhub's API?) - if you can provide that it will be a great help, otherwise I'll try and dig it out...

**Comment by geodatasource** [comment]
Here you go, thanks.
https://app.swaggerhub.com/apis/geodatasource/geodatasource-location-search/1.0

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! Apologies I didn't close this back in January.
