### ISSUE TITLE
Error in authorization type in Trello spec

### ISSUE THREAD

**Issue by maryguirola** [APIs-guru/openapi-directory#49]
Hi, @IvanGoncharov, I found that Trello's API uses OAuth 1 authentication. The spec says is type oauth2

**Comment by IvanGoncharov** [comment]
Hi @maryguirola,
I did quick search on Trello API portal.
And I didn't found reference to Oauth1 or Oauth2.
Could you please post such link?

**Comment by maryguirola** [comment]
Sorry, I forgot it... https://developers.trello.com/authorize

**Comment by IvanGoncharov** [comment]
@maryguirola Thank you.
I will take a look and think about what to do.
Will try to came up with a solution on next week.

By the way, could please specify the priority of the issue, something simple like: `it's blocking us`, `important  but we can wait`, etc.
It will help me to prioritise my work.

**Comment by MikeRalphson** [comment]
Hi @maryguirola I believe this has been fixed as best as it can be [here](https://github.com/APIs-guru/unofficial_openapi_specs/issues/11). Please chase if you think we should represent oAuth 1 differently.
