### ISSUE TITLE
Add "Reloadly Mobile Top Up" API

### ISSUE THREAD

**Issue by Reloadly** [APIs-guru/openapi-directory#490]
**Format**: API Blueprint
**Official**: YES
**Url**: ~~https://topupsapi.docs.apiary.io/#~~
**Url**: https://topupsapi.docs.apiary.io/api-description-document
**Name**: Reloadly API
**Valid**: Yes
**Category**: ecommerce
**Twitter**: Reloadly

**Comment by Reloadly** [comment]
The Reloadly Mobile Top Up REST API uses the OAuth 2.0 protocol to authorize calls. OAuth is an open standard that many companies use to provide secure access to protected resources.When you create a developer account. Reloadly generates a set of OAuth client ID and secret credentials for your app for both sandbox and live environments. You pass these credentials in the Authorization header in the get access token request.In exchange for these credentials, the Reloadly authorization server issues access tokens called bearer tokens that you use for authorization when you make REST API requests. A bearer token enables you to complete actions on behalf of, and with the approval of the resource owner.The access_token field in the get access token response contains a bearer token, indicated by the token_type of Bearer

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
