### ISSUE TITLE
Add "MailboxValidator Disposable Email Checker" API

### ISSUE THREAD

**Issue by MailboxValidator** [APIs-guru/openapi-directory#492]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://app.swaggerhub.com/apis/mailboxvalidator/MailboxValidator-Disposable-Email-Checker/1.0.0
**Name**: MailboxValidator Disposable Email Checker

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
