### ISSUE TITLE
Add "MailboxValidator Free Email Checker" API

### ISSUE THREAD

**Issue by MailboxValidator** [APIs-guru/openapi-directory#493]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://app.swaggerhub.com/apis/mailboxvalidator/MailboxValidator-Free-Email-Checker/1.0.0
**Name**: MailboxValidator Free Email Checker

**Comment by hkosova** [comment]
@MikeRalphson To get the raw file URL from SwaggerHub, replace `APP.swaggerhub.com` with `API.swaggerhub.com`. This will give you JSON.
https://api.swaggerhub.com/apis/mailboxvalidator/MailboxValidator-Free-Email-Checker/1.0.0

If you want YAML, add `/swagger.yaml` at the end:
https://api.swaggerhub.com/apis/mailboxvalidator/MailboxValidator-Free-Email-Checker/1.0.0/swagger.yaml

**Comment by MikeRalphson** [comment]
Thanks @hkosova - that's really helpful.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
