### ISSUE TITLE
Add "Sentiment Analysis Api" API

### ISSUE THREAD

**Issue by proxmedia** [APIs-guru/openapi-directory#496]
**Format**: Swagger 2.0
**Official**: YES
**Url**: ~~https://text2data.org/Integration~~
**Url**: http://api.text2data.org/swagger/docs/v3.1
**Name**: Sentiment Analysis Api
**Valid**: Yes
**Category**: text
**Twitter**: Text2Data

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, WADL, Google Discovery format etc)? Without this unfortunately we cannot add the API to the directory.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
