### ISSUE TITLE
Add "obono.at RKSV API" API

### ISSUE THREAD

**Issue by pgaubatz** [APIs-guru/openapi-directory#500]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://app.obono.at/api/docs/api.yml
**Name**: obono.at RKSV API
**Valid**: Yes
**Host**: Relative
**Twitter**: obono_at

**Comment by MikeRalphson** [comment]
Hi @pgaubatz thanks for the submission. I note there is no `host` in the swagger YAML file. In that case, does it mean that the API endpoint is relative to `app.obobo.at` or that the API can be self-hosted?

**Comment by pgaubatz** [comment]
Hi @MikeRalphson!
All endpoints are relative to `app.obobo.at` and the API can not be self-hosted... :)
Thanks!

**Comment by MikeRalphson** [comment]
@pgaubatz Thanks for the confirmation.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
