### ISSUE TITLE
Add "Football Prediction API" API

### ISSUE THREAD

**Issue by boggio-analytics** [APIs-guru/openapi-directory#501]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://boggio-analytics.com/fp-api/schema/football-prediction-openapi.yaml
**Name**: Football Prediction API
**Valid**: Yes
**Category**: analytics
**Logo**: https://logo-core.clearbit.com/boggio-analytics.com

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
