### ISSUE TITLE
Add "Microsoft Graph" API

### ISSUE THREAD

**Issue by darrelmiller** [APIs-guru/openapi-directory#503]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/microsoftgraph/microsoft-graph-openapi/master/v1.0.json
**Name**: Microsoft Graph

**Comment by MikeRalphson** [comment]
That'll be a test! / cc @whitlockjc

In ~~retaliation~~ thanks, could someone take a look at https://github.com/microsoftgraph/microsoft-graph-openapi/issues/9 ?

**Comment by MikeRalphson** [comment]
Actually, should only add around 30s to a CI run. Looking good!

**Comment by darrelmiller** [comment]
@MikeRalphson Thanks for that heads up.   I'll talk to the folks responsible for that failure :-D

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
