### ISSUE TITLE
Add "HERE" APIs

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#511]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES

**Url**: https://developer.here.com/documentation/positioning/swagger/2.0/api_reference/positioning-v1-external-spec.json
**Name**: HERE Positioning

**Url**: https://developer.here.com/documentation/tracking/swagger/2.0/api_reference/swagger.json
**Name**: HERE Tracking

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
