### ISSUE TITLE
Add "Mercedes-Benz" APIs

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#514]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES

Car Configurator API
https://developer.mercedes-benz.com/content/sites/default/files/2018-08/swagger_car_configurator_api.json

Dealer API
https://developer.mercedes-benz.com/content/sites/default/files/2018-07/swagger_dealer_api_0.yaml

Remote Diagnostic Support API
https://developer.mercedes-benz.com/content/sites/default/files/2018-10/swagger_remote_diagnostics_api_2.yaml

Vehicle Image API
https://developer.mercedes-benz.com/content/sites/default/files/2018-05/swagger_vehicleimage_api.json

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
