### ISSUE TITLE
Add "Axesso Amazon product lookup" API

### ISSUE THREAD

**Issue by viktorRot** [APIs-guru/openapi-directory#525]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/Axesso/axesso-java-client/master/swagger/axessor_api_def_swagger.yaml
**Name**: Axesso Amazon product lookup
**Valid**: Yes

**Comment by viktorRot** [comment]
Hi Mike,

 

you can find our swagger file here:

 

https://github.com/Axesso/axesso-java-client/tree/master/swagger

 

Best regards,

Viktor

 

Gesendet: Montag, 31. Dezember 2018 um 10:24 Uhr
Von: "Mike Ralphson" <notifications@github.com>
An: APIs-guru/openapi-directory <openapi-directory@noreply.github.com>
Cc: viktorRot <viktor.rotaermel@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [APIs-guru/openapi-directory] Add "Axesso Amazon product lookup" API (#525)


Please could you provide the direct URL to your machine-readable API definition? Thanks.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
