### ISSUE TITLE
Add "GeoDB Cities API" API

### ISSUE THREAD

**Issue by wirefreethought** [APIs-guru/openapi-directory#534]
Format: OpenAPI(fka Swagger) 2.0
Official: YES
Url: https://wirefreethought.github.io/geodb-cities-api-docs/swagger.json
Name: GeoDB Cities API
Valid: Yes
Category: developer_tools,location
Logo: https://wirefreethought.github.io/geodb-cities-api-docs/images/logo.png

This should replace the previous"GeoDB City API" entry (issue: Add "GeoDB City API" API #323)

**Comment by MikeRalphson** [comment]
API updated, many thanks for letting us know!
