### ISSUE TITLE
Add "Handwrytten" API

### ISSUE THREAD

**Issue by davidwachs** [APIs-guru/openapi-directory#535]
**Format**: Swagger 2.0
**Official**: YES
**Url**: ~~https://app.swaggerhub.com/apis-docs/Handwrytten/handwrytten/1.0.0~~
**Url**: https://api.swaggerhub.com/apis/Handwrytten/handwrytten/1.0.0
**Name**: Handwrytten
**Valid**: Yes
**Twitter**: Handwrytten
**Category**: text

**Comment by MikeRalphson** [comment]
SwaggerHub direct links now seem to be of the form:

https://app.swaggerhub.com/apiproxy/registry/Handwrytten/handwrytten/1.0.0

**Comment by hkosova** [comment]
@MikeRalphson To get a raw file from SwaggerHub, use:
```
https://API.swaggerhub.com/apis/<owner>/<apiname>/<version> - JSON
https://API.swaggerhub.com/apis/<owner>/<apiname>/<version>/swagger.yaml - YAML
```

In this case:
https://api.swaggerhub.com/apis/Handwrytten/handwrytten/1.0.0
https://api.swaggerhub.com/apis/Handwrytten/handwrytten/1.0.0/swagger.yaml

Please don't use `/apiproxy` links as they might change.

**Comment by MikeRalphson** [comment]
Many thanks @hkosova!

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!

**Comment by davidwachs** [comment]
THANK YOU!
