### ISSUE TITLE
Add "College Football Data API" API

### ISSUE THREAD

**Issue by BlueSCar** [APIs-guru/openapi-directory#544]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.collegefootballdata.com/api-docs.json
**Name**: College Football Data API
**Valid**: Yes
**Logo**: https://collegefootballdata.com/Logo.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
