### ISSUE TITLE
Add "Digital Owl" API

### ISSUE THREAD

**Issue by bstoilov** [APIs-guru/openapi-directory#545]
**Format**: API Blueprint
**Official**: NO
**Url**: https://github.com/bstoilov/digitalowl-api
**Name**: Digital Owl

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, WADL, Google Discovery format etc)? Without this unfortunately we cannot add the API to the directory.

**Comment by bstoilov** [comment]
Hello Mike, I created RAML 1.0 specification which you can access here
<https://drive.google.com/file/d/1rGYhk-2JrcaLD4qjwpcIkT5R5_MHFF6B>.

Let me know if this works for you.

Regards.

**Comment by MikeRalphson** [comment]
Many thanks for the submission, we're waiting on a PR (https://github.com/mulesoft/oas-raml-converter/pull/19) to our RAML converter, then we should be able to add this API.

**Comment by bstoilov** [comment]
That is great news, thank you.

Regards

**Comment by MikeRalphson** [comment]
File no longer exists at that URL. Please chase if you would still like this API added.
