### ISSUE TITLE
Add "NamSor Name to Gender and Ethnicity API" API

### ISSUE THREAD

**Issue by namsor** [APIs-guru/openapi-directory#546]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://v2.namsor.com/NamSorAPIv2/api2/openapi.json
**Name**: NamSor Name to Gender and Ethnicity API
**Valid**: Yes
**Twitter**: @gendreapp

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
