### ISSUE TITLE
Add "bunq API" API

### ISSUE THREAD

**Issue by lexym** [APIs-guru/openapi-directory#547]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/bunq/doc/master/swagger.json
**Name**: bunq API
**Valid**: No

**Comment by MikeRalphson** [comment]
Hi, thanks for the submission. Are you associated with the API? If so, could you fix validation errors. E.g. the first one I found seems to be missing `name` and `in` properties on a parameter:

```
expected Object {
  description: 'The standard HTTP Cache-Control header is required for all requests.',
  schema: Object { type: 'string' },
  required: true
} to have property name
#/paths/~1user~1{userID}~1monetary-account~1{monetary-accountID}~1share-invite-bank-inquiry~1{share-invite-bank-inquiryID}~1amount-used~1{itemId}/delete/parameters/4
```

**Comment by lexym** [comment]
Hi Mike,

Thank you for your pointing it out. We will definitely look to it. I'll leave a comment here when it is fixed.

Cheers

**Comment by kojoru** [comment]
Hi @MikeRalphson! Which tool do you use to validate OpenAPI 3 definition?

I'll ensure it gives no warnings for bunq API.

**Comment by MikeRalphson** [comment]
I use the validator from `oas-kit`. There is an online version at http://mermade.org.uk/openapi-converter

**Comment by kojoru** [comment]
@MikeRalphson please check again on the same URL. I don't see any errors via the validator now.

**Comment by MikeRalphson** [comment]
Hmm, I'm seeing

```
#/components/schemas/SofortMerchantTransaction/properties/error_message
expected Object {
  type: 'array',
  description: 'The error message of the transaction.',
  readOnly: true,
  writeOnly: false
} to have property items
```

though that is with the latest local copy of the validator.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
