### ISSUE TITLE
Add "PeerTube" API

### ISSUE THREAD

**Issue by roipoussiere** [APIs-guru/openapi-directory#554]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/Chocobozzz/PeerTube/develop/support/doc/api/openapi.yaml
**Name**: PeerTube

**Comment by roipoussiere** [comment]
Note that PeerTube is open-source and has hundreds of instances.

Its official website is http://joinpeertube.org/, a list of instances can be found [here](https://instances.joinpeertube.org/instances), and a test-purpose instance is available [here](https://peertube.cpy.re/).

**Comment by MikeRalphson** [comment]
Thanks for the contribution!

There are several mismatches between templated parameters in the `pathItem` keys and parameters defined (or not defined) in the `parameters` objects.

These can be seen with a validator such as https://mermade.org.uk/openapi-converter

Do you have a route to getting those validation errors fixed?

**Comment by roipoussiere** [comment]
> These can be seen with a validator such as https://mermade.org.uk/openapi-converter

I get `status:  {}`.

With [an other validator](https://apidevtools.org/swagger-parser/online/), I get:

```
This API is valid, but it cannot be shown because it contains circular references

toText@https://apidevtools.org/swagger-parser/online/js/bundle.js:933:15
[8]</editors.addResult@https://apidevtools.org/swagger-parser/online/js/bundle.js:866:13
[8]</editors.showResult@https://apidevtools.org/swagger-parser/online/js/bundle.js:822:3
parseSwagger/</<@https://apidevtools.org/swagger-parser/online/js/bundle.js:1139:11
parseSwagger/<@https://apidevtools.org/swagger-parser/online/js/bundle.js:1138:30
```

(which is not really helpful)

Nothing concerning the `parameters` objects...

**Comment by MikeRalphson** [comment]
Apologies, I'll update the online validator to the latest version of the engine later today and ping you back.

**Comment by MikeRalphson** [comment]
Apologies for the delay, the online validator is back up. Just check http://mermade.org.uk/api/v1/validate?url=https://raw.githubusercontent.com/Chocobozzz/PeerTube/develop/support/doc/api/openapi.yaml until no errors are returned.

**Comment by roipoussiere** [comment]
@chocobozzz

**Comment by Chocobozzz** [comment]
Thanks, it should be okay now.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
