### ISSUE TITLE
Azure WebApps spec is missing

### ISSUE THREAD

**Issue by pimterry** [APIs-guru/openapi-directory#557]
Is there any documentation on how the Azure import process works? I'd happily debug deeper, but I can't find anything.

The specific spec that is missing is `WebApps.json` here: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/web/resource-manager/Microsoft.Web/stable/2018-02-01. In APIs/azure.com in this repo I can see various other specs from that folder (e.g. web-DeletedWebApps, web-ResourceHealthMetadata), but there doesn't seem to be any corresponding spec for this one.

This spec defines all the core [web apps](https://azure.microsoft.com/en-us/services/app-service/web/) endpoints, e.g. all the main hosted sites/functions endpoints, so it's a pretty major omission! Let me know if there's anything I can do to help debug.

**Comment by MikeRalphson** [comment]
Hmm, bit of a mystery this one, the url doesn't seem to be blacklisted, and a quick check shows that it's valid.

So what should happen is that the `update` command downloads `https://codeload.github.com/Azure/azure-rest-api-specs/tar.gz/master` which **does** include `specification/web/resource-manager/Microsoft.Web/stable/2018-02-01/WebApps.json`.

Now the `update` command ignores URLs even from github repo archives which are not currently part of the directory (not sure I would have designed this part like this, but I inherited this project).

So the command which adds new valid definitions from URLs in so called `spec_sources` (which aren't present in `blacklist.yaml`) is `leads`.

**Comment by MikeRalphson** [comment]
When resolved this definition has the following error:

```
======================== azure.com/web-WebApps/2018-02-01/swagger.yaml ================
UNRESOLVABLE_REFERENCE #/definitions/ErrorEntity
UNRESOLVABLE_REFERENCE #/definitions/ErrorEntity
```

I have patched this up by making `ErrorEntity` an empty schema.

I've tried raising issues on the Azure repo but didn't get anywhere. Until they add some CI to their process things like this will keep happening.

**Comment by MikeRalphson** [comment]
Deployed. Thanks for the report.

**Comment by pimterry** [comment]
Amazing, thank you! That's perfect :+1:
