### ISSUE TITLE
Add "Job titles and Skill tags API by mycru.io" API

### ISSUE THREAD

**Issue by mycru** [APIs-guru/openapi-directory#558]
**Format**: API Blueprint
**Official**: YES
**Url**: ~~https://mycrujobtitlesskills.docs.apiary.io~~
**Url**: https://mycrujobtitlesskills.docs.apiary.io/api-description-document
**Name**: Job titles and Skill tags API by mycru.io

**Comment by mycru** [comment]
Icon for API    https://mycru.io/banner/mycru512x512.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
