### ISSUE TITLE
Add "Akeneo PIM API" API

### ISSUE THREAD

**Issue by AwakenTheJaken** [APIs-guru/openapi-directory#559]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/akeneo/pim-api-docs/master/content/swagger/akeneo-web-api.json
**Name**: Akeneo PIM API
**Twitter**: akeneopim

**Comment by AwakenTheJaken** [comment]
Thanks for looking into this! Is there anything I can do in the meantime to help out?

**Comment by MikeRalphson** [comment]
Apologies for leaving this hanging, I think I was just looking for the correct category and got distracted! API will be added in the next hour or so.
