### ISSUE TITLE
Add "Rev.ai Speech-to-text API" API

### ISSUE THREAD

**Issue by dkokotov** [APIs-guru/openapi-directory#560]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: http://api.rev.ai/openapi/v1/documentation.yaml
**Name**: Rev.ai Speech-to-text API

**Comment by MikeRalphson** [comment]
```
expected Object { type: 'array', description: 'Allowed values for this request' } to have property items
#/paths/~1jobs~1{id}/delete/responses/409/content/application~1problem+json/properties/allowed_values
```

When `type` is `array`, `items` is mandatory to describe the array contents. There may be other validation errors.

**Comment by dkokotov** [comment]
@MikeRalphson we will fix this. Is there a good way to run your script by hand to make sure we fix all the errors at once?

**Comment by MikeRalphson** [comment]
I'm just fixing an issue with the online validator, will ping you when done. Or there is the node.js package `swagger2openapi` which has an `oas-validate` command.

**Comment by MikeRalphson** [comment]
The online validator is fixed again now. Just check against http://mermade.org.uk/api/v1/validate?url=http://api.rev.ai/openapi/v1/documentation.yaml until no errors are returned.

**Comment by MikeRalphson** [comment]
>Schema object cannot have additionalProperty: content
`#/paths/~1jobs~1{id}~1transcript/get/responses/200/content/text~1plain/schema`

**Comment by MikeRalphson** [comment]
> expected 'String' to be equals one of Array `[ 'integer', 'number', 'string', 'boolean', 'object', 'array' ]`
`#/paths/~1jobs~1{id}/get/responses/200/content/application~1json/properties/delete_after_seconds`

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! Will be live on site when the CI run completes.
