### ISSUE TITLE
Add "bng2latlong" API

### ISSUE THREAD

**Issue by GetTheData** [APIs-guru/openapi-directory#562]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://www.getthedata.com/bng2latlong/openapi
**Name**: bng2latlong
**Valid**: Yes
**Category**: location
**Twitter**: getthedatacom

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! Deploying now.

**Comment by GetTheData** [comment]
Thanks @MikeRalphson - much appreciated!
