### ISSUE TITLE
Add "ExchangeRate-API"

### ISSUE THREAD

**Issue by bimmer44** [APIs-guru/openapi-directory#563]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://www.exchangerate-api.com/openapi.yaml
**Name**: ExchangeRate-API
**Valid**: Yes
**Category**: financial

**Comment by bimmer44** [comment]
You can use this image for the thumbnail:

https://www.exchangerate-api.com/img/logo-cube-135px.png

If you need anything else let me know so I can sort it out. Thanks for running this great service!

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
