### ISSUE TITLE
Add "Language Detection" API

### ISSUE THREAD

**Issue by BigLobsterito** [APIs-guru/openapi-directory#564]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/BigLobsterito/apis/master/language-identification-swagger.yaml
**Name**: Language Detection
**Valid**: Yes

**Comment by MikeRalphson** [comment]
Please could you provide a stable URL for the always-latest version of your API definition? Otherwise our update scripts will never detect changes in the gist-hosted copy at that URL.

**Comment by BigLobsterito** [comment]
@MikeRalphson, URL updated.
