### ISSUE TITLE
Amazon Mturk API Errors?

### ISSUE THREAD

**Issue by veaux** [APIs-guru/openapi-directory#571]
Love site! If we paste API of amazonaws/mturk-requester/2017-01-17 into editor.swagger.io for JSON conversion get some errors or blank POST items.

**Comment by MikeRalphson** [comment]
The OpenAPI documents here pass multiple validators. Could you be a bit more specific as to which `path` and method(s) show errors or blank 'items'? A screenshot might help.

If all you need is a JSON version of the YAML file in the repository, these are always available via our API urls, e.g.: https://api.apis.guru/v2/specs/amazonaws.com/mturk-requester/2017-01-17/swagger.json

**Comment by veaux** [comment]
Where we came up with questions was if we pasted API into editor.swagger.io, YAML or JSON. If we pick a validator such as GetAccountBalance, that comes up blank. So it's suggesting something earlier is causing an error?

**Comment by MikeRalphson** [comment]
The `body` parameter schema definition comes from this original definition in the Amazon AWS SDK:

```json
"GetAccountBalanceRequest":{
      "type":"structure",
      "members":{
      }
    },
```

That translates to an empty JSON Schema object, where any JSON is allowed. Without more information from the AWS side we have no way of automatically generating those schemas.
