### ISSUE TITLE
Add "Contract.fit" API

### ISSUE THREAD

**Issue by HanneContractFit** [APIs-guru/openapi-directory#576]
**Format**: Swagger 2.0
**Official**: YES
**Url**: https://cfportal.contract-p.fit/swagger.json
**Name**: Contract.fit
**Description**: Contract.fit is the solution to help you with all your intelligent automation needs. Fast, accurate and flexible API for extraction, classification and validation of content from documents, emails, etc.

**Comment by MikeRalphson** [comment]
Thanks for the submission. Your OpenAPI/Swagger definition has some validation errors. Please could you correct these? For example:

>Swagger schema validation failed. 
  Additional properties not allowed: patternProperties,definitions at #/definitions/EvaluationDataPost

https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fcfportal.contract-p.fit%2Fswagger.json

**Comment by MikeRalphson** [comment]
Closing in favour of #598
