### ISSUE TITLE
Add "WhatsApp Business API" API

### ISSUE THREAD

**Issue by jmini** [APIs-guru/openapi-directory#584]
**Format**: OpenAPI 3.0
**Official**: NO
**Url**: https://raw.githubusercontent.com/unblu/WhatsApp-Business-API-OpenAPI/master/openapi.yaml
**Name**: WhatsApp Business API

**Comment by jmini** [comment]
More information on the project Homepage:
https://unblu.github.io/WhatsApp-Business-API-OpenAPI/

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
