### ISSUE TITLE
Add "Secured Signing API" API

### ISSUE THREAD

**Issue by securedsigningsupport** [APIs-guru/openapi-directory#589]
**Format**: Swagger 1.x
**Official**: YES
**Url**: https://api.securedsigning.com/web/v1.4/resources
**Name**: Secured Signing API

**Comment by MikeRalphson** [comment]
I'm seeing validation errors on your Swagger document which is preventing conversion. I'll try and get you a readable error message, but in the meantime, is there any reason you are (still) using Swagger 1.x - tooling support is very poor compared to Swagger/OpenAPI 2.0 / 3.0.x

**Comment by MikeRalphson** [comment]
The first error is

```
{
  "errors": [
    {
      "code": "OBJECT_MISSING_REQUIRED_PROPERTY",
      "message": "Missing required property: description",
      "path": [
        "info"
      ],
      "description": "info object (section 5.1.3)"
    }
  ],
  "warnings": []
}
```

though I suspect there may be more in the resource sections.

**Comment by MikeRalphson** [comment]
We no longer support Swagger 1.2, please let us know if you upgrade to 2.0 or 3.x
