### ISSUE TITLE
Add "Intellifi Brain Web API" API

### ISSUE THREAD

**Issue by idelsink** [APIs-guru/openapi-directory#593]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://intellifi-nl.github.io/brain-rest-api-spec/openapi.yml
**Name**: Intellifi Brain Web API

**Comment by MikeRalphson** [comment]
Thanks for the submission.

Please could you address validation errors (shown by, for example, http://mermade.org.uk/api/v1/validate?url=https://intellifi-nl.github.io/brain-rest-api-spec/openapi.yml)

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
