### ISSUE TITLE
Add "LambdaTest Screenshot API"

### ISSUE THREAD

**Issue by jahmed2345** [APIs-guru/openapi-directory#595]
**Format**: ~~Swagger 1.x~~ OpenAPI 3.0.x
**Official**: YES
**Url**: ~~https://www.lambdatest.com/support/docs/api-doc/#screenshots~~
**Url**: https://screenshot-public-api.s3.amazonaws.com/openapi.yaml
**Name**: LambdaTest Screenshot API

**Comment by MikeRalphson** [comment]
Thanks for the contribution. Unfortunately, your API definition contains one or more validation errors.

Could you run it through a validator (several are available at https://apis.guru/awesome-openapi3/category.html#parsers) until there are no more errors such as this one:

```
expected Object { type: 'array', example: Array [ '1024x768', '1280x1024' ] } to have property items
#/components/schemas/res_list
```

Thanks.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
