### ISSUE TITLE
Wrong category in tinyuid API definition

### ISSUE THREAD

**Issue by Atralbus** [APIs-guru/openapi-directory#596]
All other APIs are categorized as `developer_tools` except `tinyuid.com`.

**Comment by MikeRalphson** [comment]
When you say "all other APIs", which ones do you mean? For instance, most amazonaws APIs are categorised as `cloud`.

**Comment by Atralbus** [comment]
I meant other developer tools APIs. Their category name contains underscore (as `developer_tools`)  but tinyuid contains hyphen (as `developer-tools`).

**Comment by MikeRalphson** [comment]
Thanks!
