### ISSUE TITLE
Add "SheerSEO API" API

### ISSUE THREAD

**Issue by sheerseo** [APIs-guru/openapi-directory#597]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: ~~https://www.sheerseo.com/api/swagger-ui/#/default~~
**Url**: https://www.sheerseo.com/api/swagger.yaml
**Name**: SheerSEO API
**Valid**: Yes
**Twitter**: sheerseo

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
