### ISSUE TITLE
Add "Image-Charts" API

### ISSUE THREAD

**Issue by FGRibreau** [APIs-guru/openapi-directory#599]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://image-charts.com/swagger.json
**Name**: Image-Charts
**Valid**: Yes
**Twitter**: imagecharts

**Comment by MikeRalphson** [comment]
Hi, thanks for the contribution. Your API definition contains some validation errors (`optional` properties, which look like they should be `x-optional` vendor/specification extensions).

https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fimage-charts.com%2Fswagger.json

Please could you look at getting these fixed before inclusion?

**Comment by FGRibreau** [comment]
Hello @MikeRalphson, everything's good now!

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
