### ISSUE TITLE
Add "WGS84 to OSGB36" API

### ISSUE THREAD

**Issue by quicksold** [APIs-guru/openapi-directory#610]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://quicksold.co.uk/v2/api-docs
**Name**: WGS84 to OSGB36
**Valid**: Yes
**Category**: location
**Twitter**: QuicksoldCoUk

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
