### ISSUE TITLE
Add "AutoML" API

### ISSUE THREAD

**Issue by jbejenar** [APIs-guru/openapi-directory#614]
**Format**: Google API Discovery
**Official**: YES
**Url**: https://automl.googleapis.com/$discovery/rest?version=v1beta1
**Name**: AutoML

**Comment by MikeRalphson** [comment]
All public google discovery APIs should be included already, will investigate.

**Comment by MikeRalphson** [comment]
Something very odd going on, that URL 404s from my machine using Curl and Wget but not with Firefox, even when copying the browser request to curl format.

Anyway, added now, thanks.
