### ISSUE TITLE
Add "RAWG" API

### ISSUE THREAD

**Issue by accujazz** [APIs-guru/openapi-directory#618]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.rawg.io/docs/?format=openapi
**Name**: RAWG

**Comment by MikeRalphson** [comment]
> Validation failed. /paths/games/{game_pk}/get has a path parameter named "id", but there is no corresponding {id} in the path string

**Comment by accujazz** [comment]
Hi, thanks, we have fixed the issue.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! Apologies for the delay.
