### ISSUE TITLE
Add URLs on API key registration 

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#64]
It would be cool to provide user directly link to API key registration or at least documentation that explains how to get API key. I created `x-apiClientRegistration` extension and mark [couple](https://github.com/APIs-guru/api-models/search?utf8=%E2%9C%93&q=x-apiClientRegistration+filename%3Apatch&type=Code) or APIs.

I need help with the rest of APIs, the task is very simple just add `x-apiClientRegistration` into appropritate `patch.yaml` and submit PR. Here is [example](https://github.com/APIs-guru/api-models/blob/master/APIs/bigoven.com/patch.yaml#L4-L5).

**Comment by oliver-xapix-io** [comment]
+1 for the issue

What if you have to sign up for some account on the provider website first, then create a key pair for the API? A very common workflow.

Link to the "user account sign up" or "API key creation"? Most websites will just prompt you for sign in/up when you visit the latter one without being signed in, so I'd propose to go for the 2nd option.

**Comment by IvanGoncharov** [comment]
@oliver-xapix-io Definitely "API key creation", because all "API key creation" pages link to "user account sign up" but not vice versa.
