### ISSUE TITLE
Add "Get Email Information API" API

### ISSUE THREAD

**Issue by interzoid** [APIs-guru/openapi-directory#649]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://oas.interzoid.com/api/getemailinfo.yaml
**Name**: Get Email Information API

**Comment by MikeRalphson** [comment]
Hi, thanks for the contributions! Do you have a machine-readable index of all your available API descriptions, i.e. in [apis.json](http://apisjson.org/) format or similar? We could use this to add all of your APIs at once and keep up to date with new ones added.

**Comment by interzoid** [comment]
No, not currently but will look into putting one together. Do you have a
good example of one such preferred machine-readable index you can share?

**Comment by MikeRalphson** [comment]
https://developer.trade.gov/apis.json contains the Swagger property we would use.

**Comment by sfbuckeye** [comment]
Here you go: https://oas.interzoid.com/apis.json
How often will it refresh?

**Comment by MikeRalphson** [comment]
@sfbuckeye thanks for this and apologies for the delay. All the APIs mentioned in your `apis.json` file have now been added. I'll close the other issues but please let me know if there are any special cases.

The scripts to update should run once a week.
