### ISSUE TITLE
Add "JSON storage by ExtendsClass" API

### ISSUE THREAD

**Issue by cyrilbois** [APIs-guru/openapi-directory#655]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://extendsclass.com/json-storage.openapi.json
**Name**: JSON storage by ExtendsClass

**Comment by MikeRalphson** [comment]
Thanks for the contribution, could you look at the following validation error:

```
Cannot resolve reference: #/components/schemas/CreateStatus
#/paths/~1bin/post/responses/200/content/application~1json/schema/%24ref
```

**Comment by cyrilbois** [comment]
Hello, Thank you for warning me about this error! It is fixed.

**Comment by MikeRalphson** [comment]
Sorry, there is just one more (my validator throws on the first error). Your path `/bin/{id}` needs an `id` parameter defining, something like:

```json
    "paths": {
        "/bin/{id}": {
            "parameters": [
              {
                "name": "id",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
```

**Comment by cyrilbois** [comment]
Sorry, I changed validator ... It is fixed. Thanks.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! 

PS it may take a little while to show up on the website, as we have had a few out-of-memory errors in the CI / deployment pipeline that we're working on.

**Comment by cyrilbois** [comment]
Thanks!
