### ISSUE TITLE
Add "PTV Timetable API - Version 3" API

### ISSUE THREAD

**Issue by jamesladd** [APIs-guru/openapi-directory#658]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: http://timetableapi.ptv.vic.gov.au/swagger/docs/v3
**Name**: PTV Timetable API - Version 3

**Comment by MikeRalphson** [comment]
Hi, thanks for the contribution, it seems we already have this API in the directory (`APIs/ptv.vic.gov.au/v3/swagger.yaml`) and it is up-to-date.
