### ISSUE TITLE
Update Githhub v3 API

### ISSUE THREAD

**Issue by nitishMehrotra** [APIs-guru/openapi-directory#662]
1. The current API available in the directory doesn't account for how Github is using OAUTH2.

They have a non standard method where instead of Authorization: Bearer <token> they use  Authorization: token <token>. 
One quick fix around this is to support both OAUTH and API_KEY in github api where apikeyPrefix is token

2. The second is around security definitions not added for all the APIs. Even though Github supports pulblic end points but for a lot of use cases (like /user or /user/repos) authentication is required.

**Comment by nitishMehrotra** [comment]
I have picked up the spec given in the directory and updated it for my use case but I think it might make solve some of the above mentioned issues as well. 

I can open a PR for review if that will help

**Comment by MikeRalphson** [comment]
We're thinking about switching over to the octokit/routes published OpenAPI document: https://github.com/octokit/routes/blob/master/openapi/api.github.com/index.json - does this look any better from your point of view?

**Comment by pimterry** [comment]
As of today, GitHub now have an officially published OpenAPI spec: https://github.blog/2020-07-27-introducing-githubs-openapi-description/. The spec itself is here: https://github.com/github/rest-api-description.

We should switch to that, and any spec improvements should happen over there.

**Comment by MikeRalphson** [comment]
I would, but it doesn't validate for me. Looking into it.

**Comment by MikeRalphson** [comment]
Related issue https://github.com/github/rest-api-description/issues/14

**Comment by MikeRalphson** [comment]
GitHub fixed the issues already! We have moved to the official document and removed the old unofficial and OctoKit versions. As @pimterry noted above, any deficiences in the new version should now be reported upstream.

**Comment by nitishMehrotra** [comment]
@MikeRalphson This is awesome. I'll take a look and see how it works with our system.

**Comment by MikeRalphson** [comment]
We will be adding the GitHub enterprise versions soon too.
