### ISSUE TITLE
GitHub API: "assignee" field has wrong type

### ISSUE THREAD

**Issue by bobby-brennan** [APIs-guru/openapi-directory#67]
https://github.com/APIs-guru/api-models/blob/master/APIs/github.com/v3/swagger.yaml#L13572

Listed as string, should be a user object, e.g. here:
https://api.github.com/repos/bobby-brennan/rss-parser/issues/3

**Comment by IvanGoncharov** [comment]
This issue was moved to APIs-guru/unofficial_openapi_specs#4
