### ISSUE TITLE
Looking maintainer for GitHub API

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/openapi-directory#68]
I used an official RAML spec as source: https://github.com/raml-apis/GitHub/tree/production
It has many problems including #67 and many more other issues that you can easily spot.
But most important is that Mulesoft(owner of repo) ignores [issues](https://github.com/raml-apis/GitHub/issues) and [PRs](https://github.com/raml-apis/GitHub/pulls).

IMHO, correct way to handle this situation is to split Swagger spec for Github API into a separate repo and maintain it there for APIs.guru to use it as a source.

Is someone interested in maintaining such repo under his user account?

**Comment by MikeRalphson** [comment]
@IvanGoncharov I am interested in producing a spec for the new github [GraphQL API](http://githubengineering.com/the-github-graphql-api/) and perhaps for a 'classic' v4 if they produce one, but probably not to revise the current API v3 specification.

**Comment by MikeRalphson** [comment]
[First cut - valid and working with bearer auth](https://raw.githubusercontent.com/Mermade/openapi_specifications/master/github/swagger.json)

**Comment by IvanGoncharov** [comment]
@MikeRalphson Great, it's Wikipedia for APIs so it's cool that you contributing specs that you are working on.

IMHO, you can produce quality spec only if you interested in studying API or interested in using OpenAPI spec.
