### ISSUE TITLE
Add "Company Lookalikes by Automata" API

### ISSUE THREAD

**Issue by afraine** [APIs-guru/openapi-directory#683]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://s3.amazonaws.com/api.specs.byautomata.io/automata_api.json
**Name**: Company Lookalikes by Automata

**Comment by MikeRalphson** [comment]
Your API definition contains a `schema` property under your `parameters` object, which is not valid according to OpenAPI 2.0

https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fs3.amazonaws.com%2Fapi.specs.byautomata.io%2Fautomata_api.json

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
