### ISSUE TITLE
Add "Canada Holidays" API

### ISSUE THREAD

**Issue by pcraig3** [APIs-guru/openapi-directory#690]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://app.swaggerhub.com/apis/pcraig3/canada-holidays
**Name**: Canada Holidays

Hello! Not sure what "official" means, but this is an API for holidays in Canada that's based on the official data (which, regrettably, is not available as an API).

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
