### ISSUE TITLE
Add "Handwritten for sending handwritten cards" API

### ISSUE THREAD

**Issue by wallawe** [APIs-guru/openapi-directory#691]
**Format**: Swagger 1.x
**Official**: YES
**Url**: https://www.handwrite.io/handwritten-notes-api
**Name**: API for sending handwritten letters

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, WADL, Google Discovery format etc)? Without this unfortunately we cannot add the API to the directory.
