### ISSUE TITLE
Add "TL API" API

### ISSUE THREAD

**Issue by hiran108** [APIs-guru/openapi-directory#692]
**Format**: OpenAPI 3.0
**Official**: NO
~~**Url**: https://tl-api.azurewebsites.net/swagger/main/swagger.json~~
**Url**: https://tl-api.azurewebsites.net/swagger/default/swagger.json
**Name**: TL API

**Comment by MikeRalphson** [comment]
There's a small issue with your API definition:

```json
  "security": [
    {
      "Bearer": [
        "Bearer"
      ]
    }
  ]
```

should be:

```json
  "security": [
    {
      "Bearer": []
    }
  ]
```

as scopes are only allowed for oAuth2 / openIdConnect securitySchemes.

**Comment by MikeRalphson** [comment]
Could you also improve the description for those not familiar with what the TL API is? How is the API related to the `tl.no` domain?

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
