### ISSUE TITLE
Add "Brainbi Price API" API

### ISSUE THREAD

**Issue by lixam** [APIs-guru/openapi-directory#698]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://documenter.getpostman.com/view/1148203/SzKZtGPb
**Name**: Brainbi Price API

**Comment by MikeRalphson** [comment]
https://www.postman.com/collections/1148203-6a9d2dc5-3f7e-47f5-ae7d-782740625908-SzKZtGPb

**Comment by MikeRalphson** [comment]
Tried with `postman-to-openapi` but hit errors with an undefined path. https://github.com/joolfe/postman-to-openapi/issues/43 ?

**Comment by MikeRalphson** [comment]
API added with `postman2openapi` conversion step. Thanks @kevinswiber !

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
