### ISSUE TITLE
Add Updated ConfigCat API

### ISSUE THREAD

**Issue by kp-cat** [APIs-guru/openapi-directory#703]
I'd like to update the ConfigCat API. It seems that the update script hasn't updated that yet. 
Should we change something in the API to be able to update it by the script? 

Format: OpenAPI 3.0
Official: YES
Url: https://api.configcat.com/docs/v1/swagger.json
Name: ConfigCat

**Comment by MikeRalphson** [comment]
No, it should update automatically, but I've been trying to rewrite some core bits of the scripting lately which has delayed a few things.

**Comment by kp-cat** [comment]
Is it possible to update it manually?

**Comment by MikeRalphson** [comment]
Updated, running CI/deployment now.
