### ISSUE TITLE
Where is the openapi.yaml file for Google APIs Admin/Directory v1?

### ISSUE THREAD

**Issue by tonedef71** [APIs-guru/openapi-directory#709]
I see no **_openapi.yaml_** file in the [directory_v1 folder](https://github.com/APIs-guru/openapi-directory/tree/master/APIs/googleapis.com/admin/directory_v1).   The file does exist for the other two _admin_ APIs ([datatransfer_v1](https://github.com/APIs-guru/openapi-directory/tree/master/APIs/googleapis.com/admin/datatransfer_v1) and [reports_v1](https://github.com/APIs-guru/openapi-directory/tree/master/APIs/googleapis.com/admin/reports_v1)).  

What happened to the OpenAPI 3 documentation for _directory_v1_?

**Comment by MikeRalphson** [comment]
Thanks for pointing this out! When it was a `swagger` 2.0 file, the `googleapis/admin/directory_v1` API had some patches applied, which when it was converted to `openapi` 3.0 no longer cleanly applied, thus it failed validation and the `openapi.yaml` file was never created.

I've removed the redundant patch files and re-updated missing/new google APIs, which included this one. CI/deployment to the website/API is running now, but the file is now present in this repo.

Thanks again for spotting this.
