### ISSUE TITLE
Add "ExchangeRate-API.com" API

### ISSUE THREAD

**Issue by bimmer44** [APIs-guru/openapi-directory#710]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://www.exchangerate-api.com/openapi.yaml
**Name**: ExchangeRate-API.com

**Comment by MikeRalphson** [comment]
Thanks, but we already have this API in the directory and it seems to be up-to-date.

**Comment by bimmer44** [comment]
OK great, my apologies!
