### ISSUE TITLE
Add "Kubernetes" API

### ISSUE THREAD

**Issue by stifelch** [APIs-guru/openapi-directory#711]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://v1-14.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/
**Name**: Kubernetes

**Comment by MikeRalphson** [comment]
Thanks, we already have `v1.18.0` of this API in the directory.

**Comment by stifelch** [comment]
Hey there, we'd need the 1.10 Version specificly for our purposes...no chance to support this Version?

**Comment by MikeRalphson** [comment]
Ok, went back through the kubernetes GitHub history and found it. Is present in the repo now, will be on the website / API when the CI run finishes in around 40 minutes from now.

**Comment by stifelch** [comment]
Great, thank you so much!

**Comment by stifelch** [comment]
Sorry for disturbing again, but i can't find the kubernetes 1.10 api on the website / api collection :/ Any help would be highly appreciated

**Comment by MikeRalphson** [comment]
https://github.com/APIs-guru/openapi-directory/blob/master/APIs/kubernetes.io/v1.10.0/swagger.yaml
