### ISSUE TITLE
Add "COVID-19 Tracking QR Code Signin Server API" API

### ISSUE THREAD

**Issue by aijaz** [APIs-guru/openapi-directory#713]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/aijaz/qrCodeSigninServer/main/openapi.yaml
**Name**: COVID-19 Tracking QR Code Signin Server API

**Comment by MikeRalphson** [comment]
Hi! Thanks for the submission. No validation errors, excellent.

Do you have a version which points at a live server (i.e. not `https://virtserver.swaggerhub.com/aijaz/QRCodeSigninServer/1.0`) or is the API designed to be self-hosted?

**Comment by aijaz** [comment]
As part of a suite of open source apps, the API (which is implemented in a web server app repo) is designed to be self-hosted. Once we have a new version, or we have a demo host (whichever comes first) I would like to submit a new version. 

Thank you.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
