### ISSUE TITLE
Add "IdealSpot GeoData Location Intelligence" API

### ISSUE THREAD

**Issue by kevincal** [APIs-guru/openapi-directory#714]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://idealspot.gitlab.io/developer-docs/specs/idealspot-swagger20.json
**Name**: IdealSpot GeoData Location Intelligence

**Comment by MikeRalphson** [comment]
Thanks. Can we close #707 ?

**Comment by kevincal** [comment]
Yes. Ty

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
