### ISSUE TITLE
Add "Probely" API

### ISSUE THREAD

**Issue by nunoloureiro** [APIs-guru/openapi-directory#715]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://developers.probely.com/openapi.yaml
**Name**: Probely

**Comment by MikeRalphson** [comment]
Thanks for the contribution. Unfortunately the API definition fails validation. For example:

> path parameters must appear in the path
`#/paths/~1keys~1/get/parameters/0`

```yaml
/keys/:
    get:
      tags:
        - API Keys
      summary: List API keys allowed to operate on account
      parameters:
        - $ref: "#/components/parameters/targetId"
...
    targetId:
      in: path
      name: target_id
      required: true
      description: Target id
      schema:
        $ref: '#/components/schemas/id'
```

The parameter `target_id` doesn't exist in the path `/keys/` (and several other places).

**Comment by hcastilho** [comment]
The schema has been updated, fixing all found issues.

I was not able to find an official validation tool for inclusion, is there one?

**Comment by MikeRalphson** [comment]
Sorry, I spoke a little too soon, I was using a development version of our validator where I'd been making some performance-tuning changes. With the released version I still see this error:

```
path parameters must appear in the path
#/paths/~1keys~1/get/parameters/0
```

The `pathItem` `/keys/` > `get` operation defines a parameter (using a `$ref`) `targetId` which is an `in:path` parameter, but `targetId` doesn't appear in the path `/keys/`. This error occurs in other `operation`s and `paths`.

**Comment by hcastilho** [comment]
Seems like our current validator is way too lenient.

The schema file is now passing on oas-validator.
I'll have a look at fixing the linter warnings and improving/changing our tooling at a later date.

PS: The link to boast.js in the swagger2openapi npm entry is broken. (The one under the text "See the boast command-line tool for a fuller CLI tool for converting, validating and linting.")

**Comment by MikeRalphson** [comment]
Thanks for that, and for the PS, will take a look.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
