### ISSUE TITLE
Add "QingStor Object Storage" API

### ISSUE THREAD

**Issue by Xuanwo** [APIs-guru/openapi-directory#716]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/qingstor/qingstor-api-specs/master/2016-01-06/swagger/api_v2.0.json
**Name**: QingStor Object Storage

**Comment by MikeRalphson** [comment]
Thanks for the contribution. The API definition fails to resolve, for example in 

https://raw.githubusercontent.com/qingstor/qingstor-api-specs/master/2016-01-06/swagger/service.json

There is a `$ref` to `#/definitions/bucket` but `#/definitions/bucket` doesn't exist in that resource. `$ref`s are scoped to the current resource, so this `$ref` should be a direct link to whatever resource contains `#/definitions/bucket`, e.g. `/definitions.json#/bucket` You can't "defer" resolution of `$ref`s to later in the process.

**Comment by Xuanwo** [comment]
Well, they are split into different files, we will generate a full version for this,

**Comment by MikeRalphson** [comment]
No, I can see the API definition is split into multiple files, it's just that it is not done correctly.

I would be interested to know what tool you could use to generate a single file from them, because it would not be following the JSON Pointer specification.

**Comment by Xuanwo** [comment]
Our services will parse OpenAPI Specs via [OAI object model](https://github.com/go-openapi/spec) which supports load files and keep them in the same scope like following:

```json
    "bucket": {
      "$ref": "./definitions.json#/bucket"
    },
```

And we will generate them via following scrips:

```js
```javascript
const definitions = JSON.parse(fs.readFileSync(`${definitionsPath}`));
const parameters = JSON.parse(fs.readFileSync(`${parametersPath}`));

_.each(swagger2Paths, spec => {
  let data = JSON.parse(fs.readFileSync(`${spec}`));
  data.definitions = {};
  _.each(definitions, (v, k) => {
    data.definitions[k] = {
      '$ref': `../common/definitions.json#/${k}`
    }
  });
  data.parameters = {};
  _.each(parameters, (v, k) => {
    data.parameters[k] = {
      "$ref": `../common/parameters.json#/${k}`
    }
  });
  fs.writeFileSync(`${spec}`, utils.stringify(data) + "\n");
});
```
```

**Comment by MikeRalphson** [comment]
Rather than using your own tools to resolve the separate files, it would allow more people to use them if you fixed the out-of-scope `$ref`s. Just saying.

**Comment by Xuanwo** [comment]
OK, we will trying to fix this.

**Comment by MikeRalphson** [comment]
@Xuanwo any progress on this?

**Comment by Xuanwo** [comment]
We found OpenAPI is not suitable for object storage alike apis without extension, so we will stop the trying.
