### ISSUE TITLE
Add "Google Pay Passes" API

### ISSUE THREAD

**Issue by smoench** [APIs-guru/openapi-directory#717]
**Format**: Google API Discovery
**Official**: YES
**Url**: https://walletobjects.googleapis.com/$discovery/rest?version=v1
**Name**: Google Pay Passes

https://developers.google.com/pay/passes/rest

**Comment by MikeRalphson** [comment]
Thanks for the suggestion. I wonder why it's not listed in https://www.googleapis.com/discovery/v1/apis ?

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! Should be visible when CI process has finished.

**Comment by smoench** [comment]
@MikeRalphson Awesome! Thank you for your quick response and converting this api to openapi!
