### ISSUE TITLE
Add "OPTIMADE" Materials Science Databases API

### ISSUE THREAD

**Issue by blokhin** [APIs-guru/openapi-directory#722]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/Materials-Consortia/OPTIMADE/master/schemas/openapi_schema.json
**Name**: OPTIMADE, the Open Databases Integration for Materials Design

**Comment by MikeRalphson** [comment]
There are a few validation errors you might want to look at fixing?

https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fraw.githubusercontent.com%2FMaterials-Consortia%2FOPTIMADE%2Fmaster%2Fschemas%2Fopenapi_schema.json

**Comment by MikeRalphson** [comment]
Ping @blokhin

**Comment by ml-evs** [comment]
The latest OPTIMADE release fixed this issue (thanks for pointing it out!) We should be compliant at the URL @blokhin provided above, or at the explicitly versioned URL for v1.1: https://raw.githubusercontent.com/Materials-Consortia/OPTIMADE/v1.1.0/schemas/openapi_schema.json

**Comment by MikeRalphson** [comment]
Yes great - looks like that's 100% valid now. Will get it added! Thanks.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
