### ISSUE TITLE
Add "Amadeus Flight Search API" API

### ISSUE THREAD

**Issue by cpearrow** [APIs-guru/openapi-directory#727]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: ~~https://developers.amadeus.com/self-service/category/air/api-doc/flight-offers-search/api-reference~~
**Url**: https://developers.amadeus.com/PAS-EAS/api/v0/documents/10181/file
**Name**: Amadeus Flight Search API

**Comment by MikeRalphson** [comment]
API added, nice to see this one back in the collection. Many thanks for the contribution!

**Comment by cpearrow** [comment]
CONFIDENTIAL & RESTRICTED

Hey Mike,

I'm new to GitHub to wasn't sure I was submitting it correctly. We have a lot more open REST APIs available - could I contribute in the same fashion?

Best,
Chris

**Comment by MikeRalphson** [comment]
Yes, if you can link directly to the OpenAPI / Swagger file in each case that would be brilliant and save me some detective work. I can move the one I just added to give it a "service" value to distinguish it from your other APIs.

Feel free to open other issues or just comment here and I will re-open this one. Thanks again!
