### ISSUE TITLE
Add "Google Search API" API

### ISSUE THREAD

**Issue by tuangeek** [APIs-guru/openapi-directory#728]
Format: OpenAPI 3.0
Official: NO
Url: https://goog.io/
Name: Google Search API
OpenAPI JSON: https://goog.io/openapi.json

**Comment by MikeRalphson** [comment]
Thanks for the submission (though I suspect this API may break Google's terms-of-service). The API definition fails to validate:

https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fgoog.io%2Fopenapi.json

**Comment by tuangeek** [comment]
The OpenAPI JSON has been updated. I can't figure out what is the issue with the last error message though.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
