### ISSUE TITLE
Definitions without properties in pushpay.com API

### ISSUE THREAD

**Issue by maryguirola** [APIs-guru/openapi-directory#73]
These definitions are type Object but don't have properties in pushpay.com API:
-  NullableOfInstant
- NullableOfLocalDate
- NullableOfOffsetDateTime
- OffsetDateTime

**Comment by IvanGoncharov** [comment]
`properties` is optional, if it's absent it mean any properties can be inside this object.
So it __correct__ description, but at the same time, it could be __incomplete__.

I think many of specs is incomplete in one way or another, so it will be impossible to patch all of them.
So we should draw borderline somewhere, for example `securityDefinitions` is absolutely necessary, but `descriptions` in every definition not.

@maryguirola How critical this for your use case?

**Comment by maryguirola** [comment]
Now that's not critical for me. I thought that could be something missed in these definitions.

**Comment by MikeRalphson** [comment]
@maryguirola I think we can close this, but please re-open if you have any problems with obviously incomplete specs.
