### ISSUE TITLE
Add "Chaingateway.io" API

### ISSUE THREAD

**Issue by chaingateway** [APIs-guru/openapi-directory#730]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://chaingateway.io/downloads/openapiv3.json
**Name**: Chaingateway.io

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! Will be live as soon as the CI run finishes.

**Comment by chaingateway** [comment]
Thanks a lot!
