### ISSUE TITLE
Add "Contact Enrichment" API

### ISSUE THREAD

**Issue by jmmpf** [APIs-guru/openapi-directory#732]
**Format**: API Blueprint
**Official**: YES
**Url**: ~~https://pfent1821.docs.apiary.io/#reference/0/contact-enrichment~~
**Url**: https://pfent1821.docs.apiary.io/api-description-document
**Name**: Contact Enrichment

**Comment by MikeRalphson** [comment]
The tool we use to convert APIBlueprint to OpenAPI 2.0 does not enforce unique `operationId`s (see https://github.com/kminami/apib2swagger/issues/50). Either we can wait to see if this issue gets fixed, or you could make the `### Search` headers more descriptive?

**Comment by MikeRalphson** [comment]
We now have a workaround for the above issue.

API added, many thanks for the contribution! Will be live on the site once the CI run finishes.
