### ISSUE TITLE
Confused about naming conventions

### ISSUE THREAD

**Issue by timburks** [APIs-guru/openapi-directory#733]
I've been assuming that files named "swagger.yaml" are OpenAPI 2 specs and "openapi.yaml" are OpenAPI 3.x.

But I notice that [this recently-added swagger.yaml](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/monarchinitiative.org/1.0.1/swagger.yaml) is `openapi: 3.0.0`

Is it appropriate to expect file names to reflect spec formats?

**Comment by timburks** [comment]
In case this is helpful, here are the apparent inconsistencies that I see:
```
$ find ./APIs -name "swagger.yaml" -exec egrep "^openapi:" {} \; -print
openapi: 3.0.0
APIs/id4i.de/0.9.7/swagger.yaml
openapi: 3.0.0
APIs/biapi.pro/2.0/swagger.yaml
openapi: 3.0.0
APIs/amadeus.com/2.2.0/swagger.yaml
openapi: 3.0.0
APIs/monarchinitiative.org/1.0.1/swagger.yaml
$ find ./APIs -name "openapi.yaml" -exec egrep "^swagger:" {} \; -print
swagger: "2.0"
APIs/elmah.io/v3/openapi.yaml
```

**Comment by MikeRalphson** [comment]
Having monitored this for a few update runs and newly added APIs, I think this is resolved now. Thanks again.
