### ISSUE TITLE
Add "NetBox" API

### ISSUE THREAD

**Issue by stgarf** [APIs-guru/openapi-directory#736]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://netboxdemo.com/api/swagger.json (this is a demo site running the [netbox](https://github.com/netbox-community/netbox) software)
**Name**: [NetBox](https://github.com/netbox-community/netbox)

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!

**Comment by stgarf** [comment]
Thanks for the blazing ⚡ fast response @MikeRalphson!

Any chance you can import the v2.4 version of this API as well? Here's the yaml I copied from an internal instance (and munged the `host` field (and extension to upload to github -- its still yaml)).


[swagger.yaml.txt](https://github.com/APIs-guru/openapi-directory/files/5383965/swagger.yaml.txt)

**Comment by MikeRalphson** [comment]
No problem, will push that commit when the previous CI job has finished. Thanks.
