### ISSUE TITLE
Add "Telnyx" API

### ISSUE THREAD

**Issue by odhranreidy** [APIs-guru/openapi-directory#738]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/team-telnyx/openapi/master/openapi/spec3.yml
**Name**: Telnyx

**Comment by MikeRalphson** [comment]
Thanks for the contribution!

Your API description very nearly passes validation, but your `callback` expressions need a tiny tweak:

```yaml
    post:
      callbacks:
        fax.delivered:
          ${response.body#/data/webhook_url}:
            post:
              requestBody:
```

should be:

```yaml
    post:
      callbacks:
        fax.delivered:
          '{$response.body#/data/webhook_url}':
            post:
              requestBody:
```

**Comment by odhranreidy** [comment]
Thanks for the feedback - that should be fixed now!

**Comment by MikeRalphson** [comment]
Thanks, looks good now. Will add when the current CI run finishes.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
