### ISSUE TITLE
Add "OpenAPI 3.0" API

### ISSUE THREAD

**Issue by imyjim** [APIs-guru/openapi-directory#740]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md
**Name**: OpenAPI 3.0

**Comment by MikeRalphson** [comment]
Thanks, but the OpenAPI specification isn't an API definition itself, so we can't add it to the directory.
