### ISSUE TITLE
jokes.one api is incorrect

### ISSUE THREAD

**Issue by gordallott** [APIs-guru/openapi-directory#743]
It's incorrect in the source, So I'm not sure what to do about that. Did my best to inform the source but they don't have great contact options. 

the response of `curl -X GET "https://api.jokes.one/jod" -H  "accept: application/json"` is:
```json
{
  "success": {
    "total": 1
  },
  "contents": {
    "jokes": [
      {
        "description": "Joke of the day ",
        "language": "en",
        "background": "",
        "category": "jod",
        "date": "2020-11-17",
        "joke": {
          "title": "Knock Knock - Howard who?",
          "lang": "en",
          "length": "98",
          "clean": "1",
          "racial": null,
          "date": "2020-11-17",
          "id": "iU88XXQb6g6ykf1ufALO6weF",
          "text": "Knock Knock\r\n Who's there?\r\n Howard!\r\n Howard who?\r\n Howard can it be to guess a Knock Knock joke?"
        }
      }
    ],
    "copyright": "2019-20 https://jokes.one"
  }
}
```

the swagger.json specifies the field `"joke"` as a `string`, but in reality something similar to the `Joke` definition 

I'm not sure what the process is here for just incorrect source apis. apologies

**Comment by MikeRalphson** [comment]
There are some instructions in [CONTRIBUTING.md](https://github.com/APIs-guru/openapi-directory/blob/master/CONTRIBUTING.md#amending-an-api-definition)... but I'm in the process of rewriting the scripts we use and so that's somewhat out of date. I'll attempt to get both the API definition and the instructions updated soon.

Thanks for reporting!

**Comment by MikeRalphson** [comment]
@orthosie you initially added this API to the directory, do you represent jokes.one? If so, could you comment on whether the API definition is correct?

**Comment by MikeRalphson** [comment]
Returning HTTP status 500 for me.

**Comment by orthosie** [comment]
Thank you for the note! This is fixed now.

**Comment by MikeRalphson** [comment]
@orthosie the API seems to be back up now, but could you comment on the disparity between what the OpenAPI definition says the response format should be and the actual response from the API?
