### ISSUE TITLE
Zenoti API Rate limit. 

### ISSUE THREAD

**Issue by mashray** [APIs-guru/openapi-directory#759]
Hi,

In the API doc (https://docs.zenoti.com/#rate-limiting) the rate limit is not mentioned clearly. When I am trying to trigger multiple API calls some calls are getting certificate issues and getting rejected.  Can you kindly provide what is the exact rate limit for zenoti API calls ??

**Comment by MikeRalphson** [comment]
I'm sorry, we don't have that information, we only collect and host API definitions, we don't have any information which isn't in the files themselves. You would need to contact the vendor direct.
