### ISSUE TITLE
Add "GazeCloudAPI" API

### ISSUE THREAD

**Issue by szydej** [APIs-guru/openapi-directory#761]
**Format**: API Blueprint
**Official**: YES
**Url**: https://gazerecorder.com/gazecloudapi/
**Name**: GazeCloudAPI

**Comment by MikeRalphson** [comment]
Thanks for the submission. The openapi-directory only caters for HTTP web APIs, not JavaScript / browser APIs. If I have misunderstood, and you have a machine-readable definition of your API(s), please let me know and I will re-open this issue.
