### ISSUE TITLE
Add "Ambee Weather API" API

### ISSUE THREAD

**Issue by Ambee01** [APIs-guru/openapi-directory#762]
**Format**: I/O Docs
**Official**: YES
**Url**: https://www.getambee.com/api/weather
**Name**: Ambee Weather API

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, WADL, Google Discovery format etc)? Without this unfortunately we cannot add the API to the directory.

**Comment by Ambee01** [comment]
HI Team,


PFA, HAR format for weather APIS

{
    "weather_latest" : {

        "geospatial": {
            "method": "GET",
            "url": "https://api.ambeedata.com/weather/latest/by-lat-lng",
            "httpVersion" : "HTTP/1.1",
            "headers" : [
              { "name": "x-api-key", "value": "API_KEY", "comment":
"Unique API key to identify your account"},
              { "name": "Content-type", "value": "application/json",
"comment": "Content type"}
            ],
            "queryString" : [
              { "name": "lat", "value": "12.9889055", "comment":
"Latitude of the location to search"},
              { "name": "lng", "value": "77.574044", "comment":
"Longitude of the location to search"}
            ]
        }
    },
        "weather_forecast" : {

        "geospatial": {
            "method": "GET",
            "url": "https://api.ambeedata.com/weather/forecast/by-lat-lng",
            "httpVersion" : "HTTP/1.1",
            "headers" : [
              { "name": "x-api-key", "value": "API_KEY", "comment":
"Unique API key to identify your account"},
              { "name": "Content-type", "value": "application/json",
"comment": "Content type"}
            ],
            "queryString" : [
              { "name": "lat", "value": "12.9889055", "comment":
"Latitude of the location to search"},
              { "name": "lng", "value": "77.574044", "comment":
"Longitude of the location to search"},
              { "name": "filter", "value": "{hourly|minutely|daily}",
"comment": "Averaging interval"}
            ]
        }
    },  "weather_history" : {

        "geospatial": {
            "method": "GET",
            "url": "https://api.ambeedata.com/weather/history/by-lat-lng",
            "httpVersion" : "HTTP/1.1",
            "headers" : [
              { "name": "x-api-key", "value": "API_KEY", "comment":
"Unique API key to identify your account"},
              { "name": "Content-type", "value": "application/json",
"comment": "Content type"}
            ],
            "queryString" : [
              { "name": "lat", "value": "12.9889055", "comment":
"Latitude of the location to search"},
              { "name": "lng", "value": "77.574044", "comment":
"Longitude of the location to search"},
              { "name": "from", "value": "2020-07-13 12:16:44", "comment":
"from date time"},
              { "name": "to", "value": "2020-07-14 12:16:44", "comment":
"to date time"}
            ]
        }
    }
}

Please do avoid taking such requests in the future unless necessary because
https://docs.ambeedata.com is more than sufficient for development.
