### ISSUE TITLE
Some logos are invalid - contain HTML

### ISSUE THREAD

**Issue by rbren** [APIs-guru/openapi-directory#763]
E.g. https://api.apis.guru/v2/cache/logo/http_mandrill.com_assets_images_brand_logo-vertical-light-735b5657.png

Probably good to check status code and content type of the response.

**Comment by MikeRalphson** [comment]
Hmm, we already check status code and that the media-type is `image/*` so I'll have to investigate some one-off scripts to see what has happened here. Thanks for the report.

**Comment by MikeRalphson** [comment]
http_1forge.com_logo.png
http_mandrill.com_assets_images_brand_logo-vertical-light-735b5657.png
https_visagecloud.com_visage-cloud-logo.png
https_www.doubleclickbygoogle.com_static_core_img_doubleclick-google-logo-wide.svg

**Comment by MikeRalphson** [comment]
Checks replicated in all current scripts.
