### ISSUE TITLE
Add "Portfolio Optimizer" API

### ISSUE THREAD

**Issue by lequant40** [APIs-guru/openapi-directory#764]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://docs.portfoliooptimizer.io/openapi/portfoliooptimizer.yaml
**Name**: Portfolio Optimizer

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!

**Comment by lequant40** [comment]
You're welcome, thanks to you 👍 !
