### ISSUE TITLE
Add "Corrently.io - Green Energy API" API

### ISSUE THREAD

**Issue by zoernert** [APIs-guru/openapi-directory#765]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://corrently.io/dist.yaml
**Name**: Corrently.io - Green Energy API

**Comment by MikeRalphson** [comment]
Thanks for the submission. Just checked your definition and our validator through up an issue:

>GET https://corrently.io/dist.yaml
expected Object { description: 'Device switching recommendation.', type: 'array' } to have property items
#/paths/~1gsi~1prediction/get/responses/200/content/application~1json/properties/matrix

**Comment by MikeRalphson** [comment]
We have patched the above issue. 

API added, many thanks for the contribution! It will be live on site once the CI run completes.
