### ISSUE TITLE
Add "ESG (Environmental, Social, Governance) API" API

### ISSUE THREAD

**Issue by ESGEnterprise** [APIs-guru/openapi-directory#767]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://www.esgenterprise.com/esg-analytics/esg-api-developer/
**Name**: ESG (Environmental, Social, Governance) API

**Comment by MikeRalphson** [comment]
Please could you provide the direct URL to your *machine-readable* API definition? Thanks.

**Comment by ESGEnterprise** [comment]
Mike,

Here is the URL to the machine-readable API def in JSON format.

https://www.esgenterprise.com/wp-content/api/ESGRatingAPI-Definition.json

Thanks.

**Comment by MikeRalphson** [comment]
Thanks for the link, I can see a few issues, on line 28 of your JSON file you have a trailing comma which shouldn't be there. And your `securitySchemes` object should be within a `components` object.

As you are `$ref`ing the entirety of `https://www.esgenterprise.com/wp-content/api/ESGRating.json` there should not be any `components/schemas` containing objects in this file. Alternatively the `$ref` could be specified as

```yaml
$ref: 'https://www.esgenterprise.com/wp-content/api/ESGRating.json#/components/schemas/ESGRating'
```

In the ESGRating file you have several properties with `type: double`. `double` is not a valid JSON Schema type. This should probably be:

```yaml
type: number
format: double
```

in each case.

`date` is also not a valid JSON Schema type, this should probably be:

```yaml
type: string
format: date
```

**Comment by ESGEnterprise** [comment]
Mike,

Sorry for the late reply. We fixed all the issues and please try again.

https://www.esgenterprise.com/wp-content/api/ESGRatingAPI-Definition.json

https://www.esgenterprise.com/wp-content/api/ESGRating.json


Thanks.

**Comment by MikeRalphson** [comment]
Thanks - hit a JSON issue parsing one of those documents:

> Flow map contains an unexpected , at line 12, column 26:

```json
        "social_score": {,
```

**Comment by ESGEnterprise** [comment]
Mike,

Thanks for pointing out the issue. I have fixed it, please try again.

**Comment by MikeRalphson** [comment]
Thanks for the fixes. API added, will be live on site when the CI run completes. Many thanks for the contribution!
