### ISSUE TITLE
amazonaws x-serviceName: pinpoint

### ISSUE THREAD

**Issue by shashankkumar88** [APIs-guru/openapi-directory#778]
https://github.com/APIs-guru/openapi-directory/blob/d485558c75fc99990e2b7d349b4646c1941e23c9/APIs/amazonaws.com/pinpoint/2016-12-01/openapi.yaml#L20

Correct service name seems to be mobiletargeting

**Comment by MikeRalphson** [comment]
Can you expand on why you think this should be changed?

**Comment by MikeRalphson** [comment]
Ok, have taken a look. `x-serviceName` is an internal property of the APIs.guru OpenAPI-directory to distinguish multiple APIs from one vendor. It is taken from the `metadata.endpointPrefix` property of the input definition.

I have added an `x-aws-signingName` property to the `info` section, which will be set if the input definition includes this information. Hopefully that helps. 

I'll close this once the next update of the AWS API definitions happens. Thanks for raising the issue.

**Comment by shashankkumar88** [comment]
I was actually testing this service and when passing the header 'servicename' as 'pinpoint', I got the response back that the expected header value is mobiletargeting.  Based on your comment, My assumption that the x-serviceName represents the servicename header that's needs to be passed to AWS service seems to be incorrect? Could you confirm if that's the case and which field maps to the servicename header?

**Comment by MikeRalphson** [comment]
Where specified by AWS there is now the new property `x-aws-signingName`:

https://github.com/APIs-guru/openapi-directory/blob/93e1ad7996ab4c45780b75d2ee69497df7c93f1b/APIs/amazonaws.com/pinpoint/2016-12-01/openapi.yaml#L21

If not present, and a value is still required, I guess you would take it from `x-serviceName`.

Thanks again for bringing up this issue.
