### ISSUE TITLE
Add "Shotstack" API

### ISSUE THREAD

**Issue by jeffski** [APIs-guru/openapi-directory#779]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://github.com/shotstack/oas-api-definition/blob/main/api.oas3.yaml
**Name**: Shotstack

**Comment by MikeRalphson** [comment]
Thanks for the suggestion, coincidentally I added this API last night!

https://github.com/APIs-guru/openapi-directory/blob/master/APIs/shotstack.io/v1/openapi.yaml

**Comment by jeffski** [comment]
Oh, haha, what timing! Thank you. Does this repo feed through to the https://any-api.com web site?

**Comment by MikeRalphson** [comment]
This repo is definitely one source for `any-api` but I'm not sure what their update cadence is like. Some recent APIs don't seem to be there. Maybe @rbren could say?

**Comment by rbren** [comment]
We actually sold AnyAPI to apilayer a while back, not sure how often they're pushing updates.

**Comment by MikeRalphson** [comment]
Thanks @rbren - didn't know that! Maybe then @milanlatinovic would know?

**Comment by jeffski** [comment]
Thanks for looking everyone. Appreciate the effort.

**Comment by milanlatinovic** [comment]
Hi @MikeRalphson, @rbren,
I am not involved in this project, but I have mentioned this thread to my peers. 
Sorry for not being able to provide more help.

**Comment by MikeRalphson** [comment]
@milanlatinovic Thanks so much, and no problem at all. If anyone needs to get hold of me, my contact details are in my GitHub profile.
