### ISSUE TITLE
Add "open banking LT" API

### ISSUE THREAD

**Issue by webrollygoal** [APIs-guru/openapi-directory#782]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: NO
**Url**: C:\Users\Hp\Desktop\swaggerdemo-master\src\main\resources\static\swagger-apis\api1\Swagger.json
**Name**: open banking LT

**Comment by MikeRalphson** [comment]
Thanks for the submission. The URL we need for an API description must be web-accessible, not a local path on your machine 😸 
Also, the word "demo" means we are unlikely to add this API to the directory.

Please feel free to chase this issue if I have misunderstood.
