### ISSUE TITLE
Add "Plate Recognizer" API

### ISSUE THREAD

**Issue by kytango** [APIs-guru/openapi-directory#783]
**Format**: 
**Official**: YES
**Url**: https://platerecognizer.com
**Name**: Plate Recognizer
**Category**: machine_learning
**Logo**: https://platerecognizer.com/wp-content/uploads/2020/07/plate-recognizer-alpr-anpr-logo.png

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, WADL, Google Discovery format etc)? Without this unfortunately we cannot add the API to the directory.

**Comment by kytango** [comment]
docs.platerecognizer.com


Does this help?
ᐧ

**Comment by MikeRalphson** [comment]
No, this is a directory of **machine-readable** API definitions, such as those in OpenAPI format. Please chase this issue if you have such a document.
