### ISSUE TITLE
Add "DaveAPI" API

### ISSUE THREAD

**Issue by dletorey** [APIs-guru/openapi-directory#784]
**Format**: OpenAPI 3.0
**Official**: NO
**Url**: https://api.code-red.uk
**Name**: DaveAPI
**Category**: text
**Logo**: https://code-red.uk/images/apple-touch-icon.png

**Comment by MikeRalphson** [comment]
> Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, WADL, Google Discovery format etc)? Without this unfortunately we cannot add the API to the directory.

That's how I close out issues! GitHub canned responses FTW. 

Thanks for testing.
