### ISSUE TITLE
Invalid schema (containing field "components")

### ISSUE THREAD

**Issue by hrennau** [APIs-guru/openapi-directory#786]
In the document `opensuse.org:obs` downloaded today (2021-03-09), an invalid payload schema was found, containing a field `components`.

Location:

`/paths/"/request/{id}?cmd=diff"/post/responses/200/content/"application/xml; charset=utf-8"/schema/components`

**Comment by MikeRalphson** [comment]
Still ok after this week's update. Closing. Thanks again.
