### ISSUE TITLE
Add "Markecheck Cars API" API

### ISSUE THREAD

**Issue by shisoderohit** [APIs-guru/openapi-directory#789]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://new-verticals-dot-marketcheck-gcp.uc.r.appspot.com/docs/
**Name**: Markecheck Cars API
**Category**: search
**Logo**: https://www.marketcheck.com/assets/logo-home.png

**Comment by MikeRalphson** [comment]
Source URL and API updated for the existing API in the directory. Thanks.
