### ISSUE TITLE
Add links to open spec in swagger-ui and swagger-editor

### ISSUE THREAD

**Issue by cbornet** [APIs-guru/openapi-directory#79]
It would be nice to have for each API buttons to directly open the spec in swagger-ui and swagger-editor
Example link for swagger-ui:
http://petstore.swagger.io/?url=https://apis-guru.github.io/api-models/apis-guru.github.io/1.0/swagger.json
Example link for swagger-editor:
http://editor.swagger.io/#/?import=https://apis-guru.github.io/api-models/apis-guru.github.io/1.0/swagger.json

**Comment by IvanGoncharov** [comment]
Great, idea I want to make it one step further and allow to submit such buttons in PRs
So we will add something like `3rd_party_buttons.yaml`:
```yaml
'swagger-ui': 'http://petstore.swagger.io/?url={swaggerUrl}'
'swagger-editor': 'http://editor.swagger.io/#/?import={swaggerUrl}'
```

**Comment by MikeRalphson** [comment]
Moved to [GitHub Pages repo #13](https://github.com/APIs-guru/APIs-guru.github.io/issues/13)

**Comment by rubywq** [comment]
Any update for this issue?

**Comment by MikeRalphson** [comment]
Please see the open issue at https://github.com/APIs-guru/APIs-guru.github.io/issues/13 - it's possible there may be some progress on this issue later in the year.
