### ISSUE TITLE
Add "FRC Events" API

### ISSUE THREAD

**Issue by Ewpratten** [APIs-guru/openapi-directory#796]
**Format**: Postman
**Official**: YES
**Url**: https://frc-api-docs.firstinspires.org/
**Name**: FRC Events
**Category**: open_data
**Logo**:

**Comment by Ewpratten** [comment]
I think this is also needed based on other addition requests here.

https://frc-api-docs.firstinspires.org/api/collections/13920602/TW6zHTEi?segregateAuth=true&versionTag=latest

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
