### ISSUE TITLE
Add "The Blue Alliance Read APIv3" API

### ISSUE THREAD

**Issue by Ewpratten** [APIs-guru/openapi-directory#797]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.thebluealliance.com/swagger/api_v3.json
**Name**: The Blue Alliance Read APIv3
**Category**: open_data
**Logo**:

**Comment by MikeRalphson** [comment]
Thanks for the submission. The API definition contains a "tight" circular reference (i.e. a `$ref` to the exact same spot in the document) which will never resolve.

```json
"components":
  "responses": {
      "Unauthorized": {
        "$ref": "#/components/responses/Unauthorized"
      },
  }
```

Are you affiliated with the API, in order to get this fixed?

**Comment by MikeRalphson** [comment]
Awesome, thanks! Let me know if you end up needing contact details for the API.

**Comment by MikeRalphson** [comment]
Issue resolved our side.  API added, many thanks for the contribution!
