### ISSUE TITLE
Add "Department of Veterans Affairs - Facilities API" API

### ISSUE THREAD

**Issue by matthewmilhoan** [APIs-guru/openapi-directory#800]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://developer.va.gov/explore/facilities/docs/facilities?version=current
**Name**: Department of Veterans Affairs - Facilities API
**Category**: location
**Logo**:

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
