### ISSUE TITLE
Add "Apptigent PowerTools" API

### ISSUE THREAD

**Issue by eshupps** [APIs-guru/openapi-directory#801]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://portal.apptigent.com/sites/portal.apptigent.com/files/v3-powertools-developer-2021-1-01.json
**Name**: Apptigent PowerTools
**Category**: tools
**Logo**: https://portal.apptigent.com/sites/portal.apptigent.com/files/api/powertools-developer.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
