### ISSUE TITLE
Add "COVID-19 Vaccine Status For USA" API

### ISSUE THREAD

**Issue by datachipio** [APIs-guru/openapi-directory#803]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://vaccinationstatus.azurewebsites.net/covid-vaccine-status/v1.0.0/swagger-ui.html,https://vaccinationstatus.azurewebsites.net/covid-vaccine-status/v1.0.0/usa/api/swagger-ui.html
**Name**: COVID-19 Vaccine Status For USA
**Category**: search
**Logo**: https://www.datachip.io

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
