### ISSUE TITLE
Update Spotify API definition

### ISSUE THREAD

**Issue by sonallux** [APIs-guru/openapi-directory#804]
The current openapi definition for Spotify is sourced from this official [spotify/web-api](https://github.com/spotify/web-api) repo, which has been archived and not been updated since **5 years**.

As the playlist endpoints have changed and a lot of new endpoints have been added to the Spotify Web API in the last 5 years, I have written a [parser](https://github.com/sonallux/spotify-web-api) to parse [Spotify's Web API reference documentation](https://developer.spotify.com/documentation/web-api/reference) into a machine-readable format. From this format I am also generating an openapi definition for Spotify. The latest version of the openapi definition can be found [in the releases](https://github.com/sonallux/spotify-web-api/releases/latest) or [here in the repo](https://github.com/sonallux/spotify-web-api/blob/master/spotify-web-api-generator-open-api/spotify-web-api-openapi.yml)

I would like to contribute my latest Spotify openapi definition to the openapi-directory. And ideally replace the current openapi definition for Spotify with my openapi definition. As I am new to the openapi-directory repo, I would appreciate any guidance on how to contribute my openapi definition to this project.

**Comment by MikeRalphson** [comment]
This is exactly the sort of contribution we are here for.

> As I am new to the openapi-directory repo, I would appreciate any guidance on how to contribute my openapi definition to this project.

I have updated the source URL to point to your (raw) github file, marked it as unofficial (third-party) and our scripts have done the rest. Congratulations on having a fully valid OAS definition!

The only addition I could suggest would be an `info.contact` section, either with your contact details or those for Spotify.

The definition will be live on the website as soon as the CI run completes.

Thank you again.
