### ISSUE TITLE
Add "VA Forms" API

### ISSUE THREAD

**Issue by matthewmilhoan** [APIs-guru/openapi-directory#809]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://developer.va.gov/explore/vaForms/docs/vaForms?version=current
**Name**: VA Forms
**Category**: forms
**Logo**: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.va.gov%2Fpittsburgh-health-care&psig=AOvVaw0lbB4LcBkckkpTqueNsYe5&ust=1617731341517000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJj-2oPV5-8CFQAAAAAdAAAAABAD

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
