### ISSUE TITLE
Add "VA Veteran Confirmation" API

### ISSUE THREAD

**Issue by matthewmilhoan** [APIs-guru/openapi-directory#810]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://developer.va.gov/explore/verification/docs/veteran_confirmation?version=current
**Name**: VA Veteran Confirmation
**Category**: tools
**Logo**: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.va.gov%2Fpittsburgh-health-care&psig=AOvVaw0lbB4LcBkckkpTqueNsYe5&ust=1617731341517000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJj-2oPV5-8CFQAAAAAdAAAAABAD

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
