### ISSUE TITLE
Add "COVID-19 Vaccine Status For Bresil" API

### ISSUE THREAD

**Issue by alavenimahender** [APIs-guru/openapi-directory#811]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://vaccinationstatus.azurewebsites.net/covid-vaccine-status/v1.0.0/brasil/api/swagger-ui.html
**Name**: COVID-19 Vaccine Status For Bresil
**Category**: monitoring
**Logo**: https://www.datachip.io

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
