### ISSUE TITLE
Add "COVID-19 Vaccine Status For Brasil" API

### ISSUE THREAD

**Issue by alavenimahender** [APIs-guru/openapi-directory#812]
**Format**: OpenAPI 3.0
**Official**: 
**Url**: https://vaccinationstatus.azurewebsites.net/covid-vaccine-status/v1.0.0/swagger-ui.html , https://vaccinationstatus.azurewebsites.net/covid-vaccine-status/v1.0.0/brasil/api/swagger-ui.html
**Name**: COVID-19 Vaccine Status For Brasil
**Category**: monitoring
**Logo**: https://www.datachip.io

**Comment by MikeRalphson** [comment]
Duplicate of #811
