### ISSUE TITLE
Add "Google My Business API" API

### ISSUE THREAD

**Issue by eminvegan** [APIs-guru/openapi-directory#815]
**Format**: Google API Discovery
**Official**: YES
**Url**: https://developers.google.com/my-business/samples/mybusiness_google_rest_v4p9.json
**Name**: Google My Business API
**Category**: location
**Logo**: https://www.google.com/images/icons/product/search-32.gif

**Comment by MikeRalphson** [comment]
Thanks. This URL has `samples` in it, is this definition definitely different to the APIs currently in the collection?

* https://github.com/APIs-guru/openapi-directory/tree/master/APIs/googleapis.com/mybusinessaccountmanagement/v1
* https://github.com/APIs-guru/openapi-directory/tree/master/APIs/googleapis.com/mybusinesslodging/v1

**Comment by eminvegan** [comment]
Yes it is completely different. This is the main Google My Business API Discovery document. It has the most important endpoints like locations, location reviews and more. The API's **mybusinessaccountmanagement/v1** and **mybusinesslodging/v1** are not the main API's

**Comment by MikeRalphson** [comment]
Thanks!

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
