### ISSUE TITLE
Add "DrChrono" API

### ISSUE THREAD

**Issue by tafelito** [APIs-guru/openapi-directory#816]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://drchrono.com/openapi-schema
**Name**: DrChrono
**Category**: customer_relation
**Logo**: https://www.drchrono.com/site_media/images/drchrono-dark.53a9fc1649a7.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
