### ISSUE TITLE
Add "IP geolocation API" API

### ISSUE THREAD

**Issue by Emmajperrez** [APIs-guru/openapi-directory#817]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://documentation.abstractapi.com/ip-geolocation-openapi.json
**Name**: IP geolocation API
**Category**: location
**Logo**: https://global-uploads.webflow.com/5ebbd0a566a3996636e55959/5ec2b974e578f93e553425eb_logo-dark.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
