### ISSUE TITLE
Add "PDF Blocks" API

### ISSUE THREAD

**Issue by cucho** [APIs-guru/openapi-directory#820]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://www.pdfblocks.com/assets/specs/pdfblocks.openapi.yaml
**Name**: PDF Blocks
**Category**: tools
**Logo**: https://www.pdfblocks.com/assets/images/pdfblocks-logo.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!

**Comment by cucho** [comment]
Thank you Mike!

**Comment by cucho** [comment]
@MikeRalphson what do I need to do to show my logo in the directory? It shows a "No logo yet" message. Thanks.

<img width="298" alt="image" src="https://user-images.githubusercontent.com/10786270/115805858-c8e73080-a3b3-11eb-9455-3c73881babc9.png">

**Comment by MikeRalphson** [comment]
Ah, my bad. Will update.

**Comment by MikeRalphson** [comment]
Thanks, updated now https://apis.guru/browse-apis/?q=pdfblocks

**Comment by cucho** [comment]
Thanks Mike!
