### ISSUE TITLE
Add "printAPI - Convert URL to PDF" API

### ISSUE THREAD

**Issue by ozeron** [APIs-guru/openapi-directory#821]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://pdfapi.alexlapchenko.com/api/swagger-json
**Name**: printAPI - Convert URL to PDF
**Category**: tools
**Logo**:  https://pdfapi.alexlapchenko.com/public/logo-350.png

**Comment by MikeRalphson** [comment]
Thanks for the submission. Unfortunately, your definition doesn't quite validate.

You have `security` requirement objects pointing to a `securityDefinition` called `ApiKeyAuth`:

```json
     "security": [
          {
            "ApiKeyAuth": []
          }
        ]
```

but your `securityDefinition` is not called `ApiKeyAuth`, it is called `api_key`:

```json
"securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "in": "header",
      "name": "X-RapidAPI-Proxy-Secret"
    }
  }
```

**Comment by MikeRalphson** [comment]
Ping @ozeron

**Comment by MikeRalphson** [comment]
Host is now unreachable.
