### ISSUE TITLE
Add "Spanish random words" API

### ISSUE THREAD

**Issue by AlexScigalszky** [APIs-guru/openapi-directory#822]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://palabras-aleatorias-public-api.herokuapp.com/
**Name**: Spanish random words
**Category**: text
**Logo**: https://palabras-aleatorias-public-api.herokuapp.com//icon.jpg
**Swagger**: https://palabras-aleatorias-public-api.herokuapp.com/swagger/ui/index.html
**OpenApi descriptor**: https://palabras-aleatorias-public-api.herokuapp.com/openapi3.json

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, WADL, Google Discovery format etc)? Without this unfortunately we cannot add the API to the directory.

I can see your OpenAPI document is embedded in https://palabras-aleatorias-public-api.herokuapp.com/swagger/ui/index.html/swagger-ui-init.js but we require a directly downloadable URL.

**Comment by AlexScigalszky** [comment]
Ohh dont worry, I will make a downloadable file. I the next days i'm going to update.

In the future, I going to add a tool to get the updated file.

**Comment by AlexScigalszky** [comment]
@MikeRalphson  It's ready.
I add this endpoint: https://palabras-aleatorias-public-api.herokuapp.com/openapi3.json to describe the API.

I'm here if you need something else

**Comment by MikeRalphson** [comment]
Thanks @AlexScigalszky - your definition is a mix of OpenAPI v3 and v2 syntax, v3 doesn't have a separate `schemes` field, it should have a `servers` array.

**Comment by AlexScigalszky** [comment]
Ohh! Sorry about that. I'm working on it

**Comment by AlexScigalszky** [comment]
@MikeRalphson It's done. I made all changes and test it with this endpoint:
[https://validator.swagger.io/validator/?url=https%3A%2F%2Fpalabras-aleatorias-public-api.herokuapp.com%2Fopenapi3.json](https://validator.swagger.io/validator/?url=https%3A%2F%2Fpalabras-aleatorias-public-api.herokuapp.com%2Fopenapi3.json)

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
