### ISSUE TITLE
Add "ClimateKuul" API

### ISSUE THREAD

**Issue by Usman-47** [APIs-guru/openapi-directory#833]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: http://api.climatekuul.com/api-docs
**Name**: ClimateKuul
**Category**: backend
**Logo**:

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!

**Comment by Usman-47** [comment]
its working with http, now its require https. is there any option to move it from https to http from your side.
and if want to make some change, how can i do.

**Comment by Usman-47** [comment]
aslo there is any option to delete it from your side?

**Comment by MikeRalphson** [comment]
Just update the definition at the same URL and we will pick up  the changes. Unless you want it deleted?
