### ISSUE TITLE
Add "CHANGE" API

### ISSUE THREAD

**Issue by sonianigam** [APIs-guru/openapi-directory#834]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://getchange.io
**Name**: CHANGE
**Category**: payment
**Logo**: https://change-brand-assets.s3-us-west-1.amazonaws.com/deltamark.svg
**OpenAPI**: https://change-api-definition.s3-us-west-1.amazonaws.com/swagger.yaml

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
