### ISSUE TITLE
Add "Sms77" API

### ISSUE THREAD

**Issue by matthiez** [APIs-guru/openapi-directory#836]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/sms77io/api-schemes/master/json/openapi.json
**Name**: Sms77
**Category**: telecom
**Logo**: https://www.sms77.io/wp-content/uploads/integrationen_sms77_logo.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
