### ISSUE TITLE
Add "Orbit" API

### ISSUE THREAD

**Issue by martyndavies** [APIs-guru/openapi-directory#837]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://app.orbit.love/api-docs/v1/swagger.json
**Name**: Orbit
**Category**: customer_relation
**Logo**: https://avatars.githubusercontent.com/u/55637052?s=200&v=4

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
