### ISSUE TITLE
Add "CyCAT - The Cybersecurity Resource Catalogue public API services." API

### ISSUE THREAD

**Issue by adulau** [APIs-guru/openapi-directory#838]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://api.cycat.org/swagger.json
**Name**: CyCAT - The Cybersecurity Resource Catalogue public API services.
**Category**: security
**Logo**: https://cycat.org/images/illustrations/pointing.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
