### ISSUE TITLE
Add "CIRCL file hash lookup" API

### ISSUE THREAD

**Issue by adulau** [APIs-guru/openapi-directory#839]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://hashlookup.circl.lu/swagger.json
**Name**: CIRCL file hash lookup
**Category**: security
**Logo**: https://www.circl.lu/assets/images/circl-logo.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
