### ISSUE TITLE
Add "Bulk WHOIS API" API

### ISSUE THREAD

**Issue by pbudzik** [APIs-guru/openapi-directory#840]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://apispot.io/static/whois.yml
**Name**: Bulk WHOIS API
**Category**: hosting
**Logo**: https://s3.amazonaws.com/rapidapi-prod-user/e7a9c6f8-f01f-4dca-8fda-68f7424ad817

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
