### ISSUE TITLE
Add "Redeal Analytics API" API

### ISSUE THREAD

**Issue by johansc** [APIs-guru/openapi-directory#841]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://static.redeal.se/APIDefinitions/analytics.redeal.io-1.0.0-swagger.yaml
**Name**: Redeal Analytics API
**Category**: analytics
**Logo**: https://static.redeal.se/APIDefinitions/re-deal-logo-cmyk_1.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
