### ISSUE TITLE
Add "NOWPayments" API

### ISSUE THREAD

**Issue by paulinelnowpayments** [APIs-guru/openapi-directory#843]
**Format**: Postman Collection
**Official**: YES
**Url**: ~~https://documenter.getpostman.com/view/7907941/S1a32n38~~
**Url**: https://www.postman.com/collections/7907941-9f217404-4263-42ad-b6b1-03a3d95b7d22-S1a32n38
**Name**: NOWPayments
**Category**: payment
**Logo**: https://drive.google.com/file/d/1sOCQr76FWqlFjIPPg56LoO0PKSj0Cd0c/view

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!

**Comment by paulinelnowpayments** [comment]
Hi Mike,

Thanks very much! Cannot find the API on the website though, could you help
me with that?

Kind regards,
Pauline L.
Junior Marketing Manager
NOWPayments

ср, 23 июн. 2021 г. в 11:50, Mike Ralphson ***@***.***>:

**Comment by MikeRalphson** [comment]
We had a hiccup in the CI process which updates the website, should be resolved within the next hour.

**Comment by paulinelnowpayments** [comment]
Great, thanks!

And also I'm interested in any-apy.com website, it says that you are
related. Are we going to list there as well automatically?

Thank you!

ср, 23 июн. 2021 г. в 13:17, Mike Ralphson ***@***.***>:

**Comment by MikeRalphson** [comment]
There now. https://apis.guru/?q=nowpayments

`any-api.com` used to take the data from us but they have not updated in some considerable while. We're trying to schedule a call with the new owners.

**Comment by paulinelnowpayments** [comment]
Awesome, thank you so much!

Could you please share the contacts of the new owners? Or maybe just let me
know who they are?

ср, 23 июн. 2021 г. в 15:08, Mike Ralphson ***@***.***>:

**Comment by MikeRalphson** [comment]
Hi, yes it is apilayer.com

**Comment by paulinelnowpayments** [comment]
ah thanks! yeah, they're not replying to me

ср, 23 июн. 2021 г. в 15:53, Mike Ralphson ***@***.***>:
