### ISSUE TITLE
Add "Billingo" API

### ISSUE THREAD

**Issue by marceldarvas** [APIs-guru/openapi-directory#844]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://api.swaggerhub.com/apis/Billingo/Billingo/3.0.7
**Name**: Billingo
**Category**: financial
**Logo**: https://www.billingo.hu/images/billingo_logo.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
