### ISSUE TITLE
Add "Taggun" API

### ISSUE THREAD

**Issue by Hannahroseoc** [APIs-guru/openapi-directory#846]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.taggun.io/docs/swagger.json
**Name**: Taggun
**Category**: financial
**Logo**: https://www.taggun.io/wp-content/uploads/2019/04/logo-big.png

**Comment by MikeRalphson** [comment]
Thanks for the contribution. This API is already in the directory.

https://apis.guru/?q=taggun
https://github.com/APIs-guru/openapi-directory/tree/main/APIs/taggun.io/1.5.52
