### ISSUE TITLE
uri encoding error ?

### ISSUE THREAD

**Issue by seriousme** [APIs-guru/openapi-directory#849]
Hi,

there seems to be some trouble with the URI encoding in the Open Build Service API e.g:

https://github.com/APIs-guru/openapi-directory/blob/d1ff11d6ea9a382b2d4e2c1590beb27df1f8ef38/APIs/opensuse.org/obs/2.10.50/openapi.yaml#L318-L330

Trying to parse the YAML to JSON and then checking the JSON against schema results in validation errors since the YAML encoded URI is not considered a valid URI.

Similarly:
https://github.com/APIs-guru/openapi-directory/blob/1a0715de37d6daf01109061e966f5337cfc0442a/APIs/brex.io/2021.12/openapi.yaml#L82-L84

https://github.com/APIs-guru/openapi-directory/blob/1a0715de37d6daf01109061e966f5337cfc0442a/APIs/conjur.local/5.1.1/openapi.yaml#L134-L144
although some $refs are ok here, some are not 

and:
https://api.apis.guru/v2/specs/nexmo.com/application.v2/2.1.0/openapi.yaml
https://api.apis.guru/v2/specs/rev.ai/v1/openapi.yaml
https://api.apis.guru/v2/specs/surevoip.co.uk/9dcb0dc8/openapi.yaml

Kind regards,
Hans

**Comment by MikeRalphson** [comment]
I have concentrated on the `brex.io` example as in the other cases it's not exactly clear which `$ref` you think there is a problem with.

Also, can you explain what you mean by "YAML encoding"?

`$ref: "#/paths/~1api~1v1~1system~1countries/get/responses/default"` is encoded according to the [JSON Pointer specification](https://datatracker.ietf.org/doc/html/rfc6901#section-3) and looks exactly the same in the [JSON version](https://api.apis.guru/v2/specs/brex.io/2021.12/openapi.json):

`"$ref": "#/paths/~1api~1v1~1system~1countries/get/responses/default"`

**Comment by seriousme** [comment]
Hi,

thanks for the reply. It is indeed a JSON pointer and has nothing to do with YAML. 
(I think I saw too much YAML when I wrote that)

I found a JSON pointer in my error log so I (incorrectly) assumed the issue was with JSON pointers in general but I could not figure out why, hence the question mark in the issue title.

After your reply and doing some more digging I found: 

https://github.com/APIs-guru/openapi-directory/blob/b4f769ea567ae157352f4dc14c0ac4f753d67af1/APIs/opensuse.org/obs/2.10.50/openapi.yaml#L326-L329
The problem here seems to be the `; charset=utf-8/schema`

https://github.com/APIs-guru/openapi-directory/blob/b4f769ea567ae157352f4dc14c0ac4f753d67af1/APIs/brex.io/2021.12/openapi.yaml#L276-L279

The problem here seems to be the curly brackets that seem to require to be encoded as: `~1api~1v1~1company~1search~1name~1%7Bcountry%7D~1%7Bname%7D`
which also would explain the error on:

https://github.com/APIs-guru/openapi-directory/blob/1a0715de37d6daf01109061e966f5337cfc0442a/APIs/conjur.local/5.1.1/openapi.yaml#L141-L144

https://github.com/APIs-guru/openapi-directory/blob/main/APIs/nexmo.com/application.v2/2.1.0/openapi.yaml#L441
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/rev.ai/v1/openapi.yaml#L332
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/surevoip.co.uk/9dcb0dc8/openapi.yaml#L583

Kind regards,
Hans

**Comment by MikeRalphson** [comment]
Ok, thanks, that makes sense. `oas-kit` isn't currently replacing a `$ref` value it understands but isn't in the form it would construct. That should be a reasonably easy fix.

**Comment by MikeRalphson** [comment]
@seriousme what kind of URI parser are you using to validate the `$ref` values? (Or what kind of URI validation is your JSON Schema validator doing?) The WHATWG standard suggests that spaces **do** need to be encoded, but the only other characters that need to be encoded in a fragment id are:

> The C0 control percent-encode set are the C0 controls and all code points greater than U+007E (~).
>
> The fragment percent-encode set is the C0 control percent-encode set and U+0020 SPACE, U+0022 ("), U+003C (<), U+003E (>), and U+0060 (`).

**Comment by seriousme** [comment]
@MikeRalphson 
I'm using the `uri-reference` format of [ajv-formats](https://github.com/ajv-validator/ajv-formats) which is part of Mozilla sponsored [AJV](https://ajv.js.org/)

ajv-formats has 2 regexps for `uri-reference`:
- a full format: https://github.com/ajv-validator/ajv-formats/blob/master/src/formats.ts#L52
- a fast format: https://github.com/ajv-validator/ajv-formats/blob/master/src/formats.ts#L102

The fast format rexexp basically says that fragements cannot contain whitespace and thats about it.
The full fomat rexexp is a bit too complex for me.

The OAS standards reference RFC3986 via JSON reference draft 02 (swagger) and draft 03 (OAS 3.0.0 and OAS 3.1.0).
And like the WhatWG says:  RFC3986 is not very clear on what is acceptable and what not :-(

I tried Smartbear's [Swagger Editor](https://editor.swagger.io/) that also complains about the curly braces not being RFC3986 compliant.

Kind regards,
Hans

Kind regards,
Hans

**Comment by MikeRalphson** [comment]
@seriousme I think you're right, as OAS references RFC3986 not WHATWG, we should be conservative in what we produce.

The issues you identified above should now be fixed. Any others should get mopped up in next Monday's update run.

**Comment by seriousme** [comment]
Thx 👍
