### ISSUE TITLE
Add "DynamicDocs" API

### ISSUE THREAD

**Issue by Rodionov5** [APIs-guru/openapi-directory#850]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://advicement.io/open_api_spec/dynamicdocs.json
**Name**: DynamicDocs
**Category**: developer_tools
**Logo**: https://advicement.io/images/logo/Advicement_DynamicDocs_API.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.

**Comment by Rodionov5** [comment]
Hi Mike, 
We actually stuffed up our submission and included our support page URL. Any chance we can change it to our landing page: 
[https://advicement.io/dynamic-documents-api](https://advicement.io/dynamic-documents-api)?
Also, we checked the website and our logo doesn't seem to be working on the site: [https://apis.guru/?q=dynamicdocs](https://apis.guru/?q=dynamicdocs). Not sure how we can fix that. 

Apologies for the inconvenience caused. 
Igor

**Comment by MikeRalphson** [comment]
Hi Igor, which field has the support page URL which needs updating to the landing page one? If you can update your source OpenAPI document, we will automatically pull in the change.

I'll take a look at the logo issue.

**Comment by Rodionov5** [comment]
Great. Many thanks. We have updated the URL in the source OpenAPI document.

**Comment by MikeRalphson** [comment]
Latest OpenAPI document pulled in. CI is running now to update the website. Thanks.
