### ISSUE TITLE
Add "Tafqit" API

### ISSUE THREAD

**Issue by postscripter** [APIs-guru/openapi-directory#853]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://tafqit.herokuapp.com/open_api/TafqitOpenAPI.json
**Name**: Tafqit
**Category**: developer_tools
**Logo**: https://tafqit.com/assets/logo-69c6f503c54101a8a05bfceb9a7d6f1a96f22bd4aa3a4f72d9ad5a8ab0a2a951.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
