### ISSUE TITLE
Add "iCUE Growth Service" API

### ISSUE THREAD

**Issue by iCUE-Solutions** [APIs-guru/openapi-directory#854]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.i-cue.solutions/swagger/v1/swagger.json
**Name**: iCUE Growth Service
**Category**: analytics
**Logo**: https://api.i-cue.solutions/icue/icue_logo_2.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
