### ISSUE TITLE
Add "ETSI GS MEC 010-2 - Part 2: Application lifecycle, rules and requirements management" API

### ISSUE THREAD

**Issue by geokal** [APIs-guru/openapi-directory#855]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://forge.etsi.org/rep/mec/gs010-2-app-pkg-lcm-api/raw/v2.1.1/MEC010-2_AppPkgMgmt.yaml
**Name**: ETSI GS MEC 010-2 - Part 2: Application lifecycle, rules and requirements management
**Category**: telecom
**Logo**:

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
