### ISSUE TITLE
Add "Gambit Communications MIMIC simulator REST API" API

### ISSUE THREAD

**Issue by gambitcomminc** [APIs-guru/openapi-directory#857]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://www.gambitcomm.com/docs/mimic.yaml
**Name**: Gambit Communications MIMIC simulator REST API
**Category**: iot
**Logo**: https://www.gambitcomm.com/site/images/logo.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
