### ISSUE TITLE
Add "resertrip" API

### ISSUE THREAD

**Issue by ransilad** [APIs-guru/openapi-directory#86]
**Format**: Swagger 1.x
**Official**: NO
**Url**: http://sandbox.api.resertrip.com
**Name**: resertrip

**Comment by IvanGoncharov** [comment]
@ransilad Thank you for submission.

> Official: NO

Based on URL it looks official to me.
By `official` I mean it was created by API owner.
Should I mark it as official?

> Url: http://sandbox.api.resertrip.com

I want to correctly mark language, is it in Spanish?

P.S. It will be first non-English API in our collection :smile:

**Comment by sanchojaf** [comment]
Hi Ivan. Yes, this is Spanish

**Comment by MikeRalphson** [comment]
@ransilad could you confirm if this is an official API definition?

**Comment by MikeRalphson** [comment]
resertrip.com seems to be gone. Please feel free to re-open this issue if that's not the case.
