### ISSUE TITLE
Add "Connected Device Discovery and Vulnerability Assessment (IoTVAS)" API

### ISSUE THREAD

**Issue by befoulad** [APIs-guru/openapi-directory#861]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://iotvas-api.firmalyzer.com/api/v1/openapi.json
**Name**: Connected Device Discovery and Vulnerability Assessment (IoTVAS)
**Category**: security
**Logo**:

**Comment by MikeRalphson** [comment]
Thanks for the submisison. Your API definition contains one small validation error. The keys within `components` maps (such as the `securityScheme` "API key header") cannot contain spaces. If you could change all occurrences to `API-key-header` or `API_key_header` this would solve the problem.

**Comment by befoulad** [comment]
changed to api-key-header

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
