### ISSUE TITLE
Add "IBAN API" API

### ISSUE THREAD

**Issue by samymassoud** [APIs-guru/openapi-directory#864]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.ibanapi.com/docs/api-docs.json
**Name**: IBAN API
**Category**: financial
**Logo**:

**Comment by MikeRalphson** [comment]
There are a number of validation errors in this API definition, preventing us from adding it.

https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fapi.ibanapi.com%2Fdocs%2Fapi-docs.json

**Comment by samymassoud** [comment]
All validation errors were taken care of, please retry.

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
