### ISSUE TITLE
Add "Regulation Technologies" API

### ISSUE THREAD

**Issue by mikeoaten123** [APIs-guru/openapi-directory#871]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://demo.api.regulationtechnologies.com/swagger/v1/swagger.json
**Name**: Regulation Technologies
**Category**: open_data
**Logo**:

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
