### ISSUE TITLE
Add "TCGdex" API

### ISSUE THREAD

**Issue by Aviortheking** [APIs-guru/openapi-directory#877]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.tcgdex.net/v2/openapi.yaml
**Name**: TCGdex
**Category**: entertainment
**Logo**: https://www.tcgdex.net/assets/logo.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
