### ISSUE TITLE
Add "EmailVerify" API

### ISSUE THREAD

**Issue by tomemmerson** [APIs-guru/openapi-directory#880]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://paypi-default-images.s3.eu-west-1.amazonaws.com/openapi.yaml
**Name**: EmailVerify
**Category**: email
**Logo**: https://paypi-default-images.s3.eu-west-1.amazonaws.com/EV-Img.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
