### ISSUE TITLE
Add "MeiliSearch" API

### ISSUE THREAD

**Issue by bb** [APIs-guru/openapi-directory#881]
**Format**: Postman Collection
**Official**: YES
**Url**: https://raw.githubusercontent.com/meilisearch/documentation/master/.vuepress/public/postman/meilisearch-collection.json
**Name**: MeiliSearch
**Category**: search
**Logo**: https://www.meilisearch.com/_nuxt/img/cf59975.svg

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
