### ISSUE TITLE
Add "siemonster" API

### ISSUE THREAD

**Issue by dedhyacinthe** [APIs-guru/openapi-directory#883]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://192.168.137.207:8090
**Name**: siemonster
**Category**: machine_learning
**Logo**:

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.

We can't reach a private 192.168.x.x IP address.
