### ISSUE TITLE
Add "Amadeus Location Score" API

### ISSUE THREAD

**Issue by rfsubroto** [APIs-guru/openapi-directory#890]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://raw.githubusercontent.com/amadeus4dev/amadeus-open-api-specification/main/spec/json/LocationScore_v1_swagger_specification.json
**Name**: Amadeus Location Score
**Category**: entertainment
**Logo**: https://developers.amadeus.com/PAS-EAS/api/v1/cms-gateway/sites/default/files/2019-09/logo-portal.png

**Comment by MikeRalphson** [comment]
@rfsubroto - Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
