### ISSUE TITLE
Add "Amadeus Trip Parser" API

### ISSUE THREAD

**Issue by rfsubroto** [APIs-guru/openapi-directory#896]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://raw.githubusercontent.com/amadeus4dev/amadeus-open-api-specification/main/spec/json/TripParser_v3_swagger_specification.json
**Name**: Amadeus Trip Parser
**Category**: transport
**Logo**: https://developers.amadeus.com/PAS-EAS/api/v1/cms-gateway/sites/default/files/2019-09/logo-portal.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.
