### ISSUE TITLE
Add "Amadeus AI-Generated Photos" API

### ISSUE THREAD

**Issue by rfsubroto** [APIs-guru/openapi-directory#907]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://raw.githubusercontent.com/amadeus4dev/amadeus-open-api-specification/main/spec/json/AIGeneratedPhotos_v2_swagger_specification.json
**Name**: Amadeus AI-Generated Photos
**Category**: entertainment
**Logo**: https://developers.amadeus.com/PAS-EAS/api/v1/cms-gateway/sites/default/files/2019-09/logo-portal.png

**Comment by MikeRalphson** [comment]
@rfsubroto - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check --host undefined https://raw.githubusercontent.com/amadeus4dev/amadeus-open-api-specification/main/spec/json/AIGeneratedPhotos_v2_swagger_specification.json

https://raw.githubusercontent.com/amadeus4dev/amadeus-open-api-specification/main/spec/json/AIGeneratedPhotos_v2_swagger_specification.json F 404 
Saving metadata...
Exiting with 1

**Comment by MikeRalphson** [comment]
@rfsubroto - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check --host undefined https://raw.githubusercontent.com/amadeus4dev/amadeus-open-api-specification/main/spec/json/AIGeneratedPhotos_v2_swagger_specification.json

https://raw.githubusercontent.com/amadeus4dev/amadeus-open-api-specification/main/spec/json/AIGeneratedPhotos_v2_swagger_specification.json F 404 
Saving metadata...
Exiting with 1

**Comment by MikeRalphson** [comment]
@rfsubroto - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check --host undefined https://raw.githubusercontent.com/amadeus4dev/amadeus-open-api-specification/main/spec/json/AIGeneratedPhotos_v2_swagger_specification.json

https://raw.githubusercontent.com/amadeus4dev/amadeus-open-api-specification/main/spec/json/AIGeneratedPhotos_v2_swagger_specification.json F 404 
Saving metadata...
Exiting with 1
