### ISSUE TITLE
Add "ticketing-api" API

### ISSUE THREAD

**Issue by joliva-ob** [APIs-guru/openapi-directory#91]
**Format**: API Blueprint
**Official**: YES
**Url**: http://docs.oneboxticketingapi.apiary.io/
**Name**: ticketing-api

**Comment by IvanGoncharov** [comment]
@joliva-ob Thank you for submissions.

Sadly your API Blueprint files crash converter that I use:
https://github.com/lucybot/api-spec-converter
I will try to make fix ASAP but it could take me a couple of days.

**Comment by MikeRalphson** [comment]
As per #92
