### ISSUE TITLE
Add "Amadeus Flight Inspiration Search" API

### ISSUE THREAD

**Issue by rfsubroto** [APIs-guru/openapi-directory#915]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://raw.githubusercontent.com/amadeus4dev/amadeus-open-api-specification/main/spec/json/FlightInspirationSearch_v1_swagger_specification.json
**Name**: Amadeus Flight Inspiration Search
**Category**: search
**Logo**: https://developers.amadeus.com/PAS-EAS/api/v1/cms-gateway/sites/default/files/2019-09/logo-portal.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
