### ISSUE TITLE
Add "JSON2Video" API

### ISSUE THREAD

**Issue by qcardona** [APIs-guru/openapi-directory#933]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://json2video.com/docs/api/json2video-api.json
**Name**: JSON2Video
**Category**: developer_tools
**Logo**: https://json2video.com/images/json2video-logo.png

**Comment by qcardona** [comment]
Please, add a link on the title to the API home page: https://json2video.com

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
