### ISSUE TITLE
Add "LinQR" API

### ISSUE THREAD

**Issue by kubasaw** [APIs-guru/openapi-directory#935]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://linqr.app/openapi/openapi.json
**Name**: LinQR
**Category**: tools
**Logo**: https://linqr.app/assets/apple-touch-icon-144x144.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
