### ISSUE TITLE
Error in Adyen API's ?

### ISSUE THREAD

**Issue by seriousme** [APIs-guru/openapi-directory#936]
Hi,

I have tried to validate 

https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/CheckoutService/68/openapi.yaml
using:
https://raw.githubusercontent.com/OAI/OpenAPI-Specification/gh-pages/oas/3.1/schema/2021-09-28

Looking at the Adyen spec (OpenAPI 3.1.0 format) it contains:
https://github.com/APIs-guru/openapi-directory/blob/d747281b4343ef5b6373d81c5461575ed6d3741c/APIs/adyen.com/CheckoutService/68/openapi.yaml#L13053-L13054

Which does not seem to be allowed by the spec.
AJV gives me [an error](https://github.com/seriousme/openapi-schema-validator/blob/master/test/realworld/failed.md#api-adyencomcheckoutservice-version-68):

Keyword | Params | Message
-- | -- | --
unevaluatedProperties | {"unevaluatedProperty":"source"} | must NOT have unevaluated properties

And https://json-schema.hyperjump.io/ gives me: `# fails schema constraint https://spec.openapis.org/oas/3.1/schema/2021-09-28#/unevaluatedProperties`

Same holds for: 
- https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/PaymentService/68/openapi.yaml
- https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/PayoutService/68/openapi.yaml
- https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/RecurringService/68/openapi.yaml

Kind regards,
Hans

**Comment by MikeRalphson** [comment]
This should be fixed from tonight. I'll keep an eye on your results page.

**Comment by seriousme** [comment]
Many thanks for maintaining this site !

**Comment by seriousme** [comment]
FYI: I just triggered the report manually this morning as it only runs once a week on Thursday. 
40 out of 56 API errors have been fixed by your update :-)  
Just let me know if you want me to trigger it again manually.
