### ISSUE TITLE
Add "Open DeFi API" API

### ISSUE THREAD

**Issue by miohtama** [APIs-guru/openapi-directory#937]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://tradingstrategy.ai/api/onchain/open-defi-api.yaml
**Name**: Open DeFi API
**Category**: financial
**Logo**: https://raw.githubusercontent.com/tradingstrategy-ai/frontend/master/src/lib/assets/logo-two-lines.svg

This is an API to get OHLCV candle chart data for decentralised exchanges.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
