### ISSUE TITLE
Add "Zip Code Data API" API

### ISSUE THREAD

**Issue by ricardo-rangel-velasquez** [APIs-guru/openapi-directory#943]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://www.metadapi.com/Portals/0/ApiModels/Zipcode.json
**Name**: Zip Code Data API
**Category**: location
**Logo**: https://www.metadapi.com/Portals/0/metadapi_logot.png

**Comment by MikeRalphson** [comment]
@ricardo-rangel-velasquez - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check --host undefined https://www.metadapi.com/Portals/0/ApiModels/Zipcode.json

https://www.metadapi.com/Portals/0/ApiModels/Zipcode.json FRV
component name invalid
#/components/securitySchemes/Subscription Key
 ✗ 
undefined
Saving metadata...
Exiting with 1
