### ISSUE TITLE
Add "XTRF" API

### ISSUE THREAD

**Issue by netsatan** [APIs-guru/openapi-directory#948]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://presentation.s.xtrf.eu/home-api/openapi.json
**Name**: XTRF
**Category**: project_management
**Logo**: https://xtrf.eu/wp-content/uploads/2021/03/XTRFlogo-default.png

**Comment by MikeRalphson** [comment]
Given URL 404s, please can you check?

**Comment by netsatan** [comment]
@MikeRalphson Thanks for noticing that, can you please try this one: https://presentation.s.xtrf.eu/home-api/openapi.json ?

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
