### ISSUE TITLE
Add "regression" API

### ISSUE THREAD

**Issue by scideassoftware** [APIs-guru/openapi-directory#950]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://services.scideas.net/regression/resources/openapi3.0.0-regression-1.0.json
**Name**: regression
**Category**: machine_learning
**Logo**: https://scideas.net/media/logos/VenLogo2.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
