### ISSUE TITLE
Add "ProxyKingdom" API

### ISSUE THREAD

**Issue by bokklu** [APIs-guru/openapi-directory#961]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.proxykingdom.com/swagger/v1/swagger.json
**Name**: ProxyKingdom
**Category**: developer_tools
**Logo**: https://i.imgur.com/b7lgaVN.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
