### ISSUE TITLE
Update Spotify OpenAPI

### ISSUE THREAD

**Issue by sonallux** [APIs-guru/openapi-directory#962]
I am currently providing the OpenAPI definition for Spotify (see #804). As Spotify has released its own OpenAPI definition at the end of last year, I think the link/url must be updated.

The official OpenAPI definition for the Spotify Web API can be found here: https://developer.spotify.com/_data/documentation/web-api/reference/open-api-schema.yml
Unfortunately, there are some errors in this definition. Therefore I am now providing an improved version that is based on the official OpenAPI definition and contains some fixes and improvements: https://github.com/sonallux/spotify-web-api/blob/main/fixed-spotify-open-api.yml

I hope there is some way to have both OpenAPI definitions listed.

**Comment by MikeRalphson** [comment]
Thanks! Both API definitions should be present from tonight.
