### ISSUE TITLE
Add "Thremapi" API

### ISSUE THREAD

**Issue by todorolev** [APIs-guru/openapi-directory#963]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.thremapi.com:8443/api-docs
**Name**: Thremapi
**Category**: security
**Logo**: https://thremapi.com/img/logo.png

**Comment by MikeRalphson** [comment]
URL given times out. Can you check?

**Comment by todorolev** [comment]
Thanks, this API was decommissioned few months ago. I'm closing the issue.
