### ISSUE TITLE
Add "Inflation Rate Around the World" API

### ISSUE THREAD

**Issue by Emisoft12** [APIs-guru/openapi-directory#967]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://rapidapi.com/belchiorarkad@gmail.com/api/inflation-rate-around-the-world/
**Name**: Inflation Rate Around the World
**Category**: backend
**Logo**: https://rapidapi.com/cdn/images?url=https://rapidapi-prod-apis.s3.amazonaws.com/23ca582d-67c4-47bc-b889-032943604050.png

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.
