### ISSUE TITLE
Add "Taxes and Social Security Rates" API

### ISSUE THREAD

**Issue by Emisoft12** [APIs-guru/openapi-directory#968]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://rapidapi.com/belchiorarkad@gmail.com/api/taxes-and-social-security-rates/
**Name**: Taxes and Social Security Rates
**Category**: payment
**Logo**: https://rapidapi.com/cdn/images?url=https://rapidapi-prod-apis.s3.amazonaws.com/1471d421-291e-4753-a6d1-2c50654178cb.png

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.
