### ISSUE TITLE
Add "flamegraph.com rest API" API

### ISSUE THREAD

**Issue by abeaumont** [APIs-guru/openapi-directory#970]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://flamegraph.com/openapi/api.yaml
**Name**: flamegraph.com REST API
**Category**: developer_tools
**Logo**: https://flamegraph.com/logo.svg

**Comment by MikeRalphson** [comment]
@abeaumont - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://flamegraph.com/openapi/api.yaml

https://flamegraph.com/openapi/api.yaml FRUV
expected Object { url: 'https://www.apache.org/licenses/LICENSE-2.0' } to have key name
	missing keys: name
#/info/license
 ✗ 
flamegraph.com
Saving metadata...
Exiting with 1
