### ISSUE TITLE
Repository cannot be cloned on Windows

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#974]
Similar to #806, but caused by another file.

```
> git clone https://github.com/APIs-guru/openapi-directory.git --depth 1
Cloning into 'openapi-directory'...
remote: Enumerating objects: 10027, done.
remote: Counting objects: 100% (10027/10027), done.
remote: Compressing objects: 100% (2760/2760), done.
Receiving objects: 100% (10027/10027), 36.36 MiB | 1.06 MiB/s, done.
remote: Total 10027 (delta 2492), reused 8199 (delta 1530), pack-reused 0
Resolving deltas: 100% (2492/2492), done.
error: invalid path 'APIs/statsocial.com/1.0.0./openapi.yaml'      <---------------------------
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

The file mentioned in the error message (`APIs/statsocial.com/1.0.0./openapi.yaml`) is in the folder named `1.0.0.` with a dot at the end. Such folder names are [not allowed on Windows](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions):
> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not.

**Comment by MikeRalphson** [comment]
Should be fixed by tonight. Thanks for raising the issue.
