### ISSUE TITLE
Add "perfectpdf" API

### ISSUE THREAD

**Issue by scideassoftware** [APIs-guru/openapi-directory#975]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://services.scideas.net/perfectpdf/resources/openapi3.0.0-perfectpdf-1.0.json
**Name**: perfectpdf
**Category**: tools
**Logo**: https://scideas.net/media/logos/VenLogo2.png

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
