### ISSUE TITLE
Add "Threat Jammer" API

### ISSUE THREAD

**Issue by diegoparrilla** [APIs-guru/openapi-directory#977]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://dublin.api.threatjammer.com/openapi.json
**Name**: Threat Jammer
**Category**: security
**Logo**: https://threatjammer.com/threatjammer-risk-score.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
