### ISSUE TITLE
Add "Meteosource Weather API" API

### ISSUE THREAD

**Issue by Meteosource** [APIs-guru/openapi-directory#978]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://www.meteosource.com/api/v1/premium/openapi.json
**Name**: Meteosource Weather API
**Category**: machine_learning
**Logo**: https://www.meteosource.com/static/logo_square.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
