### ISSUE TITLE
Add "Cradl.ai - Build document parsing APIs with deep learning" API

### ISSUE THREAD

**Issue by staalezh** [APIs-guru/openapi-directory#979]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://raw.githubusercontent.com/LucidtechAI/cradl-docs/master/static/oas.yaml
**Name**: Cradl.ai - Build document parsing APIs with deep learning
**Category**: machine_learning
**Logo**: https://uploads-ssl.webflow.com/6173d535da7f63813560c1ea/618444caa16801573ff2aa8a_cradl-ai-logo-p-500.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
