### ISSUE TITLE
Add "Yousign" API

### ISSUE THREAD

**Issue by hack3rvaillant** [APIs-guru/openapi-directory#980]
**Format**: Postman Collection
**Official**: YES
**Url**: https://www.postman.com/collections/2211403-b4a94cd1-a33f-4c5b-a263-3585b748c2d2
**Host**: https://api.yousign.com/
**Name**: Yousign
**Category**: tools
**Logo**: https://res.cloudinary.com/postman/image/upload/t_team_logo_pubdoc/v1/team/49579b05bf85ef2fdda19deb19bd3a8c7468643177c086d15b2ea713426a3250

**Comment by MikeRalphson** [comment]
Please could you provide the direct URL to your *machine-readable* API definition? Thanks.

**Comment by hack3rvaillant** [comment]
Not sure this is what you ask for but this is the link to fork the postman definition
https://elements.getpostman.com/view/fork?collection=2211403-b4a94cd1-a33f-4c5b-a263-3585b748c2d2&referrer=https%3A%2F%2Fdev.yousign.com%2F&versionTag=latest
and this is the latest json version of this definition
https://gist.github.com/hack3rvaillant/f8b88bc6ea4b6dca166d2e45120a6261

**Comment by MikeRalphson** [comment]
Thanks!

**Comment by MikeRalphson** [comment]
@hack3rvaillant - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://www.postman.com/collections/2211403-b4a94cd1-a33f-4c5b-a263-3585b748c2d2

https://www.postman.com/collections/2211403-b4a94cd1-a33f-4c5b-a263-3585b748c2d2 FCV ✔ 
Could not determine servers information
Saving metadata...
Exiting with 1

**Comment by MikeRalphson** [comment]
@hack3rvaillant - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://www.postman.com/collections/2211403-b4a94cd1-a33f-4c5b-a263-3585b748c2d2

https://www.postman.com/collections/2211403-b4a94cd1-a33f-4c5b-a263-3585b748c2d2 FCV ✔ 
Could not determine servers information
Saving metadata...
Exiting with 1

**Comment by MikeRalphson** [comment]
@hack3rvaillant - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://www.postman.com/collections/2211403-b4a94cd1-a33f-4c5b-a263-3585b748c2d2

https://www.postman.com/collections/2211403-b4a94cd1-a33f-4c5b-a263-3585b748c2d2 FCV ✔ 
Could not determine servers information
Saving metadata...
Exiting with 1

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.

**Comment by hack3rvaillant** [comment]
Thanks for the follow up
