### ISSUE TITLE
Add "Clickup" API

### ISSUE THREAD

**Issue by serviceitsecurity** [APIs-guru/openapi-directory#985]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://jsapi.apiary.io/apis/clickup20.source
**Name**: Clickup
**Category**: collaboration
**Logo**: https://app-cdn.clickup.com/assets/images/brand/clickup-symbol_color.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
