### ISSUE TITLE
Add "Eqivo Telephony API" API

### ISSUE THREAD

**Issue by cdosoftei** [APIs-guru/openapi-directory#986]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://eqivo.org/openapi.yaml
**Name**: Eqivo Telephony API
**Category**: telecom
**Logo**: https://raw.github.com/rtckit/media/master/eqivo/readme-splash.png

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
