### ISSUE TITLE
Add "Svix" API

### ISSUE THREAD

**Issue by svix-ken** [APIs-guru/openapi-directory#993]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://api.svix.com/api/v1/openapi.json
**Name**: Svix
**Category**: developer_tools
**Logo**: https://docs.svix.com/img/brand.svg

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
