### ISSUE TITLE
Add "IP2Location.io IP Geolocation" API

### ISSUE THREAD

**Issue by chrislim2888** [APIs-guru/openapi-directory#996]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://www.ip2location.io
**Name**: IP2Location.io IP Geolocation
**Category**: location
**Logo**: https://cdn.ip2location.io/assets/img/icons/android-chrome-512x512.png

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.

**Comment by chrislim2888** [comment]
Hi, you may refer to this link below. 
https://app.swaggerhub.com/apis/ip2location/ip2location-io-ip-geolocation-api/1.0

Thanks.

**Comment by chrislim2888** [comment]
Hi, can i check if any further information is needed for the listing?

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
