### ISSUE TITLE
Add "MetOcean Forecast REST API v2.0.0" API

### ISSUE THREAD

**Issue by gitmetocean** [APIs-guru/openapi-directory#998]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://www.metocean.co.nz/weather-forecast-api
**Name**: MetOcean Forecast REST API v2.0.0
**Service**: forecast
**Category**: analytics
**Logo**:

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.
